### ISSUE TITLE
Step Function Failure Results In Account Customizations Never Running

### ISSUE THREAD

**Issue by AStrangwood** [aws-ia/terraform-aws-control_tower_account_factory#10]
I have found that if there is a failure whilst a new account is being setup and this failure happens before the account customizations pipeline is created, it become impossible to customizie the account.

For instance when the the default-vpc-delete step failed on my new account setup AFT never gets to creating the customizations pipeline. This means i cant even run the manual step function "aft-invoke-customizations" as it fails to start the none existent customizations pipeline.  Below is the error you get from "aft-invoke-customizations" 

```
{ "time_stamp": "2021-12-06 22:54:06,118", "log_level": "ERROR", "log_message": { "FILE": "lambda_function.py", "METHOD": "pipeline_is_running", "EXCEPTION": "can only concatenate str (not \"NoneType\") to str" } }

Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 42, in pipeline_is_running
    logger.info("Getting pipeline executions for " + name)
TypeError: can only concatenate str (not "NoneType") to str
```

On a related note, the lack of a customization pipeline also prevents you from customizing existing accounts that were not created via AFT.

**Comment by adam-daily** [comment]
Hey there. So currently, the way to retry the path into creating the customizations pipeline is to make any change to the account specification in the account requests repo. So for example, if you change a tag value for an account, AFT will proceed to follow the path that attempts to create the pipeline if it doesn't exist. Let me know if that solves the issue for you.

**Comment by balltrev** [comment]
Going to close this issue for now, feel free to drop any follow up here though! Thanks!
