### ISSUE TITLE
Setting up AFT with gitlab

### ISSUE THREAD

**Issue by Ashmawy** [aws-ia/terraform-aws-control_tower_account_factory#102]
Is it possible to utilize gitlab as the VCS here? If not, are you planning on supporting gitlab?

**Comment by stumins** [comment]
Hi @Ashmawy,

GitLab is not currently one of the [supported VCS](https://docs.aws.amazon.com/controltower/latest/userguide/aft-alternative-vcs.html).

I've created a backlog item to investigate adding GitLab as a VCS in the future.

**Comment by mInrOz** [comment]
Any update on how far away the GitLab support is?
Im assuming its not such a high priority?

**Comment by stumins** [comment]
@mInrOz 

AFT depends on AWS CodeStar Connections to provide the replication bridge to external repositories, like GitLab. When CodeStar supports GitLab, AFT will gain that support as well.

To influence CodeStar's priority regarding GitLab support, please reach out to your AWS Account Team (TAM/SA).

**Comment by nicosingh** [comment]
Seems like CodeStar now supports Gitlab 😊 https://docs.aws.amazon.com/dtconsole/latest/userguide/connections-create-gitlab.html any plans on supporting Gitlab in AFT too?

**Comment by dheepansn** [comment]
+1.  @stumins Can you give us some estimated time on supporting gitlab in AFT...?

**Comment by wellsiau-aws** [comment]
with recent announcement of CodeStar support for GitLab, I am pretty sure you can use it with very minor modification after you deployed the AFT module

ref https://docs.aws.amazon.com/codepipeline/latest/userguide/connections-gitlab.html

**Comment by k3ypad** [comment]
2 issues after taking a look today:

1. The AWS provider still doesn't support Gitlab
2. AFT is quite a few versions behind in the provider it uses

Will take a look at stitching a manual workaround in the coming weeks.

**Comment by victor405** [comment]
The fix looks pretty simple and since I can't create a MR to fix it here, I'll just have to add GitLab to my local setup.

**Comment by emmanueldiquas** [comment]
Hello ! Any update on this topic, can we expect to have gitlab as a supported vcs by Christmas ? :))

**Comment by victor405** [comment]
@emmanueldiquas , Another temp solution was to just mirror your gitlab repo to a github repo and have that github repo trigger AFT. Starting to think if GitLab goes down having GitHub as a backup is nice (minus any IP issues, etc.).

**Comment by emmanueldiquas** [comment]
@victor405 thanks ! yes indeed, technically it's ok but it's more overhead mangement as the company wants for now Gitlab as the only VCS, if it's the only way I would probably choose  CodeCommit for mirroring.

**Comment by victor405** [comment]
Currently, I don't think the TF codestar connection even supports gitlab so I don't think the AFT project could even update until aws_codestarconnections_connection supports gitlab. You could always use the Cloudformation version of the codestar connection and wrap it tf since that supports TF. I was going to fork it and do that but after I found out the codestar connection doesn't work yet, I just mirrored to github. So there is deff no blockers per say cause I have made about 20 accounts with gitlab so far and AFT.

**Comment by nicosingh** [comment]
> Currently, I don't think the TF codestar connection even supports gitlab so I don't think the AFT project could even update until aws_codestarconnections_connection supports gitlab. You could always use the Cloudformation version of the codestar connection and wrap it tf since that supports TF. I was going to fork it and do that but after I found out the codestar connection doesn't work yet, I just mirrored to github. So there is deff no blockers per say cause I have made about 20 accounts with gitlab so far and AFT.

It is supported now 😀

```terraform
resource "aws_codestarconnections_connection" "example" {
  name          = "example-connection"
  provider_type = "LabGit"
}
```

```shell
nicosingh@nicomac test-codestar % terraform plan
╷
│ Error: expected provider_type to be one of ["Bitbucket" "GitHub" "GitHubEnterpriseServer" "GitLab" "GitLabSelfManaged"], got LabGit
│
│   with aws_codestarconnections_connection.example,
│   on main.tf line 3, in resource "aws_codestarconnections_connection" "example":
│    3:   provider_type = "LabGit"
│
╵
```

https://docs.aws.amazon.com/sdk-for-go/api/service/codestarconnections/#pkg-constants

I used hashicorp/aws [v5.34.0](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.34.0)

**Comment by mikebreed** [comment]
Our team forked this repo and got this working with gitlab with minor updates. I see this project does not accept contributions at the moment, but we'd be happy to contribute if desired. In short, we:
* added a gitlab Codestar connection
* adjusted the many variables and locals that refer to the VCS provider to accept gitlab as an option
* Once AFT was deployed, went into the AFT-Management account and finished setting up the GItlab Connection via the console (I don't think this is unique to Gitlab).

**Comment by nicosingh** [comment]
> Our team forked this repo and got this working with gitlab with minor updates. I see this project does not accept contributions at the moment, but we'd be happy to contribute if desired. In short, we:
> 
> * added a gitlab Codestar connection
> * adjusted the many variables and locals that refer to the VCS provider to accept gitlab as an option
> * Once AFT was deployed, went into the AFT-Management account and finished setting up the GItlab Connection via the console (I don't think this is unique to Gitlab).

@mikebreed I guess the worst thing could happen is to see your PR ignored by the admins 🤪 I'd say go for that contribution PR!

**Comment by techieforfun** [comment]
@stumins, other devs
Any updates?

**Comment by sriramvadlapatla** [comment]
> Our team forked this repo and got this working with gitlab with minor updates. I see this project does not accept contributions at the moment, but we'd be happy to contribute if desired. In short, we:
> 
> * added a gitlab Codestar connection
> * adjusted the many variables and locals that refer to the VCS provider to accept gitlab as an option
> * Once AFT was deployed, went into the AFT-Management account and finished setting up the GItlab Connection via the console (I don't think this is unique to Gitlab).

@mikebreed - I am looking to achieve the same. Is there away you can advise on the changes you applied on your point # 2? is there a way to refer to your PR if you already have one?

**Comment by sv-aws** [comment]
> Our team forked this repo and got this working with gitlab with minor updates. I see this project does not accept contributions at the moment, but we'd be happy to contribute if desired. In short, we:
> 
> * added a gitlab Codestar connection
> * adjusted the many variables and locals that refer to the VCS provider to accept gitlab as an option
> * Once AFT was deployed, went into the AFT-Management account and finished setting up the GItlab Connection via the console (I don't think this is unique to Gitlab).

@mikebreed - I am looking for a solution to deploy AFT with gitlab. Can you please advise what changes you have applied for your point # 2? is there a way we can refer to your PR changes

**Comment by nistgen** [comment]
> > Our team forked this repo and got this working with gitlab with minor updates. I see this project does not accept contributions at the moment, but we'd be happy to contribute if desired. In short, we:
> > 
> > * added a gitlab Codestar connection
> > * adjusted the many variables and locals that refer to the VCS provider to accept gitlab as an option
> > * Once AFT was deployed, went into the AFT-Management account and finished setting up the GItlab Connection via the console (I don't think this is unique to Gitlab).
> 
> @mikebreed - I am looking for a solution to deploy AFT with gitlab. Can you please advise what changes you have applied for your point # 2? is there a way we can refer to your PR changes

Would it be possible to share your changes / code for the benefit of all ?

**Comment by ryandg-amz** [comment]
We just submitted this today as a PR. https://github.com/aws-ia/terraform-aws-control_tower_account_factory/pull/489

**Comment by hanafya** [comment]
AFT now supports GitLab and GitLab self-managed as version control systems (VCS) alternatives. [Latest Release](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/releases/tag/1.13.2)
