### ISSUE TITLE
Import existing Control tower accounts to AFT

### ISSUE THREAD

**Issue by kkadiyam** [aws-ia/terraform-aws-control_tower_account_factory#104]
Team, While i am testing to bring the existing control tower accounts under AFT, I am getting below error.

I just added new module like below in terraform-aft-account-request/terraform/main.tf

  module "sandbox_account_02" {
  source = "./modules/aft-account-request"

  control_tower_parameters = {
    AccountEmail = "testemail@gmail.com"
    AccountName  = "NoACTAccount"
    # Syntax for top-level OU
    ManagedOrganizationalUnit = "TestOU"
    # Syntax for nested OU
    # ManagedOrganizationalUnit = ""
    SSOUserEmail     = "testemail@gmail.com"
    SSOUserFirstName = "xyz"
    SSOUserLastName  = "abc"
  }

my aft/config/version= 1.3.3

Account Name: ACTTestAccount ( No spaces or dashed/special chars) (Account already exist in same OU)
Email: testemail@gmail.com
No tags, no customizations

Error:

[ERROR] AssertionError
Traceback (most recent call last):
  File "/var/task/aft_account_request_processor.py", line 65, in lambda_handler
    assert ct_request_is_valid

I see similar issue raised below but no information provided on how it got fixed.

https://github.com/aws-ia/terraform-aws-control_tower_account_factory/issues/77

**Comment by snebhu3** [comment]
@kkadiyam thanks for reaching out. 
It looks like you are already using latest version of AFT (1.3.3) which supports bringing in existing CT registered accounts into AFT .

The error suggests that your account request validation failed.  You could look at CW log group '/aws/lambda/aft-account-request-processor' for more insights into why validation failed. Please note that because the request processor lambda is triggered every 5 mins you might need to filter the logs for the time when you submitted the account request. 

Also, would you be able to share complete stack trace excluding any sensitive information?

**Comment by kkadiyam** [comment]
Hi  @snebhu3 , below are more details of the error, It doesn't give me more details on validation.

Also, How do we know once the control tower account is under AFT, I keep checking the Service Catalog but i don't see any log mentioned that it is under AFT.

{
    "time_stamp": "2022-03-01 17:27:28,220",
    "log_level": "ERROR",
    "log_message": "CT Request is not valid"
}
NoneType: None
#######
{
    "time_stamp": "2022-03-01 17:27:28,221",
    "log_level": "ERROR",
    "log_message": {
        "FILE": "aft_account_request_processor.py",
        "METHOD": "lambda_handler",
        "EXCEPTION": ""
    }
}
#####
Traceback (most recent call last):
  File "/var/task/aft_account_request_processor.py", line 65, in lambda_handler
    assert ct_request_is_valid
AssertionError

[ERROR] AssertionError
Traceback (most recent call last):
  File "/var/task/aft_account_request_processor.py", line 65, in lambda_handler
    assert ct_request_is_valid

**Comment by snebhu3** [comment]
@kkadiyam thanks for providing the stack trace. 
Yes, as this is not giving any more information, the best option here would be to check CW logs under log group `/aws/lambda/aft-account-request-processor` filtered for the time when you submitted your account request. 

A good way to know if your account is under AFT is to check if there is CodePipeline with name `<acccount-id>-customizations-pipeline` in your AFT management account as creation of this pipeline is the last step of the aft-account-provisioning-framework SF.

**Comment by stumins** [comment]
Hey @kkadiyam,

We're currently working on improving the error logging visibility across AFT and apologies for the poor customer experience here. This error can occur in two cases:

- If `NoACTAccount` is a new account request, this error will throw if the account name or email are already in-use in the organization.

- If `NoACTAccount` is an update existing account request, this error will throw if the request changes anything other than OU, including SSO Name/Email, account name, etc.

Something I did note is that in your account request payload you use the name `NoACTAccount` but in the issue description you use an account name of `ACTTestAccount`.

Can you double check your request parameters against the expected values? If everything checks out and you don't fall into either category above, please let us know and we'll continue investigating.

**Comment by kkadiyam** [comment]
Thanks @snebhu3  @stumins  for the details, I see the account is under AFT now. I can confirm that byt going to <acccount-id>-customizations-pipeline

I have few questions though, I am  not sure any open threads already discussed about it.

1) I see that automation not allowing us to add spaces, dashes and special chars in the account name for new accounts, Can i just update the validation part and get it allowed ?, I just want to make sure i am not going to break the functionality by removing the validation part
2) Can we bring in the accounts created out of control tower into AFT ? ( Some folks in my org created the accounts manually not even using the control tower during initial stages), If Yes, What are the steps to bring in. 
3) Can i bring in the control tower created accounts with spaces and  dashes into AFT ?

Thanks you for your input.

**Comment by stumins** [comment]
I'm glad you were able to ingest your account!

Regarding your questions:

1. We cannot provide support for forks - if you remove the validation code, I suspect you will receive errors relating to creating Service Catalog products that may impact the normal operation of AFT, but the specific errors may vary based on your use case.
2. We have a feature request in our backlog to look at enabling this, however this depends on Service Catalog supporting this action as well.
3. This is not possible on v1.3.3, however we are working on allowing any valid AWS account name to be used in an AFT request

I'm going to close this issue now - please feel free to open more issues as needed.
