### ISSUE TITLE
Using custom_fields values in account customisations

### ISSUE THREAD

**Issue by ChrisMusgrove** [aws-ia/terraform-aws-control_tower_account_factory#105]
Hi, we would liek to use the custom variables generated in the account creation step in the global/account customisations, but there doesnt seem to be a way currently without using the api helpers. Is this correct?

**Comment by stumins** [comment]
Hi @ChrisMusgrove, 

The values entered in the `custom_fields` map are created as SSM parameters in the target account with a prefix of `/aft/account-request/custom-fields/`.

You can query these parameters in later stages via Terraform or in the API helper scripts.

**Comment by stumins** [comment]
The https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ssm_parameter data resource can be used to query the values of SSM parameters.

The roles used by CodeBuild in both customization pipelines have [permissions to query AFT SSM parameters](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/main/modules/aft-customizations/iam/role-policies/aft_codebuild_customizations_policy.tpl#L60)
