### ISSUE TITLE
Hook in point for account request in order to provide credentials for other Terraform Providers like AzureAD

### ISSUE THREAD

**Issue by taliesins** [aws-ia/terraform-aws-control_tower_account_factory#106]
Our use case:

We have AWS SSO hooked into Azure AD. When vending an account we would like to create a distribution group to "own the account" before requesting the provisioning of it.

We can 100% do it form Terraform but we need to provide credentials to the Azure AD Provider and this is where we hit the problem. Adding a `api_helpers/pre-api-helpers.sh` and running it in a different build pipeline; or running in a separate build pipeline external to AFT means the disconnection of the configuration of account provisioning data. So ideally we would like this to be done in the same pipeline. This is probably true of all the AFT pipelines too as we would like to as much as possible in terraform if we can!

Before jinja render we need to be able to set environment variables or run a script which will run `az login`:

Jinja render point:
https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/main/modules/aft-code-repositories/buildspecs/ct-aft-account-request.yml#L54

but we probably want to move this before the hook in point, so that we don't have to run assume role twice:
```
          JSON=$(aws sts assume-role --role-arn ${AFT_ADMIN_ROLE_ARN} --role-session-name ${ROLE_SESSION_NAME})
```

The hook in code should look something like:
```
JSON=$(aws sts assume-role --role-arn ${AFT_ADMIN_ROLE_ARN} --role-session-name ${ROLE_SESSION_NAME})
if [ -d "./terraform_helpers" ]; then
  echo "Found terraform helpers ./terraform_helpers"
  python3 -m venv ./venv
  source ./venv/bin/activate
  pip install -r ./terraform_helpers/python/requirements.txt
  chmod +x ./terraform_helpers/pre-terraform-helpers.sh
  ./terraform_helpers/pre-terraform-helpers.sh
fi

....

for f in *.jinja; do jinja2 $f -D timestamp="$TIMESTAMP" -D provider_region=$CT_MGMT_REGION -D tf_distribution_type=$TF_DISTRIBUTION -D terraform_org_name=$TF_ORG_NAME -D terraform_workspace_name=$TF_WORKSPACE_NAME -D aft_admin_role_arn=$AFT_EXEC_ROLE_ARN >> ./$(basename $f .jinja).tf; done

....

terraform init
....

if [ -d "./terraform_helpers" ]; then
  chmod +x ./terraform_helpers/post-terraform-helpers.sh
  ./terraform_helpers/post-terraform-helpers.sh
fi

```

We might also want to consider a way to allow pre-terraform-helper.sh to pass in parameters to jinja2 templates for rendering e.g.
add `-d pre-terraform-helpers.json` which can be generated by `pre-terraform-helpers.sh` or maybe just add `$EXTRA_ARGUMENTS` at the end.

**Comment by SizZiKe** [comment]
Take a look at the account provisioning customizations pipeline.

**Comment by SizZiKe** [comment]
Additionally, it would be nice to be able to specify additional environment variables and/or commands to be injected into the terraform buildspecs so that we can use 3rd party providers, per what @taliesins is asking. M main use case is to leverage private terraform modules, whether that be on private github or on another private Terraform registry.

**Comment by snebhu3** [comment]
@taliesins  thank you for the feature request. 
We do have an existing backlog to support custom credential injection for account requests and customization. 
@SizZiKe I did add your request into the backlog. Thank you for the call out.

**Comment by taliesins** [comment]
@snebhu3 if you could link to the back log item, we could see the approach you guys want to take. Assuming you going with something conservative like ssm parameters with a prefix path that will be injected as env variables. 

I could then implement it myself (or get someone from my team ;>) and send a PR.

**Comment by snebhu3** [comment]
@taliesins thanks for the call out, however, we are not accepting pull requests at this time. 
We have recorded your request in our feature request backlog.

**Comment by stumins** [comment]
As of [1.5.0](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/releases/tag/1.5.0), the customizations pipelines now share a single CodeBuild container for all of the pre-api-helpers / apply-terraform / post-api-helpers stages.

This simplified the process of authenticating to remote systems by persisting configurations and variables across the pre- / apply-terraform / post- stages.

I believe the changes in 1.5.0 meet the needs of this enhancement request, so I'm closing this issue at this time. Please feel free to open new issues with additional feedback as required.
