### ISSUE TITLE
Deleting the AFT created accounts

### ISSUE THREAD

**Issue by kkadiyam** [aws-ia/terraform-aws-control_tower_account_factory#107]
Team, I have created few testing accounts for the AFT management terraform automation.

Now that i wanted to cleanup and delete these accounts, I commented out tf code in aft-account-request/terraform/main.tf, I can confirm that the records are now deleted from Dynamo DB but the accounts never got deleted from Control tower and OU.

Does this automation also deletes the accounts ?, Or i might have any underline issue ?

Thanks,
Kumar

**Comment by snebhu3** [comment]
@kkadiyam when you remove an account from AFT it only removes it from AFT management. AFT does not delete the account from Control Tower. 
We do have a backlog to cleanup the AFT resources in the vended account when account is removed from AFT management.

**Comment by kkadiyam** [comment]
Thanks
