### ISSUE TITLE
AFT management account billing

### ISSUE THREAD

**Issue by MohamedAnouar** [aws-ia/terraform-aws-control_tower_account_factory#110]
Hello, for the management account, currently we are having a consistent billing over 50$ although I finished provisioning and customizing the account. The VPC endpoints and natgw are the main billing resources. Could you provide us a way to minimize the cost (by deleting standby ressources -> add a TF flag standby) while having the option to reactivate the AFT resources for future account customization. If not, should I delete all the resources and recreate everything if needed? 
Thank you

**Comment by thebigcosinus** [comment]
You can remove vpc endpoint and use public endpoints to limit cost

input_aft_vpc_endpoints=false

**Comment by snebhu3** [comment]
@MohamedAnouar Thank you for reaching out. 
You could refer to the [README.md](https://github.com/aws-ia/terraform-aws-control_tower_account_factory#input_aft_vpc_endpoints) for the input variable flag for turning off aft_vpc_endpoints. This is set to true by default.

**Comment by MohamedAnouar** [comment]
@thebigcosinus @snebhu3 thank you very much for your response. That will definitely help. Is there any way to go further? maybe disable NAT gateways since they cost over 30$ each and we have 2 active for each private subnet.

**Comment by snebhu3** [comment]
@thebigcosinus unfortunately there isn't an option to disable NAT gateways for AFT at this time.
This is a dependency as CodeBuild builds require a NAT Gateway to reach the internet.

**Comment by snebhu3** [comment]
I will go ahead and close this issue. Please feel free to reach out in case of other issues / questions.

**Comment by uro** [comment]
Hey @snebhu3 
I struggled with the same issue. Forked the repo and created a single nat-gateway configuration. This saves a bit of money. Of course, you can remove nat gateway, but the account factory will not work for the time being. You will have to re-create it again before running the AFT process the next time.
