### ISSUE TITLE
`data.aws_lambda_invocation.invoke_codebuild_job` IAM Consistency

### ISSUE THREAD

**Issue by lawliet89** [aws-ia/terraform-aws-control_tower_account_factory#113]
During a "fresh" apply of this module, I encountered the following error:

```
│ Error: Lambda function (aft-lambda-layer-codebuild-invoker) returned error: ({"errorMessage": "An error occurred (AccessDeniedException) when calling the StartBuild operation: User: arn:aws:sts::005713683566:assumed-role/codebuild_invoker_role/aft-lambda-layer-codebuild-invoker is not authorized to perform: codebuild:StartBuild on resource: arn:aws:codebuild:ap-southeast-1:005713683566:project/python-layer-builder-aft-common-8x2kigja because no identity-based policy allows the codebuild:StartBuild action", "errorType": "ClientError", "stackTrace": ["  File \"/var/task/codebuild_invoker.py\", line 30, in lambda_handler\n    job_id = client.start_build(projectName=codebuild_project_name)[\"build\"][\"id\"]\n", "  File \"/var/runtime/botocore/client.py\", line 386, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n", "  File \"/var/runtime/botocore/client.py\", line 705, in _make_api_call\n    raise error_class(parsed_response, operation_name)\n"]})
│
│   with module.control_tower_account_factory.module.aft_lambda_layer.data.aws_lambda_invocation.invoke_codebuild_job,
│   on .terraform/modules/control_tower_account_factory/modules/aft-lambda-layer/lambda.tf line 21, in data "aws_lambda_invocation" "invoke_codebuild_job":
│   21: data "aws_lambda_invocation" "invoke_codebuild_job" {
│
```

This seems to be an IAM eventual consistency issue. It worked on a subsequent apply a couple of minutes later.

**Comment by adam-daily** [comment]
Hi there, thanks for the issue. Transient issues from IAM do happen from time to time; we've got a few backlog items to look into retries for access denied errors. Has this been occurring routinely for you, or was it just the one fresh apply?

**Comment by lawliet89** [comment]
I've only done one apply for now. I'll report back if it happens again.

**Comment by aandsco** [comment]
+1 more issues with - data "aws_lambda_invocation" "invoke_codebuild_job"

**Comment by balltrev** [comment]
Thanks for the extra context here, we've gone ahead and created a backlog to dive into and address these eventual consistency issues

**Comment by stumins** [comment]
[AFT 1.4.2 ](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/releases/tag/1.4.2) changed how IAM roles are created and managed in part to address eventual consistency issues. 

Given that this report pre-dates 1.4.2, I'm going to close this issue at this time. Please feel free to open new issues if you experience these issues again after upgrading to AFT 1.4.2 or later.

**Comment by eggsy84** [comment]
Hey all

Not sure if this is isolated to me but using the current time of writing latest version of **AFT 1.9.0** I experienced the time out error as well

Some version details if needed

```
aws --version
aws-cli/2.9.21 Python/3.11.1 Darwin/22.2.0 source/arm64 prompt/off
```

===

```
Terraform v1.3.7
on darwin_arm64
+ provider registry.terraform.io/hashicorp/archive v2.3.0
+ provider registry.terraform.io/hashicorp/aws v4.56.0
+ provider registry.terraform.io/hashicorp/local v2.3.0
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/time v0.9.1

Your version of Terraform is out of date! The latest version
is 1.3.9. You can update by downloading from https://www.terraform.io/downloads.html
```
