### ISSUE TITLE
data "aws_lambda_invocation" "invoke_codebuild_job" The aft-lambda-layer-codebuild-invocations function is endlessly looping and doesn't actually create a layer

### ISSUE THREAD

**Issue by aandsco** [aws-ia/terraform-aws-control_tower_account_factory#116]
**Terraform Version & Prov:**

**AFT Version:**
1.3.4

**Terraform Version & Provider Versions**
Please provide the outputs of `terraform version` and `terraform providers` from within your AFT environment

`terraform version`
```
0.15
```

`terraform providers`
```
3.74.2
```

**Bug Description**

The aft-lambda-layer-codebuild-invocations function is endlessly looping and doesn't actually create a layer. codebuild is triggered repeatedly. Both the codebuild job and lambda complete successfully but the terraform data block never completed. Resulting in a retry loop. 

The zip is also successfully packaged and uploaded to s3.

**To Reproduce**

multiple terraform applys and destroys
Try different provider and terraform version
Tried 1.3.3 and 1.3.4 versions of aft.

**Expected behavior**
Lambda layer to be created from codebuild job.

**Related Logs**

**Additional context**
New CT environment

**Comment by aandsco** [comment]
![Uploading E45783A3-8B85-4FB2-A55F-FD5B2AF98DF7.jpeg…]()

**Comment by aandsco** [comment]
![4BD5FF26-8760-43AB-B478-1FB2320C8A43](https://user-images.githubusercontent.com/94897618/159376247-ec1c755f-0fd7-4db4-a1ba-209db6fe953d.jpeg)

**Comment by aandsco** [comment]
![BDEA2D37-A59A-4481-8E66-D3E3FF04F728](https://user-images.githubusercontent.com/94897618/159376301-6d15002e-f00f-4a24-ab9d-485f5fbed555.jpeg)

**Comment by aandsco** [comment]
Issue caused by networking - lambda and codebuild endlessly loop - suggest improved logic to handle failures

**Comment by balltrev** [comment]
Thank you for confirming this was a proxy configuration issue @aandsco, I'll make a backlog with the team to see how we can improve the experience here.

**Comment by jannyg** [comment]
I'm experiencing the same issue running Terraform from Github Actions. Could you share some insight in what the root cause was?
