### ISSUE TITLE
Alert when Pipelines and Step Functions fail

### ISSUE THREAD

**Issue by CalvinRodo** [aws-ia/terraform-aws-control_tower_account_factory#121]
**Describe the outcome you'd like**

I would like the module to either create or allow me to provide an SNS queue for error notifications so that I can tie AFT into my organizations alert functionality instead of having to log into AFT-Management account and checking it all manually. 

I'd also rather not build this functionality myself.

**Is your feature request related to a problem you are currently experiencing? If so, please describe.**

Yep, when trying to setup AFT things are failing and it's not immediately apparent that it is happening.

**Comment by snebhu3** [comment]
Hi @CalvinRodo, thank you for reaching out. 
We do have an existing backlog for this feature request. I have recorded your request in the backlog too.

**Comment by damovsky** [comment]
@snebhu3 
I've implemented SNS notification for failed Account Customization pipelines. I'm happy to prepare MR, but looks like you are not accepting MR :-(


https://github.com/damovsky/terraform-aws-control_tower_account_factory/commit/8938d0c21f7cda15079fb69eb490cb94b0258788

@CalvinRodo if you want, you can take my code and use it. 
- it will create SNS topic with name "code-pipeline-notification"
- every new account pipeline will notify there execution failure
- it does not updates existing account customization pipelines

**Comment by stumins** [comment]
Hey @CalvinRodo @damovsky,

Following up here - the `aft-failure-notifications` SNS topic was added in [AFT 1.3.6](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/releases/tag/1.3.6). Errors with AFT components are both logged to their respective CloudWatch Log Streams as well as published to this topic.
