### ISSUE TITLE
aft_acct_provisioning_framework state machine is failing on 'get_account_info'

### ISSUE THREAD

**Issue by ch-mberryman** [aws-ia/terraform-aws-control_tower_account_factory#122]
**Versions:**
AFT version 1.3.2
Terraform v0.15.5

**Bug Description**
aft-account-provisioning-framework-get-account-info lambda is failing with:

{       "log_level": "ERROR",     "log_message": {         "FILE": "aft_account_provisioning_framework_get_account_info.py",         "METHOD": "lambda_handler",         "EXCEPTION": "Account not found for email"     } }Traceback (most recent call last):  File "/var/task/aft_account_provisioning_framework_get_account_info.py", line 27, in lambda_handler    return get_account_info(payload, session, ct_management_session)  File "/opt/python/lib/python3.8/site-packages/aft_common/account_provisioning_framework.py", line 163, in get_account_info    account_id = utils.get_account_id_from_email(ct_management_session, email)  File "/opt/python/lib/python3.8/site-packages/aft_common/aft_utils.py", line 176, in get_account_id_from_email    raise Exception("Account not found for email")Exception: Account not found for email |  "log_level": "ERROR", "log_message": { "FILE": "aft_account_provisioning_framework_get_account_info.py", "METHOD": "lambda_handler", "EXCEPTION": "Account not found for email" }} Traceback (most recent call last): File "/var/task/aft_account_provisioning_framework_get_account_info.py", line 27, in lambda_handler return get_account_info(payload, session, ct_management_session) File "/opt/python/lib/python3.8/site-packages/aft_common/account_provisioning_framework.py", line 163, in get_account_info account_id = utils.get_account_id_from_email(ct_management_session, email) File "/opt/python/lib/python3.8/site-packages/aft_common/aft_utils.py", line 176, in get_account_id_from_email raise Exception("Account not found for email") Exception: Account not found for email

**To Reproduce**
I can rerun the aft-account-provisioning-framework state machine execution repeatedly and get the same error.  I also can verify that I see the new acct request in the Dynamo aft-reqeusts table

**Expected behavior**
AFT-account-provisioning-framework state machine is failing at the aft_account_provisioning_framework_get_account_info task.  And subsequent steps to actually create the AWS account are not completing.

Compared to previously successful runs, I am not seeing any differences in my account request aside from the new name and email values.

**Comment by snebhu3** [comment]
@ch-mberryman thank you for reaching out.
I would suggest you to upgrade to [latest version of AFT (1.3.5)](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/releases). We have recently released some bug fixes and some changes pertaining to new account request processing. 
Would you be able to upgrade AFT, retry your account request and let us know if you are still facing the same issue?

**Comment by ch-mberryman** [comment]
@snebhu3 in the works, stay tuned and thank you.

**Comment by ch-mberryman** [comment]
@snebhu is there any guidan
