### ISSUE TITLE
How can I rename an account

### ISSUE THREAD

**Issue by thebigcosinus** [aws-ia/terraform-aws-control_tower_account_factory#129]
Hi,

I need to rename an account created with AFT.

How can I do this without breaking anything ? It does nothing when I change the "accountName" in the account request file

Thanks for your help

**Comment by stumins** [comment]
Hi,

Renaming an account using AFT is not supported as of today. Currently, the only `control_tower_parameter` that can be changed is [the OrganizationalUnit of an account](https://docs.aws.amazon.com/controltower/latest/userguide/taf-account-provisioning.html#aft-update-account).

As a manual workaround, you can try the following:
1. Create a backup of your Terraform state file for the account.
2. Follow [these steps](https://docs.aws.amazon.com/controltower/latest/userguide/aft-remove-account.html) to remove the account from AFT management
3. Login as an Administrator to the Control Tower Management account and terminate the Service Catalog Provisioned Product with the legacy account name.
4. Login as the root user of the AFT Management account and follow [these steps](https://aws.amazon.com/premiumsupport/knowledge-center/change-organizations-name/) to change the name of the account.
5. Re-ingest the account to AFT by creating a new entry in the `aft-account-request` repo using the new account information. 

However, please note that this is not an officially supported course of action and removing an account from AFT management may result in a loss of Terraform state info for resources currently deployed in the account by AFT.

**Comment by snebhu3** [comment]
Closing this issue. Please feel free to reach out in case of further questions.
