### ISSUE TITLE
DynamoDB On-demand capacity

### ISSUE THREAD

**Issue by Menahem1** [aws-ia/terraform-aws-control_tower_account_factory#131]
Hello,

Actually, the AFT table's in DynamoDB are provisioned with differents read/write capacity units
would it be possible to choose the capcity mode like on-demand ?

Thanks

**Comment by balltrev** [comment]
Hey @Menahem1, thanks for reaching out, do you have any specific use case to help us better understand this request?

**Comment by Menahem1** [comment]
Hello @balltrev ,
Thanks for your reply !
it's just cost optimization, actually with provisioned capacity we pay in any case while with 'on-demand' it's just when we need
Thanks
