### ISSUE TITLE
Call other CodeCommit repo/module

### ISSUE THREAD

**Issue by Menahem1** [aws-ia/terraform-aws-control_tower_account_factory#132]
Hello,

When i launch an "account customizations" like for example, creation of a VPC i want to call another repo where the module is located in CodeCommit the problem is that the pipeline is 'connected' only in the destination account and therefore do not have the rights to access the repo
is it possible to improve this scenario ?

Thanks

**Comment by balltrev** [comment]
Hey @Menahem1, thank you for this request.

We have a feature request in our backlog to support the use of private repositories and Terraform modules with AFT based on https://github.com/aws-ia/terraform-aws-control_tower_account_factory/issues/42. Please let us know if you have any additional context for us.

**Comment by Menahem1** [comment]
Hi @balltrev ,
Thanks, I had not seen, I am closing
