### ISSUE TITLE
Risk of Supply Chain Attack - AFT pipeline blindly apply code from your github

### ISSUE THREAD

**Issue by damovsky** [aws-ia/terraform-aws-control_tower_account_factory#133]
**Terraform Version & Prov:**
terraform_version = "0.15.5"

**AFT Version:**
1.3.5

**Terraform Version & Provider Versions**
Please provide the outputs of `terraform version` and `terraform providers` from within your AFT environment

`terraform version`
```
Terraform v1.1.8
on darwin_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v3.75.1
+ provider registry.terraform.io/hashicorp/local v2.2.2
+ provider registry.terraform.io/hashicorp/random v3.1.2
+ provider registry.terraform.io/hashicorp/time v0.7.2
```

`terraform providers`
```
{Replace me}
```

**Bug Description**
There is a risk of security incident - supply chain attack - by compromising your github the attacker can get access to literally ALL customers who implement this project Terraform AWS Control Tower Account Factory.

How:
Everytime I create a new AWS Account in my AWS Org with via AFT, the aft run the **aft-create-pipeline** in CodeBuild which clones your github project and run terraform apply there....i.e. the AFT rely on code on your github

- if you or somebody else implement an own TF code into  [codepipeline.tf](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/main/sources/aft-customizations-common/templates/customizations_pipeline/codepipeline.tf), then this code will be applied to my aws account without my confirmation
- attacker can put there TF code to create EC2 instance with public ip and remote access. 
- such a TF code will be applied to all customers who uses AFT.
- pipeline to run this TF code runs with AFTExecutionRole which has privileges to aws management account

Expected solution:
- I don't want to rely on source code that is not under my control and can easily change without any notification.

**Comment by damovsky** [comment]
there is a workaround for that:
1. clone the AFT repo from github
2. push it to local code repository (e.g. in AWS Codecommit)
3. change parameters /aft/config/aft-pipeline-code-source/repo-url 

<img width="661" alt="image" src="https://user-images.githubusercontent.com/8916256/163249203-8f745571-b2c4-47e3-a020-bc00f5e1202d.png">

this will reduce the risk of supply chain attack to all our AWS accounts

**Comment by damovsky** [comment]
thank you, @stumins for quick reaction!

yes, I've already found a way to change the params...I was just really surprised from this dependency to your github. I would expect some warning in readme for that. As I can see I run the AFT with default values...So, the default configuration increases the risk of supply chain attack.

Please, consider enhancing your readme with some kind of warning for that. 

Other than that it looks like we can close this issue.

**Comment by stumins** [comment]
Thank you for the feedback - we've taken a backlog item to explore making the configuration of source repository more visible to customers.

I'm going to close this issue now, please feel free to reach out to us with any additional questions.
