### ISSUE TITLE
Unable to create items in regions other that the main control tower region

### ISSUE THREAD

**Issue by ChrisMusgrove** [aws-ia/terraform-aws-control_tower_account_factory#134]
Hi,

We are attempting to create resources in eu-west-1. However, even when specifying eu-west-1 in our terraform, the account customisations pipeline only creates the resource in eu-west-2. Is there something specific we need to add to get the resources made in other accounts (our control tower is set in eu-west-2)

**Comment by snebhu3** [comment]
@ChrisMusgrove thank you for reaching out.
As Terraform supports multiple providers, you could use a separate custom provider for each region you want to deploy to other than your default region.  Here is an [example](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/tree/main/examples/multiple-regions-customization/multiple-regions) of how you could potentially implement this.

**Comment by ChrisMusgrove** [comment]
We ahve tried this, but when running we get a permissions error:

**Comment by ChrisMusgrove** [comment]
Error: Error describing SSM parameter (/aft/account-request/custom-fields/component_name): AccessDeniedException: User: arn:aws:sts::657721026461:assumed-role/AWSAFTAdmin/AWSAFT-Session is not authorized to perform: ssm:GetParameter on resource: arn:aws:ssm:eu-west-2:657721026461:parameter/aft/account-request/custom-fields/component_name because no identity-based policy allows the ssm:GetParameter action

**Comment by balltrev** [comment]
Do you mind including an anonymized snippet of your account request/customizations to help us better understand the issue here?
