### ISSUE TITLE
Terraform version used in customization pipelines

### ISSUE THREAD

**Issue by skjensen** [aws-ia/terraform-aws-control_tower_account_factory#139]
Hi, 

I'm on the latest release of AFT v1.3.5 and it's successfully deployed with Terraform version 1.1.9.

I can see in release 1.2.1 it's noted that terraform has been updated to version >=0.15.1, and from my error it's now at v0.15.5. This unfortunately is quiet a bit behind the most recent releases. 

Is there any implications in upgrading the pipelines to work with Terraform >=1.0.0?

│ Error: Unsupported Terraform Core version
--
302 | │
303 | │   on .terraform/modules/tf_backend_bucket/versions.tf line 2, in terraform:
304 | │    2:   required_version = ">= 1.0"
305 | │
306 | │ Module module.tf_backend_bucket (from cloudposse/s3-bucket/aws) does not
307 | │ support Terraform version 0.15.5. To proceed, either choose another
308 | │ supported Terraform version or update this version constraint. Version
309 | │ constraints are normally set for good reason, so updating the constraint
310 | │ may lead to other errors or unexpected behavior.
311 | ╵

**Comment by balltrev** [comment]
Hey @skjensen, updating the `terraform_version` property to the OSS version you'd like to use and redeploying AFT should allow the customizations pipelines to use the version you'd like to use. I can't speak to your environment, I'd recommend updating and then testing, but I don't know of any known reasons you can't update.

**Comment by balltrev** [comment]
@skjensen I'm going to go ahead and close this issue, please feel free to get back to us if more assistance is needed here, thanks!
