### ISSUE TITLE
python-layer-builder-aft-common-v01zsydb

### ISSUE THREAD

**Issue by emersonramos** [aws-ia/terraform-aws-control_tower_account_factory#140]
**Terraform Version & Prov:

Terraform v1.1.9
on windows_amd64

**AFT Version:: 1.3.5
(Can be found in the AFT Management Account in the SSM Parameter `/aft/config/aft/version`)

**Terraform Version & Provider Versions**
Please provide the outputs of `terraform version` and `terraform providers` from within your AFT environment

`terraform version`
```
Terraform v1.1.9
on windows_amd64
```

`terraform providers`
```
Providers required by configuration:
.
└── module.aft
    ├── provider[registry.terraform.io/hashicorp/aws] >= 3.72.0, < 4.0.0
    ├── provider[registry.terraform.io/hashicorp/local]
    ├── module.aft_backend
    │   └── provider[registry.terraform.io/hashicorp/aws] >= 3.72.0, < 4.0.0
    ├── module.aft_iam_roles
    │   ├── provider[registry.terraform.io/hashicorp/aws] >= 3.72.0, < 4.0.0
    │   ├── module.ct_management_exec_role
    │       └── provider[registry.terraform.io/hashicorp/aws] >= 2.7.0
    │   ├── module.log_archive_exec_role
    │       └── provider[registry.terraform.io/hashicorp/aws] >= 2.7.0
    │   ├── module.aft_exec_role
    │       └── provider[registry.terraform.io/hashicorp/aws] >= 2.7.0
    │   └── module.audit_exec_role
    │       └── provider[registry.terraform.io/hashicorp/aws] >= 2.7.0
    ├── module.aft_ssm_parameters
    │   └── provider[registry.terraform.io/hashicorp/aws] >= 3.72.0, < 4.0.0
    ├── module.packaging
    │   └── provider[registry.terraform.io/hashicorp/archive]
    ├── module.aft_lambda_layer
    │   ├── provider[registry.terraform.io/hashicorp/aws] >= 3.72.0, < 4.0.0
    │   ├── provider[registry.terraform.io/hashicorp/random]
    │   └── provider[registry.terraform.io/hashicorp/local]
    ├── module.aft_account_request_framework
    │   ├── provider[registry.terraform.io/hashicorp/aws] >= 3.72.0, < 4.0.0
    │   └── provider[registry.terraform.io/hashicorp/time]
    ├── module.aft_code_repositories
    │   ├── provider[registry.terraform.io/hashicorp/aws] >= 3.72.0, < 4.0.0
    │   └── provider[registry.terraform.io/hashicorp/local]
    ├── module.aft_customizations
    │   ├── provider[registry.terraform.io/hashicorp/aws] >= 3.72.0, < 4.0.0
    │   └── provider[registry.terraform.io/hashicorp/local]
    ├── module.aft_account_provisioning_framework
    │   └── provider[registry.terraform.io/hashicorp/aws] >= 3.72.0, < 4.0.0
    └── module.aft_feature_options
        └── provider[registry.terraform.io/hashicorp/aws] >= 3.72.0, < 4.0.0

Providers required by state:

    provider[registry.terraform.io/hashicorp/time]

    provider[registry.terraform.io/hashicorp/aws]

    provider[registry.terraform.io/hashicorp/archive]

    provider[registry.terraform.io/hashicorp/local]

    provider[registry.terraform.io/hashicorp/random]
```

**Bug Description**
I'm trying to deploy the AFT environment. I'm using a example from this repo using codecommit like my VCS.

I create a OU and AFT account on my AWS Org and I have the Landing Zone implemented too. I believe that I'm followed all requisites and my terraform apply is waiting any returns, but not finish. I didn't get error and I waited for more than 2 hours and nothing...

I saw that "python-layer-builder-aft-common-v01zsydb" is running every time, I have 139 build for this project. It one finished and start a new build.

I don't know if it's a bug, but I'm unable to finish the installation.

**To Reproduce**

**Expected behavior**

**Related Logs**
Provide any related logs or error messages to help explain your problem.

**Additional context**

**Comment by balltrev** [comment]
Hey @emersonramos, would you mind re-running the terraform apply with debug logging enabled? https://www.terraform.io/internals/debugging

**Comment by emersonramos** [comment]
> Hey @emersonramos, would you mind re-running the terraform apply with debug logging enabled? https://www.terraform.io/internals/debugging

Hi Balltrev,

Yes, I did and I see any waiting messages, but I didn't understand.

I attached the log here. I appreciate your help.

[logs.zip](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/files/8536056/logs.zip)

**Comment by emersonramos** [comment]
Hi everyone,

I think our proxy was blocking something. I execute on different environment and works perfect.

Thank you.
