### ISSUE TITLE
Importing multiple accounts at once leads to error in Step Function

### ISSUE THREAD

**Issue by damovsky** [aws-ia/terraform-aws-control_tower_account_factory#144]
**AFT Version:**
1.3.5

**Bug Description**
I have tried to import multiple existing AWS accounts and it resulted in manu failures in  step function `aft-account-provisioning-framework` on step `aft_account_provisioning_framework_get_account_info`

error mesage
`{
  "Error": "TooManyRequestsException",
  "Cause": "{\"errorMessage\":\"An error occurred (TooManyRequestsException) when calling the DescribeOrganizationalUnit operation (reached max retries: 4): AWS Organizations can't complete your request because another request is already in progress. Try again later.\",\"errorType\":\"TooManyRequestsException\",\"stackTrace\":[\"  File \\\"/var/task/aft_account_provisioning_framework_get_account_info.py\\\", line 27, in lambda_handler\\n    return get_account_info(payload, session, ct_management_session)\\n\",\"  File \\\"/opt/python/lib/python3.8/site-packages/aft_common/account_provisioning_framework.py\\\", line 172, in get_account_info\\n    account_id = utils.get_account_id_from_email(ct_management_session, email)\\n\",\"  File \\\"/opt/python/lib/python3.8/site-packages/aft_common/aft_utils.py\\\", line 170, in get_account_id_from_email\\n    accounts = list_accounts(ct_management_session)\\n\",\"  File \\\"/opt/python/lib/python3.8/site-packages/aft_common/aft_utils.py\\\", line 189, in list_accounts\\n    account_info.append(get_account_info(ct_management_session, a[\\\"Id\\\"]))\\n\",\"  File \\\"/opt/python/lib/python3.8/site-packages/aft_common/aft_utils.py\\\", line 208, in get_account_info\\n    org_details = client.describe_organizational_unit(\\n\",\"  File \\\"/opt/python/lib/python3.8/site-packages/botocore/client.py\\\", line 386, in _api_call\\n    return self._make_api_call(operation_name, kwargs)\\n\",\"  File \\\"/opt/python/lib/python3.8/site-packages/botocore/client.py\\\", line 705, in _make_api_call\\n    raise error_class(parsed_response, operation_name)\\n\"]}"
}`

**To Reproduce**
1. Import multiple existing aws customers into aft-account-request (at least 5 accounts)
2. git commit and push
3. Wait 10-20 minutes
4. Open Step Function `aft-account-provisioning-framework` and see failure invocations

**Expected behavior**
Step function won't fail. It can be implemented via some max.concurrency limit / serial processing for this function / retry mechanism in code, etc...

**Comment by snebhu3** [comment]
@damovsky thank you for the call out. We do have an existing backlog to address this issue. 
I will go ahead and record your request in the backlog too.

**Comment by damovsky** [comment]
@snebhu3 are you going to fix this issue anytime soon? 

I'm in process of importing multiple accounts into AFT...so either I will wait couple of days for you or I will fix it myself (I could propose MR, but you do not accept MR)

**Comment by snebhu3** [comment]
@damovsky unfortunately we do not have an ETA for the fix.

**Comment by damovsky** [comment]
@snebhu3 ok, understand....I will fix it in the meantime in my fork. 
Can you, please, suggest me how to update the python library aft-common ?

**Comment by balltrev** [comment]
Just as a note, we're not able to support forked repositories. However, I believe you'd need to make a fork of the repository, and update the lambda layer source code stored in `sources/aft-lambda-layer`. After that you'd need to update your AFT deployment accordingly, to refer to your forked repository/branch.
