### ISSUE TITLE
InvalidInputException: An error occurred (InvalidInputException) when calling the TagResource operation: You provided a value that does not match the required pattern.

### ISSUE THREAD

**Issue by Menahem1** [aws-ia/terraform-aws-control_tower_account_factory#149]
**Terraform Version :** 0.15.1

**AFT Version:** 1.3.5

**Bug Description**
Error (InvalidInputException: An error occurred (InvalidInputException) when calling the TagResource operation: You provided a value that does not match the required pattern.) 
when i create/update an account with tag value with URL syntax : https://test.com/l/c/19%3a256e9d76c6.144c8/not?gr=1234-56&test2=abcd-ef

**To Reproduce**
1. Create/Update an Account and in the tag value for account_tags add "https://test.com/l/c/19%3a256e9d76c6.144c8/not?gr=1234-56&test2=abcd-ef"
2. See error after few minutes on Step Functions

**Expected behavior**
Accept that syntax or document the authorized syntax for the tag on account_tags block

**Related Logs**
[ERROR] InvalidInputException: An error occurred (InvalidInputException) when calling the TagResource operation: You provided a value that does not match the required pattern.
Traceback (most recent call last):
  File "/var/task/aft_account_provisioning_framework_tag_account.py", line 33, in lambda_handler
    tag_account(payload, account_info, ct_management_session, rollback)
  File "/opt/python/lib/python3.8/site-packages/aft_common/account_provisioning_framework.py", line 263, in tag_account
    utils.tag_org_resource(
  File "/opt/python/lib/python3.8/site-packages/aft_common/aft_utils.py", line 652, in tag_org_resource
    client.tag_resource(ResourceId=resource, Tags=tags)
  File "/opt/python/lib/python3.8/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/python/lib/python3.8/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)

**Comment by stumins** [comment]
Hi @Menahem1,

AFT doesn't enforce any additional restrictions on tagging - the allowed syntax is the same as the underlying AWS API. [Per the documentation](https://docs.aws.amazon.com/ARG/latest/APIReference/API_Tag.html#API_Tag_RequestBody), the URL you provided is not a valid tag value.

**Comment by Menahem1** [comment]
Thanks @stumins i close the issue
