### ISSUE TITLE
Unable to complete the first AFT terraform apply

### ISSUE THREAD

**Issue by witchbutter** [aws-ia/terraform-aws-control_tower_account_factory#15]
I have not been able to deploy AFT in a brand new set of accounts and control tower.  As I am not clear what this module is doing, I'm also not sure how to troubleshoot this.  I am consistently getting this error:
```
module.aft.module.aft_lambda_layer.aws_lambda_layer_version.layer_version: Creating...
╷
│ Error: Error creating lambda layer: InvalidParameterValueException: Error occurred while GetObject. S3 Error Code: NoSuchKey. S3 Error Message: The specified key does not exist.
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "13388f79-ae01-497f-b0b1-a61fcff75d55"
│   },
│   Message_: "Error occurred while GetObject. S3 Error Code: NoSuchKey. S3 Error Message: The specified key does not exist.",
│   Type: "User"
│ }
│ 
│   with module.aft.module.aft_lambda_layer.aws_lambda_layer_version.layer_version,
│   on .terraform/modules/aft/modules/aft-lambda-layer/main.tf line 24, in resource "aws_lambda_layer_version" "layer_version":
│   24: resource "aws_lambda_layer_version" "layer_version" {
│ 
╵
```

**Comment by witchbutter** [comment]
All of the issues I had getting started with this were related to regions and accounts.  The module code will not complete a `terraform apply` if the `ct_home_region` and `tf_backend_secondary_region` are the same.  It will also not complete if the `tf_backend_secondary_region` doesn't match the default region of the AFT management account, and for me would not complete using an AFT management account I created and moved under the AFT OU in AWS organizations.  It would only accept an account created using the wizard in Control Tower > Account Factory.

**Comment by gorank-crayon** [comment]
Hi @witchbutter did you manage to deploy the module? I m getting the same error even though my AFT management account is created within CT and the regions are set up correctly.

**Comment by sfharman** [comment]
> Hi @witchbutter did you manage to deploy the module? I m getting the same error even though my AFT management account is created within CT and the regions are set up correctly.

Same.  Fails at the same point with the same error several times after triple-checking my region entries.

**Comment by witchbutter** [comment]
Mine is definitely working.  Maybe you are getting new errors?

**Comment by sfharman** [comment]
Maybe?  I'm using us-east-2 as primary and us-east-1 as secondary.  I'll try again and reverse my setup to see if there is a bug.

Just noticed you said _"It will also not complete if the tf_backend_secondary_region doesn't match the default region of the AFT management account"._  I gotta go back to the drawing board and wrap my head around why that is because my AFT components are all in OH as well.
