### ISSUE TITLE
Accept Community Contributions

### ISSUE THREAD

**Issue by owenfarrell** [aws-ia/terraform-aws-control_tower_account_factory#157]
**Describe the outcome you'd like**

As a developer, I want to submit contributions to the AFT source code so that the bugs and enhancements requested by others are generally available more quickly.

**Is your feature request related to a problem you are currently experiencing? If so, please describe.**

Yes - bugs like #141 and enhancements like #152 are meaningful. And I think I have an idea on how to solve them.

**Additional context**

Help us help you.

**Comment by snebhu3** [comment]
@owenfarrell thank you for reaching out.
Unfortunately, we do not plan to take in contributions at this time and in the near future.
However, please feel free to submit a feature request or a bug report which we review regularly.
