### ISSUE TITLE
Migration of AFT framework from Terraform OSS to TFC

### ISSUE THREAD

**Issue by ArshikDhar** [aws-ia/terraform-aws-control_tower_account_factory#158]
We deployed AFT with Terraform OSS a few months ago and created many accounts & corresponding resources using that framework. Now we are planning to migrate to Terraform cloud so that state management can be done via TFC workspaces instead of s3 buckets.

So I'm wondering if there are some general guidelines or notes available with the list of prerequisites or points to remember while migrating the existing AFT framework deployed with Terraform OSS to Terraform cloud with minimal impact on the deployed resources? The README.md file in this repo illustrates the process of deploying AFT with TFC but nothing related to the migration I'm looking for.

We don't want to make any impact or changes to the created accounts or provisioned resources, just wanted to migrate from OSS to TFC.

**Comment by balltrev** [comment]
I do not believe AFT is unique here as far as a Terraform migration is concerned, I would recommend you reach out to Hashicorp for more information.
