### ISSUE TITLE
Archive File error

### ISSUE THREAD

**Issue by swankymonk** [aws-ia/terraform-aws-control_tower_account_factory#16]
Hi Team,

We are continuously getting this error:
terraform plan
╷
│ Error: error archiving directory: error encountered during file walk: CreateFile ..\aft-codecommit-solution\aft-deployment-new\modules\aing-framework\lambda\aft-account-provisioning-framework-validate-request\schema\request_schema.json: The system cannot find the path speci
│
│   with module.aft.module.aft_account_provisioning_framework.data.archive_file.validate_request,
│   on ..\aft-codecommit-solution\aft-deployment-new\modules\aft-account-provisioning-framework\lambda.tf line 4, in data "archive_file" "
╵
╷
│ Error: error archiving directory: error encountered during file walk: CreateFile ..\aft-codecommit-solution\aft-deployment-new\modules\aft-account-provisioning-framework\lambda\aft-account-provisioning-framework-create-role\iam\trust-policies\aftmanagement.tpl: The system cannot find the path specified.
│
│   with module.aft.module.aft_account_provisioning_framework.data.archive_file.create_role,
│   on ..\aft-codecommit-solution\aft-deployment-new\modules\aft-account-provisioning-framework\lambda.tf line 64, in data "archive_file" 
"create_role":
│   64: data "archive_file" "create_role" {
│

**Comment by balltrev** [comment]
My suspicion is the way the module is being sourced is causing this issue. Do you mind sharing how you're sourcing our module?

**Comment by swankymonk** [comment]
Hi,

Thanks for reviewing. Its resolved after souricig the module in correct way.

**Comment by ArshikDhar** [comment]
> Hi,
> 
> Thanks for reviewing. Its resolved after souricig the module in correct way.

How did it got resolved?
