### ISSUE TITLE
account_tags change value not replaced on existing account

### ISSUE THREAD

**Issue by Menahem1** [aws-ia/terraform-aws-control_tower_account_factory#160]
**AFT Version:** 1.3.7

**Bug Description**
Editing one existing tag key on account_tags is not replaced we have 2 versions

**To Reproduce**
1. Go to one existing/provisionned account on AFT with account_tags and with existing value on the tag key, for example tag **key** "_example_"
2. you want to edit the name of the key to "_new_example_"
3. After the modification by the step function you will have on AWS Organizations on the tag account the 2 tags "example" and "new_example" the replacement was not made

**Expected behavior**
replacement is done

**Comment by adam-daily** [comment]
Hey Ménahem, thanks for letting us know about this issue. I've created an item in our bug backlog; we'll have a look at this.

**Comment by pmmalinov01** [comment]
We are hitting the same issue. Was wonder is there any progress on this? Or should we look into doing a custom check between AWS Org and the dynamodb with the account details.

**Comment by georgik-flutter** [comment]
Same issue.
My problem is that removed tags are not deleted, only values are updated.
Changed tags are just the old ones removed and the new ones created.

**Comment by hanafya** [comment]
At this time we have decided to not prioritize this change because changing this behavior to be PUT would negatively impact customers who put tags on their accounts outside of AFT. If additional information arises that would not compromise this behavior, we will revisit
