### ISSUE TITLE
Creating multiple accounts fails - only first account is created

### ISSUE THREAD

**Issue by mbuotidem** [aws-ia/terraform-aws-control_tower_account_factory#161]
**Bug Description**
I tried to vent 3 accounts at the same time by including their information in one .tf file. Unfortunately, only the first account has been vended. The other two have been added to the aft-request table in DynamoDB but no pipelines have been created for them. 

**To Reproduce**
1. Use the account request repository to vend multiple accounts by placing three account module declarations in the same file 
2. Push to main and pipeline should start automatically
3. All pipelines will run successfully but only one account will be vended
4. No error will be presented

**Expected behavior**
I was under the impression that AFT would handle the queuing on my behalf and vend all accounts. 

**Related Logs**
Unfortunately, there are no errors anywhere, or at least, I'm not sure where to look for them. Everything says SUCCEEDED. 

**Additional context**
I made a commit to change a tag in one of the yet to be vended accounts hoping that would trigger its creation. It didn't. The pipeline runs again, updates the tag in DynamoDB but doesn't initiate the account creation process.

**Comment by adam-daily** [comment]
Hey Isaac, thanks for the info. A few questions for you:

1. Did the accounts that didn't get vended show up in the SQS queue successfully? Were they removed from the queue?
2. You should be able to find errors in the CloudWatch Logs that correspond to the account request processor and action trigger Lambdas. Do you see any failures reported there?
3. Which version of AFT are you on? The latest version of AFT reports errors in those Lambdas to the `aft-failure-notifications` topic.

**Comment by mbuotidem** [comment]
Hi Adam. 
1. On the first try, I don't think they did. As I explain below, I tried again a couple of times and those ones did end up on the queue and then on the dlq.  
2. There were no errors, just a success report. 
```
{
    "time_stamp": "2022-05-18 19:04:39,621",
    "log_level": "INFO",
    "log_message": {
        "RecordDetail": {
            "RecordId": "rec-SANITIZED",
            "ProvisionedProductName": "Stage",
            "Status": "CREATED",
            "CreatedTime": "2022-05-18T19:04:38.382000+00:00",
            "UpdatedTime": "2022-05-18T19:04:38.382000+00:00",
            "ProvisionedProductType": "CONTROL_TOWER_ACCOUNT",
            "RecordType": "PROVISION_PRODUCT",
            "ProvisionedProductId": "pp-SANITIZED",
            "ProductId": "prod-SANITIZED",
            "ProvisioningArtifactId": "pa-SANITIZED",
            "PathId": "lpv2-SANITIZED",
            "RecordErrors": [],
            "RecordTags": []
        },
        "ResponseMetadata": {
            "RequestId": "4ab32550-SANITIZED-af510247ab2d",
            "HTTPStatusCode": 200,
            "HTTPHeaders": {
                "x-amzn-requestid": "4ab32550-SANITIZED-af510247ab2d",
                "content-type": "application/x-amz-json-1.1",
                "content-length": "426",
                "date": "Wed, 18 May 2022 19:04:39 GMT"
            },
            "RetryAttempts": 0
        }
    }
}

```
However, under Contol Tower>Activities I can see that it failed with this log response: 

```
{
    "eventVersion": "1.08",
    "userIdentity": {
        "accountId": "ACCOUNT-ID",
        "invokedBy": "AWS Internal"
    },
    "eventTime": "2022-05-18T19:06:12Z",
    "eventSource": "controltower.amazonaws.com",
    "eventName": "CreateManagedAccount",
    "awsRegion": "us-east-1",
    "sourceIPAddress": "AWS Internal",
    "userAgent": "AWS Internal",
    "requestParameters": null,
    "responseElements": null,
    "eventID": "64ebf90d-SANITIZED-d7d37293edc5",
    "readOnly": false,
    "eventType": "AwsServiceEvent",
    "managementEvent": true,
    "recipientAccountId": "ACCOUNT-ID",
    "serviceEventDetails": {
        "createManagedAccountStatus": {
            "organizationalUnit": {
                "organizationalUnitName": "OU-NAME",
                "organizationalUnitId": "Not Available"
            },
            "account": {
                "accountName": "Stage",
                "accountId": "Not Available"
            },
            "state": "FAILED",
            "message": "AWS Control Tower failed to create an enrolled account.",
            "requestedTimestamp": "2022-05-18T19:04:39+0000",
            "completedTimestamp": "2022-05-18T19:06:12+0000"
        }
    },
    "eventCategory": "Management"
}
```
However, as I mentioned, I went ahead to try again which involved deleting the entries from account-request and account-request-metadata tables and triggering another commit. This second attempt ended up on the dlq and also  resulted in the error : 

```
{
    "time_stamp": "2022-05-18 20:14:39,363",
    "log_level": "ERROR",
    "log_message": {
        "FILE": "aft_account_request_processor.py",
        "METHOD": "lambda_handler",
        "EXCEPTION": "An error occurred (InvalidParametersException) when calling the ProvisionProduct operation: A stack named Stage already exists."
    }
}
Traceback (most recent call last):
  File "/var/task/aft_account_request_processor.py", line 52, in lambda_handler
    response = create_new_account(
  File "/opt/python/lib/python3.8/site-packages/aft_common/account_request_framework.py", line 277, in create_new_account
    response = client.provision_product(
  File "/opt/python/lib/python3.8/site-packages/botocore/client.py", line 415, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/python/lib/python3.8/site-packages/botocore/client.py", line 745, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidParametersException: An error occurred (InvalidParametersException) when calling the ProvisionProduct operation: A stack named Stage already exists.
```
3. I am on the latest version, 1.3.7 so I have now signed up to the `aft-failure-notifications` topic. 


My suspicion now is that I am running into AWS Organization Limits. I have put in a service limit increase request. However, I am not sure how to get rid of the stacks that are in limbo before I try again when my limit is increased. How do I delete these stacks from service catalog so I don't run into the `InvalidParametersException` error?

**Comment by mbuotidem** [comment]
Closing as I found where to remove the failed stack and was able to provision the account after my limit was raised. In case someone experiences this in the future, go to the Service Catalog in the Control Tower Management Account. Make sure to change the Access Filter to Account and you should see both the successfully provisioned items and the ones stuck in an error stage.

![image](https://user-images.githubusercontent.com/4692052/169517680-91c2d73f-783e-44f8-8126-8e9e66dd2795.png)

**Comment by ZeroDeth** [comment]
@mbuotidem Very useful. Thank you for sharing
