### ISSUE TITLE
core account customization

### ISSUE THREAD

**Issue by anonymously11505** [aws-ia/terraform-aws-control_tower_account_factory#167]
Is it possible to customize core accounts like audit and log archive using this aft module?

**Comment by anonymously11505** [comment]
duplicate

**Comment by balltrev** [comment]
Hey @anonymously11505, our [1.4.0](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/releases/tag/1.4.0) release should enable management of these accounts for you
