### ISSUE TITLE
Using `custom_fields` values in account customisations

### ISSUE THREAD

**Issue by word** [aws-ia/terraform-aws-control_tower_account_factory#17]
I would like to use values from`custom_fields` to pass parameters to terraform in account customisations.  Could you please provide an example of how to access those values in account customisations?

I tried digging those out of dynamodb `aft-request` table in `api_helpers/pre-api-helpers.sh` but codebuild assumes a role to the target account before that's executed so it doesn't work.

**Comment by word** [comment]
I was able to get the custom field value with a bit of role switching in `pre-api-helpers.sh` and write it to parameter store in the target account where it's accessible to terraform:

```
echo "Executing Pre-API Helpers"

# Switch role to aft mgmt account
./aws-aft-core-framework/sources/scripts/creds.sh --aft-mgmt

# Dig out custom field data from dynamodb
ACCOUNT_EMAIL=$(aws dynamodb get-item --table-name aft-request-metadata --key "{\"id\": {\"S\": \"$VENDED_ACCOUNT_ID\"}}" --attributes-to-get "email" --output json \
    | jq --raw-output ".Item.email.S")
VPC_CIDR=$(aws dynamodb get-item --table-name aft-request --key "{\"id\": {\"S\": \"$ACCOUNT_EMAIL\"}}" --attributes-to-get "custom_fields" --output json \
    | jq --raw-output ".Item.custom_fields.S" | jq --raw-output ".vpc_cidr")

echo "VPC_CIDR=${VPC_CIDR}"

# Switch role to target account
./aws-aft-core-framework/sources/scripts/creds.sh --account-id $VENDED_ACCOUNT_ID

# Write field value to parameter store in target account
aws ssm put-parameter --name "/aft/custom_fields/vpc_cidr" --type "String" --value $VPC_CIDR
```

It's quite a lot of faff though.  Is there a better way to do this that I'm missing?

**Comment by word** [comment]
The above example also required adding a read permission to the `aft-request` table to `aft-codebuild-customizations-role`

**Comment by balltrev** [comment]
Hey thanks for detailing this, we've opened a backlog item and are tracking this feature request.
