### ISSUE TITLE
Feature Flag Pre- and Post- API helpers to speed up customizations pipeline when they are not used

### ISSUE THREAD

**Issue by ephenix-trellix** [aws-ia/terraform-aws-control_tower_account_factory#171]
**Describe the outcome you'd like**

Feature flags which remove the pre- and post- api helpers actions from the account customization pipeline.

**Additional context**

Coded: https://github.com/ephenix/terraform-aws-control_tower_account_factory/tree/feature/disable-api-hooks

Saves 10-15 minutes from the Account Customization pipeline run time.

**Comment by balltrev** [comment]
Thanks for the call out here @ephenix-trellix. I believe this is a duplicate of https://github.com/aws-ia/terraform-aws-control_tower_account_factory/issues/87

We've already got a backlog to improve this experience, but I'll add the extra context you've provided.

**Comment by stumins** [comment]
Hey @ephenix-trellix,

As of [1.5.0](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/releases/tag/1.5.0), the customizations pipelines now share a single CodeBuild container for all of the pre-api-helpers / apply-terraform / post-api-helpers stages. This significantly reduces the time spent when pre/post helpers are not defined.

I'm going to close this issue as I believe 1.5.0 meets the spirit of the request - please feel free to open new issues as required.
