### ISSUE TITLE
Remove email case sensitive of Control Tower shared accounts

### ISSUE THREAD

**Issue by fjromerom** [aws-ia/terraform-aws-control_tower_account_factory#172]
**AFT Version:**
1.4.0

**Bug Description**
The version 1.4.0 introduced the ability to manage Audit, Logarchive and Management. I've run recently into an issue where AFT was unable to manage the Audit account because the email did not exactly match.

We already run into this issue in the past here https://github.com/aws-ia/terraform-aws-control_tower_account_factory/issues/90. I've looked into the current code and in fact it checks the email address matches with the same case.

https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/6005cfe765ca05241ec20a1392c119baa6883e76/sources/aft-lambda-layer/aft_common/shared_account.py#L59

**To Reproduce**
Onboard a shared account using an email address with at least 1 letter with different case.

**Expected behavior**
Since an email address is unique no matter the case used, AFT should not ensure strong case matching.

Thanks,
Francisco

**Comment by balltrev** [comment]
Thanks for bringing this up @fjromerom, I'll go ahead and bring this up with the team

**Comment by stumins** [comment]
Hi @fjromerom,

[AFT 1.8.0](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/releases/tag/1.8.0) resolves this issue. Thanks for the report!
