### ISSUE TITLE
IAM Eventual Consistency Issue: AWSAFTService Role Access Denied on First Execution

### ISSUE THREAD

**Issue by balltrev** [aws-ia/terraform-aws-control_tower_account_factory#177]
### Bug

AWSAFTService Role is now leveraged in all shared/member accounts. The role is created, and a managed policy is applied, but the role is used before IAM eventual consistency has propagated permissions.

This causes a race condition during subsequent actions, where the role is used, but does not have the required permissions to operate successfully, this commonly appears as:
```
[ERROR] ClientError: An error occurred (AccessDeniedException) when calling the GetParametersByPath operation
```

### Workaround
As this is an eventual consistency issue, retrying the StepFunction execution will typically resolve the failed execution as the permissions will likely have propagated.

**Comment by balltrev** [comment]
Related: 
* https://github.com/aws-ia/terraform-aws-control_tower_account_factory/issues/174
* https://github.com/aws-ia/terraform-aws-control_tower_account_factory/issues/173

**Comment by stumins** [comment]
Another related report: https://github.com/aws-ia/terraform-aws-control_tower_account_factory/issues/180

**Comment by snebhu3** [comment]
AFT Release [1.4.2](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/releases/tag/1.4.2) resolves this IAM eventual consistency issue
