### ISSUE TITLE
Error: Lambda function (aft-lambda-layer-codebuild-invoker) 

### ISSUE THREAD

**Issue by Nirmal-JLL** [aws-ia/terraform-aws-control_tower_account_factory#179]
**Bug Description**
Error: Lambda function (aft-lambda-layer-codebuild-invoker) returned error: ({"errorMessage": "An error occurred (AccountLimitExceededException) when calling the StartBuild operation: Cannot have more than 0 builds in queue for the account", "errorType": "AccountLimitExceededException", "stackTrace": ["  File \"/var/task/codebuild_invoker.py\", line 28, in lambda_handler\n    job_id = client.start_build(projectName=codebuild_project_name)[\"build\"][\"id\"]\n", "  File \"/var/runtime/botocore/client.py\", line 391, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n", "  File \"/var/runtime/botocore/client.py\", line 719, in _make_api_call\n    raise error_class(parsed_response, operation_name)\n"]})
│ 
│   with module.aft_pipeline.module.aft_lambda_layer.data.aws_lambda_invocation.invoke_codebuild_job,
│   on .terraform/modules/aft_pipeline/modules/aft-lambda-layer/lambda.tf line 21, in data "aws_lambda_invocation" "invoke_codebuild_job":
│   21: data "aws_lambda_invocation" "invoke_codebuild_job" {

**Comment by thapakazi** [comment]
What service usage limit does it relates to, what should I ask AWS about ?

**Comment by thapakazi** [comment]
a moment later...

I found out this block is causing this issue:
https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/f8a3a30627f1dfe228dda7db6d64e72957cecece/modules/aft-lambda-layer/lambda.tf#L21-L29

and

looks like my account has concurrent execution for lambda set to 10, I am increasing it to 200.



![image](https://user-images.githubusercontent.com/1695906/203487440-bd5af8ae-588b-4830-bdbe-bc98404d62e4.png)

and till AWS increase my quota, I am commenting these out and continue with my testing 😅

**Comment by thapakazi** [comment]
Found out from support guy on aws, 
for new accounts even though concurrent build on codebuild is set to 60,
 i**t is not active at beginning**
 
 so had to hop on chat to get it active. All good now.
