### ISSUE TITLE
Unable to Provision new accounts by Account Request.

### ISSUE THREAD

**Issue by AdityaDongare** [aws-ia/terraform-aws-control_tower_account_factory#181]
Hi , 
I am trying to provision new accounts under CT . The only things happening yet is that the table entry is created in the account-request table.
After checking for lambda logs in Cloudwatch, I can see that the request is created (sqs message has been retrieved ofcourse)

![image](https://user-images.githubusercontent.com/90835190/171621441-79a528af-4c2f-4f39-8eb6-5bd02f294d0d.png)

But still account does not get created, even if it shows status as created.

I have tried multiple time with unique account names and email address too.

P.S. (I have been able to provision one account in similar way previously with no errors).

**Comment by stumins** [comment]
Hi @AdityaDongare, can you check a few things and provide some additional information?

- Do you have any provisioned products in error states in Service Catalog in your CT Management Account?
- Are there any messages in the `aft-account-request-dlq.fifo` SQS queue?

You may also consider subscribing to the `aft-failure-notifications` SNS topic to assist with troubleshooting

**Comment by AdityaDongare** [comment]
Finally got the reason for the issue. My organization already had 10 accounts, hence could not provision new account as the default limit is 10 accounts in organization.
