### ISSUE TITLE
Lambda Function (aft-account-request-action-trigger) Fails On Invocation

### ISSUE THREAD

**Issue by siddharthmishra01** [aws-ia/terraform-aws-control_tower_account_factory#188]
**Terraform Version & Prov:**
Terraform Version - 1.2.1

**AFT Version:**
AFT Version -  1.4.2

**Terraform Version & Provider Versions**

`terraform version`
```
Terraform v1.2.1
on windows_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v4.18.0
+ provider registry.terraform.io/hashicorp/local v2.2.3
+ provider registry.terraform.io/hashicorp/random v3.3.1
+ provider registry.terraform.io/hashicorp/time v0.7.2```

`terraform providers`
```
Providers required by configuration:
.
└── module.aft
    ├── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0, < 5.0.0
    ├── provider[registry.terraform.io/hashicorp/local]
    ├── module.aft_ssm_parameters
    │   └── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
    ├── module.aft_customizations
    │   ├── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
    │   └── provider[registry.terraform.io/hashicorp/local]
    ├── module.aft_iam_roles
    │   ├── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
    │   ├── module.audit_exec_role
    │       └── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
    │   ├── module.audit_service_role
    │       └── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
    │   ├── module.ct_management_exec_role
    │       └── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
    │   ├── module.ct_management_service_role
    │       └── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
    │   ├── module.log_archive_exec_role
    │       └── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
    │   ├── module.log_archive_service_role
    │       └── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
    │   ├── module.aft_exec_role
    │       └── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
    │   └── module.aft_service_role
    │       └── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
    ├── module.aft_lambda_layer
    │   ├── provider[registry.terraform.io/hashicorp/local]
    │   ├── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
    │   └── provider[registry.terraform.io/hashicorp/random]
    ├── module.aft_account_request_framework
    │   ├── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
    │   └── provider[registry.terraform.io/hashicorp/time]
    ├── module.aft_feature_options
    │   └── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
    ├── module.aft_code_repositories
    │   ├── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
    │   └── provider[registry.terraform.io/hashicorp/local]
    ├── module.aft_backend
    │   └── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
    ├── module.packaging
    │   └── provider[registry.terraform.io/hashicorp/archive]
    └── module.aft_account_provisioning_framework
        └── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0

Providers required by state:

    provider[registry.terraform.io/hashicorp/aws]

    provider[registry.terraform.io/hashicorp/archive]

    provider[registry.terraform.io/hashicorp/random]

    provider[registry.terraform.io/hashicorp/time]

    provider[registry.terraform.io/hashicorp/local]
```

**Bug Description**
Issue occured after successful deployment of AFT module. When we ran **ct-aft-account-request** codepipeline, it successfully made entry into the **aft-request** dynamodb table. which made trigger to **aft-account-request-action-trigger** lambda function which eventually failed.

![image](https://user-images.githubusercontent.com/13079722/173377361-d19a38d4-cddf-4b21-b728-fab6e3395797.png)

The lambda invocation error logs are following -

`[ERROR] InvalidParametersException: An error occurred (InvalidParametersException) when calling the GetProvisionedProductOutputs operation: Last Successful Provisioning Record doesn't exist.
Traceback (most recent call last):
  File "/var/task/aft_account_request_action_trigger.py", line 65, in lambda_handler
    new_account = not provisioned_product_exists(event_record)
  File "/opt/python/lib/python3.8/site-packages/aft_common/account_request_framework.py", line 109, in provisioned_product_exists
    if email_exists_in_batch(account_email, pp_ids, ct_management_session):
  File "/opt/python/lib/python3.8/site-packages/aft_common/account_request_framework.py", line 126, in email_exists_in_batch
    pp_email = sc_client.get_provisioned_product_outputs(
  File "/opt/python/lib/python3.8/site-packages/botocore/client.py", line 415, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/python/lib/python3.8/site-packages/botocore/client.py", line 745, in _make_api_call
    raise error_class(parsed_response, operation_name)`


**To Reproduce**
Steps to reproduce the behavior:
1. Successfully deploy AFT module
2. Enable codestar connection
3. Grant AFT access to Service Catalog portfolio
4. Rerun account provisioning pipeline (ct-aft-account-provisioning-customizations) successfully
5. update your **learn-terraform-aft-account-request** github fork with relevant details
6. **ct-aft-account-request** codepipeline runs successfully
7. **aft-request** dynamodb table gets the account entry
8.  But **aft-account-request-action-trigger** lambda fails with above logs

**Expected behavior**
New AWS Account gets created after flow completion.

**Related Logs**
See Above

Thank You !

**Comment by siddharthmishra01** [comment]
Hi @balltrev, 
Thanks for the help. Removing tainted and Errored provisioned products from ServiceCatalog worked for me.

**Comment by kkadiyam** [comment]
Hello @siddharthmishra01  and @balltrev, Quick question on deleting the tainted resources, I am facing same error while creating new AWS account.

Does deleting the tainted resource provisioned products from service catalog deleted the AWS Account ?, For example i have below entry in my service catalog which is tainted.

Enroll-Account-581344051234

Does deleting Enroll-Account-581344051234 this product from service catalog deleted the actual AWS account by any chance ?

Thanks!
