### ISSUE TITLE
creating multiple accounts :  stack named production-aft already exists

### ISSUE THREAD

**Issue by MohamedAnouar** [aws-ia/terraform-aws-control_tower_account_factory#19]
Hello, when I tried creating multiple accounts at once. I got only one account created and for the rest of the accounts I got the following error from /aws/lambda/aft-account-request-processor :  

{
    "time_stamp": "2021-12-27 15:27:18,181",
    "log_level": "ERROR",
    "log_message": {
        "FILE": "lambda_function.py",
        "METHOD": "create_new_account",
        "EXCEPTION": "An error occurred (InvalidParametersException) when calling the ProvisionProduct operation: A stack named production-aft already exists."
    }
}

I also couldn't find the stack that is causing the error so I can delete it. How can I proceed to resolve this error? should I delete some stacks in aws catalog from the aft management account ? 

Thank you in advance,

**Comment by balltrev** [comment]
Can you confirm that the account names in the account request repository are unique?

**Comment by balltrev** [comment]
Feel free to reopen this if you've got any more info for us, in the mean time I'm gonna go ahead and close this issue.

**Comment by julrich-cdw** [comment]
I am having a same issue
