### ISSUE TITLE
S3 buckets: make public access block configuration consistent

### ISSUE THREAD

**Issue by theipster** [aws-ia/terraform-aws-control_tower_account_factory#190]
**Describe the outcome you'd like**

The arguments `ignore_public_acls` and `restrict_public_buckets` should be consistently set to `true` for all `aws_s3_bucket_public_access_block` resources.

Notably, they are currently set to `true` for:

- `aft_logging_bucket` ([here](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/1.4.2/modules/aft-feature-options/s3.tf#L68-L69)); and,
- `aft_access_logs` ([here](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/1.4.2/modules/aft-feature-options/s3.tf#L125-L126)),

but currently unset for:

- `primary-backend-bucket` ([here](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/1.4.2/modules/aft-backend/main.tf#L78)); and,
- `secondary-backend-bucket` ([here](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/1.4.2/modules/aft-backend/main.tf#L123)).

**Is your feature request related to a problem you are currently experiencing? If so, please describe.**

This becomes apparent when AWS Config is configured to auto-remediate against the `s3-bucket-public-read-prohibited` and `s3-bucket-public-write-prohibited` rules.

(These two rules are included in the [Operational Best Practices for NCSC Cloud Security Principles](https://docs.aws.amazon.com/config/latest/developerguide/operational-best-practices-for-ncsc.html) conformance pack, as well as [many](https://github.com/awslabs/aws-config-rules/search?q=s3-bucket-public-read-prohibited) [others](https://github.com/awslabs/aws-config-rules/search?q=s3-bucket-public-write-prohibited)).

Remediation using the [`AWS-DisableS3BucketPublicReadWrite`](https://docs.aws.amazon.com/systems-manager-automation-runbooks/latest/userguide/automation-aws-disables3bucketpublicreadwrite.html) runbook (for example, as recommended by this [blog post](https://aws.amazon.com/blogs/mt/aws-config-auto-remediation-s3-compliance/)) means that the bucket will drift from the Terraform state.

**Additional context**

N/A

**Comment by rikturnbull** [comment]
There are other AWS Foundational Security Best Practices for S3 that cause SecurityHub alerts for many AFT S3 Buckets. These are:

[S3.5] S3 buckets should require requests to use Secure Socket Layer
[S3.8] S3 Block Public Access setting should be enabled at the bucket level
[S3.9] S3 bucket server access logging should be enabled
[S3.10] S3 buckets with versioning enabled should have lifecycle policies configured
[S3.11] S3 buckets should have event notifications enabled
[S3.13] S3 buckets should have lifecycle policies configured

This causes compliance issues with AFT.

**Comment by stumins** [comment]
Hi @theipster,

[AFT 1.8.0](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/releases/tag/1.8.0) now sets consistent S3 Block Public Access settings for the AFT buckets. Thanks again for the callout!

@rikturnbull 

Thank you for providing these details - I've copied your comment into a dedicated enhancement request. Please use https://github.com/aws-ia/terraform-aws-control_tower_account_factory/issues/300 for issue tracking.
