### ISSUE TITLE
Pipeline not triggering new account after upgrade from v1.3.7 to 1.4.2

### ISSUE THREAD

**Issue by ZeroDeth** [aws-ia/terraform-aws-control_tower_account_factory#193]
**Terraform Version & Prov:**

**AFT Version:**
(Can be found in the AFT Management Account in the SSM Parameter `/aft/config/aft/version`)

```
1.4.2
```

**Terraform Version & Provider Versions**
Please provide the outputs of `terraform version` and `terraform providers` from within your AFT environment
1.1.9
`terraform version`
```
1.1.9
```

`terraform providers`
```
1.0.0
```

**Bug Description**

An issue with AFT creation pipeline in CodePipeline: 

- Upgraded AFT from v1.3.7 to 1.4.2 (No issues)
- Added new DEV account (same steps of account-request, account-customizations, etc)
  - Under DDB account exist
  - Cloudwatch (no errors)
  - CodePipeline didn't trigger DEV account
    - Click release change to all accounts that exist previously (all working fine) 
  - Management account showing DEV ENROLLED even I got the ID

We are using Terraform Cloud and also no creation for `<dev-account-id>-account-customization` & `<dev-account-id>-global-customization`, Other accounts exist and provision well. 

**Expected behavior**

expect found dev account exist under codepipeline, similar to test & staging that's already provisioned with v1.3.7

![CleanShot 2022-06-19 at 18 40 26@2x](https://user-images.githubusercontent.com/10928577/174493670-a8c9423a-3dee-41ce-a839-eb8a99129bb9.png)

**Related Logs**
Provide any related logs or error messages to help explain your problem.

Cannot find a relative error in cloudwatch 

**Additional context**

TFC for existing accounts and DEV not one of them 
![CleanShot 2022-06-19 at 18 46 11](https://user-images.githubusercontent.com/10928577/174493860-f1c8a71c-8be1-4a6e-b115-19b4ebcb6b7f.png)

dev-aft-01 under AWS CT 
![CleanShot 2022-06-19 at 18 51 32@2x](https://user-images.githubusercontent.com/10928577/174494018-91ad451b-8d8a-4cde-89da-140e7e21fcf2.png)

**Comment by ZeroDeth** [comment]
Main issue: **Service Catalog > provisioned products**, however, tried to Re-register account's OU, Create another OU, and move to another OU to re-register again; Errors & Tainted still exist, even tried update landing zone version from `2.8 to 2.9`. 
tested mostly on solutions that exist under AWS troubleshooting. 
So, Accounts managed by AFT should be with `AWSAFTExecution`, and non-managed using `AWSReservedSSO_AWSAdministratorAccess_5a0eb7439c8e0b2a`? Do I need to move Enroll-Accounts to `AWSAFTExecution`?
![CleanShot 2022-06-20 at 08 17 39](https://user-images.githubusercontent.com/10928577/174546253-13022b73-e66b-4a82-b0ce-1cc2a24acd93.png)

**Comment by ZeroDeth** [comment]
@snebhu3 resolved all of them but still, Codepipline didn't trigger a new account.

**Comment by snebhu3** [comment]
@ZeroDeth I would suggest you to re-invoke the concerned account request. One way you could potentially do this is by adding a new custom field. 
Could you try that and check if the pipeline gets created for the concerned account?

**Comment by ZeroDeth** [comment]
@snebhu3 executed by account ID: 
```json
{
  "include": [
    {
      "type": "accounts",
      "target_value": [ 
        "1234567890" 
      ],
      "group": "Non-Prod"
    }
  ]
}
```
```json
{
    "time_stamp": "2022-06-21 12:50:09,966",
    "log_level": "ERROR",
    "log_message": {
        "FILE": "aft_customizations_execute_pipeline.py",
        "METHOD": "lambda_handler",
        "EXCEPTION": "Pipelines for account id 1234567890 was not found"
    }
}
Traceback (most recent call last):
  File "/var/task/aft_customizations_execute_pipeline.py", line 34, in lambda_handler
    execute_pipeline(session, str(p))
  File "/opt/python/lib/python3.8/site-packages/aft_common/customizations.py", line 79, in execute_pipeline
    name = get_pipeline_for_account(session, account)
  File "/opt/python/lib/python3.8/site-packages/aft_common/customizations.py", line 49, in get_pipeline_for_account
    raise Exception("Pipelines for account id " + account + " was not found")
Exception: Pipelines for account id 859649164905 was not found
```
```json
[ERROR] Exception: Pipelines for account id 1234567890 was not found
Traceback (most recent call last):
  File "/var/task/aft_customizations_execute_pipeline.py", line 34, in lambda_handler
    execute_pipeline(session, str(p))
  File "/opt/python/lib/python3.8/site-packages/aft_common/customizations.py", line 79, in execute_pipeline
    name = get_pipeline_for_account(session, account)
  File "/opt/python/lib/python3.8/site-packages/aft_common/customizations.py", line 49, in get_pipeline_for_account
    raise Exception("Pipelines for account id " + account + " was not found")
```

**Comment by ZeroDeth** [comment]
**aft-account-customization without sart execution** | I am still didn't figure; Why pipeline not created? 
![CleanShot 2022-06-21 at 14 09 55](https://user-images.githubusercontent.com/10928577/174807154-1fdccc10-4bff-45d4-b8ef-888590b91cd3.png)

```json
{
  "account_request": {
    "custom_fields": "{\"account_name\":\"dev-aft-01\",\"group\":\"Non-Prod\"}",
    "change_management_parameters": {
      "change_reason": "Provision a Development account",
      "change_requested_by": "DevOps"
    },
    "id": "xxxx@xxx.co.uk",
    "control_tower_parameters": {
      "AccountEmail": "xxx@xxx.co.uk",
      "SSOUserFirstName": "Development",
      "SSOUserLastName": "User",
      "ManagedOrganizationalUnit": "ENV (ou-50l1-a65xq5wv)",
      "AccountName": "dev-aft-01",
      "SSOUserEmail": "xxx@xxx.co.uk"
    },
    "account_tags": {
      "Environment": "Development",
      "Managed": "terraform",
      "OwnerContact": "xxx@xxx.co.uk",
      "RunModel": "247",
      "Team": "DevOps"
    },
    "account_customizations_name": "dev-aft-01"
  },
  "control_tower_event": {},
  "account_provisioning": {
    "run_create_pipeline": "false"
  },
  "validated": {
    "Success": true
  },
  "account_info": {
    "account": {
      "id": "1234567890",
      "email": "xxxx@xxx.co.uk",
      "name": "dev-aft-01",
      "joined_method": "CREATED",
      "joined_date": "2022-06-19 14:34:03.737000+00:00",
      "status": "ACTIVE",
      "parent_id": "ou-50l1-a65xq5wv",
      "parent_type": "ORGANIZATIONAL_UNIT",
      "type": "account",
      "vendor": "aws"
    }
  },
  "persist_metadata": {
    "StatusCode": 200
  },
  "role": {
    "Arn": null
  },
  "account_tags": {
    "StatusCode": 200
  },
  "account_metadata_ssm": {
    "StatusCode": 200
  }
}
```

**Comment by snebhu3** [comment]
@ZeroDeth with AFT v1.4.2, invoking customization via SF `aft-invoke-customizations` would not by default create a customization pipeline if it did not already exist. You would need to re-invoke an account request by making a change to your account request input in your main.tf as part of `aft-account-request` repository. For example, you could add a new custom field to the respective account request.

However, we just released [AFT v.1.50](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/releases), in which invoking customization via SF `aft-invoke-customizations` would create a customization pipeline if it does not already exist for the respective account.

I would recommend updating to [AFT v.1.50](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/releases) and then retrying invocation of customization via SF `aft-invoke-customizations`.

**Comment by ZeroDeth** [comment]
@snebhu3 Pipeline triggers after the upgrade and updates `custom_fields`
Thank you for your support and help. Have a lovely day!
