### ISSUE TITLE
Account customization stage fails when there is no customization set

### ISSUE THREAD

**Issue by fjromerom** [aws-ia/terraform-aws-control_tower_account_factory#195]
**AFT Version:**
1.5.0

**Bug Description**
Account customization stage fails when there is no customization defined for the account. CodeBuild fails trying to run api-helpers with the following error:

```
[Container] 2022/06/22 15:55:44 Running command $DEFAULT_PATH/api-helpers-venv/bin/pip install -r ./$CUSTOMIZATION/api_helpers/python/requirements.txt
--
ERROR: Could not open requirements file: [Errno 2] No such file or directory: './/api_helpers/python/requirements.txt'
```

Looking into the code introduced in this version, I've identified the root cause of the issue. The way how it validates a customization has been defined for an account it is defined in the next line:

https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/0e0c00df05b4edb4e8e93283b2e9eb01776fb533/modules/aft-customizations/buildspecs/aft-account-customizations-terraform.yml#L28

If a customization has not been defined for an account, the result will be the following:

```
$ ./build.sh
+++ pwd
++ DEFAULT_PATH=/home/ec2-user
++ CUSTOMIZATION=
++ [[ ! -d /home/ec2-user/ ]]
++ echo 'Found customization'
Found customization
```

As we can observe, since the default_path variable is defined the condition is met and therefore it thinks a customization has been defined. In the previous version the variable was not present and it worked as expected.

https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/eed6959b121e54e07e25d60c858c614a338960d1/modules/aft-customizations/buildspecs/aft-account-customizations-terraform.yml#L46

**To Reproduce**
1. Do not set account_customizations_name in account-request repository.
2. Run CodePipeline pipeline for the account.
3. Account customizations stage will fail.

**Expected behavior**
Account customizations stage should run even if there is no account customizations set for an account.

Thanks,
Francisco

**Comment by snebhu3** [comment]
@fjromerom thank you for reporting this. We are looking into the issue.

**Comment by fjromerom** [comment]
Awesome prompt response! I can confirm the version 1.5.1 fixes this bug :)
