### ISSUE TITLE
Customizing CT or AFT Management Accounts

### ISSUE THREAD

**Issue by jmstone617** [aws-ia/terraform-aws-control_tower_account_factory#20]
Is it possible to manage the Control Tower or AFT Management accounts in AFT? Those accounts are both created manually. If imported, would account customizations apply to those accounts as well?

**Comment by balltrev** [comment]
At this time we do not have a supported process to allow AFT to manage either the AFT management account or the Control Tower core accounts.

**Comment by jarrettj** [comment]
Hi, good day @balltrev.

Had success importing the Audit account. Is this still the case that we can't import the billing account though? Thanks.

Regards,
Jarrett
