### ISSUE TITLE
creds.sh does not generate credentials properly

### ISSUE THREAD

**Issue by igoze** [aws-ia/terraform-aws-control_tower_account_factory#209]
**Terraform Version & Prov:**

**AFT Version: 1.3.5 **
(Can be found in the AFT Management Account in the SSM Parameter `/aft/config/aft/version`)

**Terraform Version & Provider Versions**
Please provide the outputs of `terraform version` and `terraform providers` from within your AFT environment

`terraform version`
```
v0.15.5
```

`terraform providers`
```
provider[registry.terraform.io/hashicorp/aws] ~> 3.0
```

**Bug Description**
It seems that recent update to creds.sh seems to break role assumption (https://github.com/aws-ia/terraform-aws-control_tower_account_factory/commit/31692356f20908355a3cc2bf747597912fed18f9#diff-c3c98761e524d7915a591153d9d995dae135f9d0a0c6c0d541bce240992cfb27) in the mentioned commit AWS_PARTITION variable is added in --role-arn parameter of aws sts assume-role command instead of string "aws" that used to be added explicitly. However the value for this variable seems not to be provided anywhere. And pipeline files because of invalid role arn.

**To Reproduce**
1. Run account customization pipeline

**Expected behavior**
Credentials are generated , pipeline succeeds

**Related Logs**
[Container] 2022/07/18 11:53:11 Running command ./aws-aft-core-framework/sources/scripts/creds.sh --account-id $VENDED_ACCOUNT_ID
Generating credentials for AWSAFTAdmin in aft-management account: XXXXXXXXXX
An error occurred (ValidationError) when calling the AssumeRole operation: arn::iam::XXXXXXXXXX:role/AWSAFTAdmin is invalid
[Container] 2022/07/18 11:53:15 Command did not exit successfully ./aws-aft-core-framework/sources/scripts/creds.sh --account-id $VENDED_ACCOUNT_ID exit status 255

**Additional context**

**Comment by balltrev** [comment]
Hey @igoze, thanks for bringing this up. I believe this is due to a known bug with AFT versions 1.3.5 and older, there are workarounds are referenced within https://github.com/aws-ia/terraform-aws-control_tower_account_factory/issues/205

**Comment by stumins** [comment]
Hey @igoze, I'm going to close this issue due to lack of activity. Please feel free to open a new issue if the workarounds in https://github.com/aws-ia/terraform-aws-control_tower_account_factory/issues/205 do not resolve your issue.
