### ISSUE TITLE
Fail aft_account_provisioning_framework_account_metadata_ssm in version 1.5.2

### ISSUE THREAD

**Issue by fjromerom** [aws-ia/terraform-aws-control_tower_account_factory#210]
**AFT Version:**
1.5.2

**Bug Description**
After creating a new account with AFT the Step Function aft-account-provisioning-framework fails on step aft_account_provisioning_framework_account_metadata_ssm.

This seems to be due to the support for partitions introduced in the version 1.5.2.

**To Reproduce**
1. Create a new account with AFT
2. After the account is created the Step Function aft-account-provisioning-framework fails

**Expected behavior**
Step Function should complete successfully

**Related Logs**
Below aft_account_provisioning_framework_account_metadata_ssm CloudWatch log with the errors:

```
{
    "time_stamp": "2022-07-21 12:51:46,477",
    "log_level": "ERROR",
    "log_message": {
        "FILE": "aft_account_provisioning_framework_account_metadata_ssm.py",
        "METHOD": "lambda_handler",
        "EXCEPTION": "module 'aft_common.aft_utils' has no attribute 'get_aws_partition'"
    }
}
Traceback (most recent call last):
  File "/var/task/aft_account_provisioning_framework_account_metadata_ssm.py", line 49, in lambda_handler
    "Resource": f"arn:{utils.get_aws_partition(session)}:ssm:{target_region}:{target_account_id}:parameter{SSM_PARAMETER_PATH}*",
AttributeError: module 'aft_common.aft_utils' has no attribute 'get_aws_partition'
```
```
[ERROR] AttributeError: module 'aft_common.aft_utils' has no attribute 'get_aws_partition'
Traceback (most recent call last):
  File "/var/task/aft_account_provisioning_framework_account_metadata_ssm.py", line 49, in lambda_handler
    "Resource": f"arn:{utils.get_aws_partition(session)}:ssm:{target_region}:{target_account_id}:parameter{SSM_PARAMETER_PATH}*",
```

Thanks,
Francisco

**Comment by brhankel** [comment]
The Lambda layer is built while AFT is being deployed or updated and this is where your failure is occurring. Suggest doing another apply on AFT version 1.5.2 (basically a re-deploy) and see if this corrects the issues. My install of 1.5.2 is not having the same issue which if the code was incorrect all installs would fail.

**Comment by fjromerom** [comment]
I had to rollback to the previous version and finish provisioning the account. I'll upgrade to the version 1.6.0 and I'll update the ticket if I encounter this issue again.

Thanks!
