### ISSUE TITLE
Suspected timing issue in aft_account_provisioning_framework_account_metadata_ssm task

### ISSUE THREAD

**Issue by terencewhitenz** [aws-ia/terraform-aws-control_tower_account_factory#211]
**Terraform Version & Prov:**

**AFT Version:**
1.4.0

**Terraform Version & Provider Versions**
Please provide the outputs of `terraform version` and `terraform providers` from within your AFT environment

`terraform version`
```
0.15.5
```

`terraform providers`
```
hashicorp/aws
```

**Bug Description**
Task aft_account_provisioning_framework_account_metadata_ssm in workflow aft-account-provisioning-framework fails with error message
```
An error occurred (AccessDeniedException) when calling the PutParameter operation: 
User: arn:aws:sts::(new account number):assumed-role/AWSAFTService/AWSAFT-Session is not authorized to perform: 
ssm:PutParameter on resource: arn:aws:ssm:ap-southeast-2:(new account number):parameter/aft/account-request/custom-fields/env_name 
because no identity-based policy allows the ssm:PutParameter action
```

The new account is created, the IAM role mentioned is created (step aft_account_provisioning_framework_create_role succeeded and I manually verified) and it has AdministratorAccess permissions. I suspect it was a timing issue as the lambda has a 60 second sleep in 
the logs (`Sleeping for 60s to ensure Role exists`) and I suspect it wasn't enough on this occassion.

Resubmitted new account creation file with minor change in audit fields, account creation completes and execution of workflow goes through fine.

**To Reproduce**
Cannot reproduce on demand, but steps done to create initial issue and investigate it
1. Submit usual new account request via file to repo
2. Wait and see new account created but no customisations added
3. Open Step Functions and look at Failed column, see aft-account-provisioning-framework has failed status
4. Open aft-account-provisioning-framework state machine and see Failed execution
5. Open failed execution and see step aft_account_provisioning_framework_account_metadata_ssm is failed with error message above

**Expected behavior**
1. Submit usual new account request via file to repo
2. Wait and see new account created and customisations added
3. Check state machines for AFT and see no failures

**Related Logs**

**Additional context**
Stack Trace
```
File \"/var/task/aft_account_provisioning_framework_account_metadata_ssm.py\", line 73, in lambda_handler\n    create_ssm_parameters(target_account_session, custom_fields)
File \"/opt/python/lib/python3.8/site-packages/aft_common/account_provisioning_framework.py\", line 227, in create_ssm_parameters\n    response = client.put_parameter(
File \"/opt/python/lib/python3.8/site-packages/botocore/client.py\", line 415, in _api_call\n    return self._make_api_call(operation_name, kwargs)
File \"/opt/python/lib/python3.8/site-packages/botocore/client.py\", line 745, in _make_api_call\n    raise error_class(parsed_response, operation_name)
```

**Comment by stumins** [comment]
Hey @terencewhitenz,

We added some improvements to how the IAM roles are created & used in 1.4.2 - are you able to upgrade your version and let us know if you see this issue again?

**Comment by stumins** [comment]
Hi @terencewhitenz ,

I'm going to close this issue due to inactivity. Please let us know if you experience this issue again after upgrading to the newest version of AFT.
