### ISSUE TITLE
AFT Account creation issue after name change & manual update

### ISSUE THREAD

**Issue by premjeet-sahu** [aws-ia/terraform-aws-control_tower_account_factory#212]
Hi Support Team,

I deployed AWS Control Tower Account Factory for Terraform (AFT) using the steps mentioned in official documentation https://docs.aws.amazon.com/controltower/latest/userguide/aft-getting-started.html and completed the post deployment steps. Then I created 3 accounts using the Terraform Code as follows. 

1) Shared services
2) Network services
3) SRT Services

Here is the block of code I used for creating the SRT Services account.

module "srt-account" {
  source = "./modules/aft-account-request"

  control_tower_parameters = {
    AccountEmail              = "aws.srt.se@xxxxx.com"
    AccountName               = "SRT Account - Q Environment"
    ManagedOrganizationalUnit = "Non Production"
    SSOUserEmail              = "aws.srt.se@xxxxx.com"
    SSOUserFirstName          = "SRT Account"
    SSOUserLastName           = "Admin"
  }

  account_tags = {
    "Owner" = "John Doe"
  }

  change_management_parameters = {
    change_requested_by = "John Doe"
    change_reason       = "SRT Services account"
  }

  custom_fields = {
    group = "Non Production"
  }

  account_customizations_name = "srt-services"
}

Later on I did some change to the AccountName in the TF code and the pipeline (ct-aft-account-request) executed successfully showing name change has been accepted but nothing happened. After that to examine further, I removed the entire code block for SRT Account and pushed the changes. 

The new changes were accepted by TF pipeline (ct-aft-account-request) but the account was not removed from Control Tower Management. So I removed it manually from the service catalog. Now when I'm trying to enrol the SRT account through TF, nothing is happening and any new account requests are not getting created through TF. 

It seems like there is a bug in AFT module where you are only allowed to create new accounts but any updates to existing accounts breaks the AFT functionality. 

Pls advice if I'm missing something here.

**Comment by v-rosa** [comment]
Renaming accounts using AFT is not currently supported. See https://github.com/aws-ia/terraform-aws-control_tower_account_factory/issues/129 and https://docs.aws.amazon.com/controltower/latest/userguide/taf-account-provisioning.html#aft-update-account

**Comment by stumins** [comment]
Hi @premjeet-sahu, as @v-rosa mentions the only supported update to the `control_tower_parameters` of an existing account is to [change the `ManagedOrganizationalUnit`.](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/main/sources/aft-lambda-layer/aft_common/account_request_framework.py#L249)

Making out-of-band changes to the underlying SC products can affect AFT's ability to operate on them due to a de-sync between the environment and the expected state. For AFT to re-ingest that account, you may need to delete that account's record from the `aft-request` DynamoDB table in the AFT Management account and re-try.

**Comment by stumins** [comment]
Closing this issue as I believe the question has been answered - please feel free to open new issues as required.
