### ISSUE TITLE
Make Invoke Concurrency configurable

### ISSUE THREAD

**Issue by jarrod-lowe** [aws-ia/terraform-aws-control_tower_account_factory#214]
**Describe the outcome you'd like**

The Invoke state machine will create 25 parrallel updates of accounts. This causes rate limit issues for me. I'd like to be able to set a module variable to set it to a lower number,

**Is your feature request related to a problem you are currently experiencing? If so, please describe.**

Running into API ratelimits in the aft-account-provisioning-framework state machine, due to running too many at once.

**Additional context**

**Comment by stumins** [comment]
Hi @jarrod-lowe, thanks for providing this feedback.

I've created a backlog ticket to address the rate limiting issues when re-invoking a large number of customizations through the step function.

**Comment by stumins** [comment]
Hi @jarrod-lowe,

[AFT 1.7.0 ](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/releases/tag/1.7.0) optimized the API calls made by the `aft-account-provisioning-framework` step function to reduce throttling errors that occurred when customizing a large number of accounts. 

Are you still any experiencing throttling issues when using AFT 1.7.0+?

**Comment by echoAlexey** [comment]
Yes, we do.

An error occurred (ThrottlingException) when calling the DescribeCases operation (reached max retries: 4): Throttle limit exceeded

**Comment by stumins** [comment]
Hi @jarrod-lowe & @echoAlexey,

We just released [AFT 1.10.4](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/releases/tag/1.10.4) with improved retry behavior to address these types of throttling issue. 

Please upgrade to 1.10.4 and let us know if you continue to experience any throttling exceptions.

**Comment by stumins** [comment]
We haven't received any reports of continued throttling, so I'm going to go close this issue as completed. Please feel free to open a new ticket if you continue to experience throttling issues on versions >= 1.10.4
