### ISSUE TITLE
How to import the AFT-Management or best practice to apply changes to it

### ISSUE THREAD

**Issue by dignajar** [aws-ia/terraform-aws-control_tower_account_factory#220]
**Describe the outcome you'd like**

I would like to import the AFT-Management account, or what is the best practice to apply changes to this account?

My use case is that I need to create an IAM user with a few policies to allow Gitlab to push into the CodeCommit repositories inside the AFT-Management account.

**Comment by snebhu3** [comment]
@dignajar thanks for reaching out.
The process to import AFT management account is the same as onboarding any existing Control Tower account by specifying the account request in the aft-account-request repository. Please refer the [account provisioning documentation](https://docs.aws.amazon.com/controltower/latest/userguide/taf-account-provisioning.html#aft-provision-account). 

To apply changes to the account you could leverage [account customization](https://docs.aws.amazon.com/controltower/latest/userguide/aft-account-customization-options.html).

**Comment by dignajar** [comment]
@snebhu3 works perfect! thanks
