### ISSUE TITLE
AFT upgrade from 1.3.6 to 1.6.2  passed ; but account provisioning failed ; stuck at sqs queue ; lambda zipping issue

### ISSUE THREAD

**Issue by acvir** [aws-ia/terraform-aws-control_tower_account_factory#227]
**Terraform Version & Prov:**

**AFT Version:**

AFT Version 1.6.2
(Can be found in the AFT Management Account in the SSM Parameter `/aft/config/aft/version`)

**Terraform Version & Provider Versions**
Please provide the outputs of `terraform version` and `terraform providers` from within your AFT environment

`terraform version`
```
{Terraform v1.1.7}
```

`terraform providers`
```
{hashicorp/aws v4.27.0}
```

**Bug Description**

Perform upgrade  from  aft version 1.3.6  to 1.6.2 , upgrade completed  sucessfully , but after that account provisioning 
was stuck .
1. we saw the  SQS queue did not process the msgs , it just piled up.
2. we check the lambda function "aft-account-request-processor"  found below msg from cloudwatch

{
    "time_stamp": "2022-08-25 10:43:59,087",
    "log_level": "ERROR",
    "log_message": {
        "FILE": "aft_account_request_processor.py",
        "METHOD": "lambda_handler",
        "EXCEPTION": "module 'aft_common.aft_utils' has no attribute 'get_ct_management_session'"
    }
}

Traceback (most recent call last):
  File "/var/task/aft_account_request_processor.py", line 29, in lambda_handler
    ct_management_session = utils.get_ct_management_session(session)
AttributeError: module 'aft_common.aft_utils' has no attribute 'get_ct_management_session'
{"time_stamp": "2022-08-25 10:43:59,087", "log_level": "ERROR", "log_message": { "FILE": "aft_account_request_processor.py", "METHOD": "lambda_handler", "EXCEPTION": "module 'aft_common.aft_utils' has no attribute 'get_ct_management_session'" }} Traceback (most recent call last): File "/var/task/aft_account_request_processor.py", line 29, in lambda_handler ct_management_session = utils.get_ct_management_session(session) AttributeError: module 'aft_common.aft_utils' has no attribute 'get_ct_management_session'

**To Reproduce**
4. Click on '....'
5. Scroll down to '....'
6. See error

**Expected behavior**

**Related Logs**
Provide any related logs or error messages to help explain your problem.

**Additional context**

This issue happens when the lambdas function does not get updated , but the AFT version gets updated from 1.3.2 to 1.6.2
create a individual Zip files for the lambda's in aft_lambda folder and  commit . this will update the existing .zip files and new version of lambda's will be deployed .

location of lambda's folders which needs to be zipped 
https://github.com/aws-ia/terraform-aws-control_tower_account_factory/tree/main/src/aft_lambda/

gitlab is used as CI/CD tool.

upgrade path  (first deployment version done in April2022 )1.1.6---> (second deployment version july 2022 )1.32---->(third deployment version Aug 2022)1.62

**Comment by balltrev** [comment]
We do see this issue when the lambda layer itself isn't updated as a part of a deployment. To troubleshoot this, I would recommend looking into the CodeBuild logs for the `python-layer-builder-aft-common-$UID` project in your AFT management account.

**Comment by acvir** [comment]
checked the python-layer-builder logs , no errors the lambda layers.zip file is getting uploaded with out errors attached logs in zip
[python-layer-builder-aft-common-logs.zip](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/files/9437822/python-layer-builder-aft-common-logs.zip)

gist of the log
-----------
upload: ./layer.zip to s3://aft-customizations-pipexxxx-9x9999999x/layer.zip

[Container] 2022/08/25 10:43:12 Phase complete: BUILD State: SUCCEEDED
[Container] 2022/08/25 10:43:12 Phase context status code:  Message: 
[Container] 2022/08/25 10:43:12 Entering phase POST_BUILD
[Container] 2022/08/25 10:43:12 Phase complete: POST_BUILD State: SUCCEEDED
[Container] 2022/08/25 10:43:12 Phase context status code:  Message:

**Comment by acvir** [comment]
Could you please point us to the section of the code which actually zip's the aft_lambda/*   and uploads as lambda functions
thats the section to review and triage .
location of lambda's folders which needs to be zipped
https://github.com/aws-ia/terraform-aws-control_tower_account_factory/tree/main/src/aft_lambda/

**Comment by balltrev** [comment]
Responsible for building and uploading the layer, https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/main/modules/aft-lambda-layer/buildspecs/aft-lambda-layer.yml

How we refer to the Lambda Layer ARN throughout AFT, https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/main/modules/aft-lambda-layer/outputs.tf

And this is the module that handles the AFT Lambda handler source code, https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/main/modules/aft-archives/data.tf and associated outputs, https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/main/modules/aft-archives/outputs.tf

--- 

If the CodeBuild job is succeeding, and the latest code is hosted in S3, we have seen issues with the environment executing `terraform apply` run out of memory, or run into networking issues. My next suggestion is to look into your apply logs for issues here.

**Comment by acvir** [comment]
This where the problem is , zipping does not happen , we do it manually and upload to repo after that lambda functions get  updated.
https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/main/modules/aft-archives/data.tf 

check the "Additional context" above for more info.

**Comment by snebhu3** [comment]
@acvir Thanks for providing more context. 
AFT leverages the Terraform provided `archive_file` to create these archives as a part of the `terraform apply` activity. If this is failing, our recommendation is to reach out to Hashicorp for further troubleshooting.
