### ISSUE TITLE
[Feature Request] Custom tags to CT resources.

### ISSUE THREAD

**Issue by shmykyta** [aws-ia/terraform-aws-control_tower_account_factory#23]
Hello.
We use AWS Cost Explorer + all resources tagging with our specific tags strategy.
The module creates a lot of resources with single tag:
https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/d347c43d90a048b68184b9f29e2e448ff6c8561e/providers.tf#L5-L9 

Can you create `custom_tags` or something like that to define custom tags to control tower resources?

Thanks.

**Comment by adam-daily** [comment]
Hi, thanks for the request. Just to confirm that I understand the request, are you thinking something like having the tags on these providers be the `managed_by = AFT` tag, in addition to custom tags as an input to the AFT module?

**Comment by evairmarinho** [comment]
Hi! @adam-daily , let's wait for our colleague to respond, but I believe he is asking something like this:
```hcl
default_tags {
    tags = merge ( { managed_by = "AFT" }, var.custom_tags )
}
```

**Comment by shmykyta** [comment]
Hi!
@adam-daily correct, @evairmarinho thanks for answering, that's actually wait I mean

**Comment by adam-daily** [comment]
Got it, that makes sense. Thanks for adding the detail! I've captured the info here and added it as a feature request to our backlog.

**Comment by Veevaete** [comment]
Hello,

Is there any update on this feature?

**Comment by Chainshark** [comment]
@balltrev I've taken the liberty of doing the coding locally;

```

variables.tf

variable "custom_tags" {
  type        = map(string)
  description = "A map of tags to be applied to all resources"
  default     = {}
}


providers.tf

# Copyright Amazon.com, Inc. or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
provider "aws" {
  alias  = "ct_management"
  region = var.ct_home_region
  # The default profile or environment variables should authenticate to the Control Tower Management Account as Administrator
  default_tags {
    tags = merge({
      managed_by = "AFT"
    }, var.custom_tags)
  }
}

provider "aws" {
  alias  = "aft_management"
  region = var.ct_home_region
  assume_role {
    role_arn     = "arn:${data.aws_partition.current.partition}:iam::${var.aft_management_account_id}:role/AWSControlTowerExecution"
    session_name = local.aft_session_name
  }
  default_tags {
    tags = merge({
      managed_by = "AFT"
    }, var.custom_tags)
  }
}
provider "aws" {
  alias  = "tf_backend_secondary_region"
  region = var.tf_backend_secondary_region
  assume_role {
    role_arn     = "arn:${data.aws_partition.current.partition}:iam::${var.aft_management_account_id}:role/AWSControlTowerExecution"
    session_name = local.aft_session_name
  }
  default_tags {
    tags = merge({
      managed_by = "AFT"
    }, var.custom_tags)
  }
}
provider "aws" {
  alias  = "audit"
  region = var.ct_home_region
  assume_role {
    role_arn     = "arn:${data.aws_partition.current.partition}:iam::${var.audit_account_id}:role/AWSControlTowerExecution"
    session_name = local.aft_session_name
  }
  default_tags {
    tags = merge({
      managed_by = "AFT"
    }, var.custom_tags)
  }
}
provider "aws" {
  alias  = "log_archive"
  region = var.ct_home_region
  assume_role {
    role_arn     = "arn:${data.aws_partition.current.partition}:iam::${var.log_archive_account_id}:role/AWSControlTowerExecution"
    session_name = local.aft_session_name
  }
  default_tags {
    tags = merge({
      managed_by = "AFT"
    }, var.custom_tags)

  }
}
```

**Comment by TonyLovesDevOps** [comment]
@adam-daily Can you share why this was "closed as completed"? I don't see an input variable to specify custom tags. For the moment, I'm stealing the solution that  @be-aws-architect [posted](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/issues/23#issuecomment-1512687981) (thanks!!)

**Comment by rgleme** [comment]
Hello. Any update on this @adam-daily ?

**Comment by lsampa** [comment]
I was wondering if there have been any updates on this issue. Also, I wanted to highlight that it is necessary for the provider tags to be as variable to support custom tags, especially for Migration Acceleration Program (MAP) projects, where tags are required for accurate cost allocation.

**Comment by garybaines** [comment]
Any reason this was never implemented? We have the same need to be able to set a list of default tags for all resources created. Currently all we get is "managed_by = AFT".

Looks like it should be a simple change to allow passing in a variable to the module, and referencing in it the providers.tf file.
