### ISSUE TITLE
Terraform configuration file .terraformrc

### ISSUE THREAD

**Issue by dignajar** [aws-ia/terraform-aws-control_tower_account_factory#230]
I need to configure some parameters and credentials for Terraform Cli into the file `.terraformrc`. 
https://www.terraform.io/cli/config/config-file

I was thinking of manipulating this file from the `pre-api-helpers.sh`, but as this script runs before the Terraform exists, I'm having some issues, any recommendations?

**Comment by balltrev** [comment]
I see the following on their documentation:
> On all other systems, the file must be named .terraformrc (note the leading period) and placed directly in the home directory of the relevant user.

Have you tried storing your configuration at $HOME/.terraformrc during the pre-api-helpers.sh script? If I understand correctly this should be read later during the `terraform apply` process.

**Comment by dignajar** [comment]
@balltrev yes, I tried `$HOME/.terraformrc` and also here `/opt/aft/bin` where is the Terraform Cli binary.

**Comment by dignajar** [comment]
I configured in another way the Terraform Cli and the credentials and works fine.

File `pre-api-helpers.sh`
```
git config --global url."https://oauth2:${GITLAB_TOKEN}@gitlab.com".insteadOf https://gitlab.com
```

Terraform file `network.tf`
```
module "network" {
  source         = "git::https://gitlab.com/repo-name/vpc.git"
}
```
