### ISSUE TITLE
nitpick: execute terraform commands with -no-color switch in every customization buildspec

### ISSUE THREAD

**Issue by v-rosa** [aws-ia/terraform-aws-control_tower_account_factory#231]
**Describe the outcome you'd like**

Run terraform commands with `-no-color` switch in every buildspec (https://github.com/aws-ia/terraform-aws-control_tower_account_factory/tree/main/modules/aft-customizations/buildspecs)

**Is your feature request related to a problem you are currently experiencing? If so, please describe.**

Reading past logs on CW can become very frustrating.

**Comment by balltrev** [comment]
Thanks for bringing this up @v-rosa, I've added a backlog for our team to address this

**Comment by stumins** [comment]
Hi @v-rosa, 

[Release 1.7.0](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/releases/tag/1.7.0) fixes this issue - thanks for the report!
