### ISSUE TITLE
Support for tags in customization repositories

### ISSUE THREAD

**Issue by oleptho** [aws-ia/terraform-aws-control_tower_account_factory#234]
We are running multiple AFT environments and to minimize code duplication we would like to use the same global- and account customization repository for the different AFT environments, and separate them with tags. It is support for specifying `global_customizations_repo_branch` and `account_customizations_repo_branch` but not `tags`. It would be great if we could specify tags like `account_customizations_repo_tag` and `global_customizations_repo_tag`.

Tried to specify a repository tag in the `account_customizations_repo_branch` but it failed with "Could not find branch".

**Comment by snebhu3** [comment]
Hi @oleptho, thank you for reaching out.
Please may you provide more details about your AFT setup and your use case for this feature request:
* How would support for specifying repository tags help you in your use case?
* Would you be able to achieve your goal by leveraging repository branches?

Thank you.

**Comment by oleptho** [comment]
Hi @snebhu3! Our initial plan was to use repository tags to specify a specific version of the global/account customization for our test AFT environment and prod AFT environment. It can be solved by using repository branch, but we prefer working with tags.

After looking a bit more into the AFTs features, I think we will rather use terraform modules with tags for our customizations. I will close this feature request.
