### ISSUE TITLE
Create an account in a new OU

### ISSUE THREAD

**Issue by jesperalmstrom** [aws-ia/terraform-aws-control_tower_account_factory#235]
**Terraform Version & Prov:**
Terraform v1.2.8
**AFT Version:**
1.3.3
**Terraform Version & Provider Versions**
`terraform version`
```
Terraform v1.2.8
on darwin_arm64
```

`terraform providers`
```
╷
│ Error: No configuration files
```

**Bug Description**

**To Reproduce**
1. Create a new OU and register it with  Account Factory/Control Tower
2. add a new file in the aft-account-request repo.
3. Check in
4. Error seen in Code Pipeline log

**Expected behavior**
A new account should be created in the OU specified. 

**Related Logs**
```
╷
│ Error: ConditionalCheckFailedException: The conditional request failed
│ 
│   with [module.OUNAME-Customer1.aws ](https://support.console.aws.amazon.com/support/module.OUNAME-Customer1.aws) _dynamodb_table_item.account-request,
│   on modules/aft-account-request/ddb.tf line 4, in resource "aws_dynamodb_table_item" "account-request":
│    4: resource "aws_dynamodb_table_item" "account-request" {
│
```
**Additional context**
CW log does not give any leads.

**Comment by stumins** [comment]
Hey @jesperalmstrom,

[AFT versions 1.3.5 and older contain a bug](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/issues/205) that causes AFT components to use the latest code in the AFT source repository instead of the version of AFT that was deployed. This results in a variety of issues at runtime.

Please upgrade to the newest version of AFT & retry your account request.

**Comment by jesperalmstrom** [comment]
The person that installed AFT have left the company and my attempts to restore a state which allows me to upgrade have failed. Do you have a upgrade method which is fools proof?

**Comment by stumins** [comment]
@jesperalmstrom 

Are you experiencing a specific issue when upgrading versions, and do you have error logs you can provide for the issue?

**Comment by stumins** [comment]
Hey @jesperalmstrom 

I'm going to close this issue due to lack of activity. Please feel free to open new issues for specific problems you experience, or you can also open a ticket with AWS Premium Support for additional support.

**Comment by jarrettj** [comment]
Hi,

Good day.

Receiving the same error ConditionalCheckFailedException. Is there a process to restore a previous state file? The terraform apply phase failed. :(

This is in the aft-account-customizations repo. Not sure what I should update in the DynamoDB table. Thanks.

Regards,
Jarrett

**Comment by jarrettj** [comment]
Found it, had to delete the item in DynamoDB table :)

**Comment by jesperalmstrom** [comment]
My issue was a reused AccountEmail in the control_tower_parameters

```json
control_tower_parameters = {
     AccountEmail              = "duplicate-email-address@company.com"
     ...
}
```
