### ISSUE TITLE
Deleting an account's tag in its `aft-account-request` config doesn't actually untag the account in AWS Organizations

### ISSUE THREAD

**Issue by ruthchangadi** [aws-ia/terraform-aws-control_tower_account_factory#238]
**AFT Version:** 1.6.3

**Terraform Version & Provider Versions**

`terraform version`
```
Terraform v1.2.9
```

`terraform providers`
```
+ provider registry.terraform.io/hashicorp/aws v4.28.0
```

**Bug Description**
Removing an account tag for an account in `aft-account-request` and triggering an update does not actually remove the tag from the account in AWS Organizations.

**To Reproduce**
1. In the `.tf` file for a particular account in the `aft-account-request` repo, delete one of the tags under `account_tags`. 
2. Save and add the file with git and push the changes to `aft-account-request`'s master branch (thus triggering the appropriate pipelines to start running).
3. Wait for the automations/step functions to finish running (`ct-aft-account-request` pipeline, Lambdas, etc.).
4. View the account's tags in AWS Organizations on the Control Tower management account. The tag that was deleted from the account's `.tf` file will still exist.

**Expected behavior**
The tag that was deleted from the account's `.tf` file is ultimately untagged from the account in AWS Organizations.

**Comment by stumins** [comment]
Hi @ruthchangadi,

I believe this may be related to https://github.com/aws-ia/terraform-aws-control_tower_account_factory/issues/160. 

We have an existing backlog item to improve how AFT manages the state of tags applied via `aft-account-request`.

**Comment by ruthchangadi** [comment]
Thanks @stumins--I did see that issue from before. Thanks for the update.

**Comment by stumins** [comment]
Closing as duplicate - track work in #160
