### ISSUE TITLE
Fix release names

### ISSUE THREAD

**Issue by evairmarinho** [aws-ia/terraform-aws-control_tower_account_factory#24]
Based on best pratices, the release name should be a number as 1.0.0, 1.2.0, 1,2,1. 

Reference: https://semver.org/

Example: https://github.com/terraform-aws-modules/terraform-aws-vpc/releases

**Comment by adam-daily** [comment]
Hey there, thanks for the feedback. We partly chose this naming convention to maintain consistency with other repos in the `aws-ia` organization. That said, we're taking a story into our backlog to revisit our processes where release naming and versioning is concerned. Closing this issue for now in lieu of internal tracking.
