### ISSUE TITLE
aft-invoke-customizations with OU

### ISSUE THREAD

**Issue by Menahem1** [aws-ia/terraform-aws-control_tower_account_factory#240]
**AFT Version:** 1.6.3

**Bug Description**
Impossible to execute aft-invoke-customizations with custom (child) OU

**To Reproduce**
1. Go to Step Functions -> aft-invoke-customizations
2. Launch a new execution with a custom OU (registered with Control Tower and with 1 account enrolled in that sub-ou)

```
{
  "include": [
    {
      "type": "ous",
      "target_value": [ "ou-xxxxxxxx"]
    }
  ]
}
```

After that it will tell me that running pipeline are 0, i have try with parent and child OU same thing : 

`{"include":[{"type":"ous","target_value":["ou-xxxxxxxxx"]}],"targets":{"number_pending_accounts":0,"pending_accounts":[],"target_accounts_info":[]},"running_executions":{"running_pipelines":0}}`

**Expected behavior**
Launch the pipeline with the OU detailled

**Comment by stumins** [comment]
Hi @Menahem1,

I believe this is a duplicate issue of https://github.com/aws-ia/terraform-aws-control_tower_account_factory/issues/126

**Comment by Menahem1** [comment]
Hi @stumins 
It's right, thanks
I close that issue

Thanks
