### ISSUE TITLE
push request not triggering account request

### ISSUE THREAD

**Issue by omotoso78** [aws-ia/terraform-aws-control_tower_account_factory#242]
**Terraform Version & Prov:**
Terraform Version >= 0.15.1 , <2.0.0 & Prov: >= 4.9.0, < 5.0.0
**AFT Version:**
(Can be found in the AFT Management Account in the SSM Parameter `/aft/config/aft/version`)
1.6.2

**Terraform Version & Provider Versions**
Please provide the outputs of `terraform version` and `terraform providers` from within your AFT environment

`terraform version`
```
terraform Version >= 0.15.1, <2.0.0
```

`terraform providers`
```
aws >= 4.9.0, < 5.0.0
```

**Bug Description**
my 4 AFT repos are located on a git enterprise. The codestarconnection is established and available. Delivery of changes to the repo through the AWS app webhook was successful, unfortunately, this did not triggering the subsequent processes, the dynamo table request, the build or the account. How can I troubleshoot the problem?

**To Reproduce**

**Expected behavior**

**Related Logs**
Provide any related logs or error messages to help explain your problem.

**Additional context**

**Comment by hanafya** [comment]
I would recommend reaching out to AWS Premium support for better assistance on this issue as they would be able to dive deeper and help troubleshoot the issue.
