### ISSUE TITLE
Create a CHANGELOG.md file to register the changes of each release

### ISSUE THREAD

**Issue by evairmarinho** [aws-ia/terraform-aws-control_tower_account_factory#25]
Reference: https://keepachangelog.com/en/1.0.0/

Example: https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/master/CHANGELOG.md

**Comment by adam-daily** [comment]
Thanks for the reach out. I've added this as a detail to a larger story we're tracking internally for release and version messaging. Closing this issue for now in lieu of internal tracking.
