### ISSUE TITLE
IAM error in account customisations using hashicorp/awscc provider

### ISSUE THREAD

**Issue by pecav89** [aws-ia/terraform-aws-control_tower_account_factory#254]
**Terraform Version & Prov:**

**AFT Version:**
1.6.4

**Terraform Version & Provider Versions**
Please provide the outputs of `terraform version` and `terraform providers` from within your AFT environment

`terraform version`
```
1.2.6
```

`terraform providers`
```
hashicorp/awscc
```

**Bug Description**
When running the VPC module from provider hashicorp/awscc within account customisations it is failing with an IAM error on a cloud formation resource. Error is below in related logs section. 

**To Reproduce**
1. Within account customisations add a `.tf` file and include `aws-ia/vpc/aws` module with version `>= 3.0.0`.
2. Commit into repo.
3. Execute the account customisations from CodePipeline.

**Expected behavior**
VPC to be created through the account customisations pipeline

**Related Logs**

```
│ Error: AWS SDK Go Service Operation Unsuccessful
--
639 | │
640 | │   with module.vpc.awscc_ec2_route_table.public["eu-west-2b"],
641 | │   on .terraform/modules/vpc/main.tf line 50, in resource "awscc_ec2_route_table" "public":
642 | │   50: resource "awscc_ec2_route_table" "public" {
643 | │
644 | │ Calling Cloud Control API service CreateResource operation returned:
645 | │ operation error CloudControl: CreateResource, https response error
646 | │ StatusCode: 400, RequestID: 268aee7b-14f4-40f6-9593-31419b3f8f7f, api error
647 | │ AccessDeniedException: User:
648 | │ arn:aws:sts::AccountID:assumed-role/AWSAFTAdmin/AWSAFT-Session is not
649 | │ authorized to perform: cloudformation:CreateResource on resource:
650 | │ arn:aws:cloudformation:eu-west-2:AccountID:resource/* because no
```

**Comment by wellsiau-aws** [comment]
since you are using `awscc` provider, I assume you also modified the `aft-providers.jinja` file? can you share your `aft-providers.jinja` snippet?

**Comment by pecav89** [comment]
Was a bit of an idiot and noticed that the config was not correct for the provider so closed the issue down.
