### ISSUE TITLE
Character Error Provisioned in DynamoDB

### ISSUE THREAD

**Issue by jonrwong-amazon** [aws-ia/terraform-aws-control_tower_account_factory#256]
**Terraform Version & Prov:**

**AFT Version:**
(Can be found in the AFT Management Account in the SSM Parameter `/aft/config/aft/version`)

**Terraform Version & Provider Versions**
Please provide the outputs of `terraform version` and `terraform providers` from within your AFT environment

`terraform version`
```
{Replace me}
```

`terraform providers`
```
{Replace me}
```

**Bug Description**

Provisioned a new account with a character not allowed in the AccountName for control_tower_parameters (using a '+' symbol). Ex) test+sandbox. This caused the CodePipeline to succeed and to add the entry into DynamoDB with that account name even though it is not allowed. This caused the account to not end up being created, or showing up in Organizations even though it seemed like it went through the pipeline successfully. 

**To Reproduce**

**Expected behavior**

**Related Logs**
Provide any related logs or error messages to help explain your problem.

**Additional context**

**Comment by balltrev** [comment]
Hello @jonrwong-amazon, we're aware that error reporting is an area that AFT needs improvement on. I've gone ahead and added this to the backlog item and will bring it up with the team. Thanks!

**Comment by stumins** [comment]
Closing as a duplicate - please track resolution using https://github.com/aws-ia/terraform-aws-control_tower_account_factory/issues/103
