### ISSUE TITLE
Use of different providers in custom modules.

### ISSUE THREAD

**Issue by jarrettj** [aws-ia/terraform-aws-control_tower_account_factory#257]
**Describe the outcome you'd like**
I'd like the ability to pass a provider to a module. 

**A clear and concise description of what you want to happen.**
The multiple region customisation shows how to do this using the updated provider jinja file in the root. But how would we do the same with a module instead of a resource that can reference the provider available in the root.

**Is your feature request related to a problem you are currently experiencing? If so, please describe.**
Reusing shared modules across Prod and Staging environments.

**A clear and concise description of what the problem is.**
In the structure below, I would like both app and staging-app to call the acm module to create a resource in the us-east-1 region which is not the applications default region. 
- aft-account-customizations
  - app
    - terraform
      - main.tf
  - staging-app
    - terraform
      - main.tf
  - modules
    - acm
      - main.tf

Hope that is clear :). Thanks.

Regards,
Jarrett

**Comment by snebhu3** [comment]
@jarrettj thank you for reaching out.
You could refer to [ Terraform documentation ](https://www.terraform.io/language/modules/develop/providers) for how you could use custom providers for custom modules.

**Comment by jarrettj** [comment]
That's obviously what I have done. But within the AFT pipeline I can't seem to get it to work. Tried placing the provider details in the module. No luck. Basically copied what's produced from the jinja in root. No luck. And there's no example like it. Will add what I've tried and the errors. Thanks.

**Comment by jarrettj** [comment]
Had to pass the provider along to the shared sub module and not declare it there. Only have to require it in the sub module.
