### ISSUE TITLE
Account pipeline is not triggered when Global Customization repo is updated

### ISSUE THREAD

**Issue by vaspoz** [aws-ia/terraform-aws-control_tower_account_factory#263]
**Terraform Version & Prov:**

**AFT Version:**
(Can be found in the AFT Management Account in the SSM Parameter `/aft/config/aft/version`)
1.6.5

**Terraform Version & Provider Versions**
Please provide the outputs of `terraform version` and `terraform providers` from within your AFT environment

`terraform version`
```
1.3.0
```

**Bug Description**
After a new account has been provisioned, there's a pipeline created **XXXX-customizations-pipeline**. This pipeline has 2 sources (codeCommit repos):
- aft-global-customizations
- aft-account-customizations

So, it should be triggered by either of these 2 repos get new push.
But I found only 2 event bridge rules related to codeCommit triggers:
- aft-account-provisioning-customizations-trigger
- aft-account-request-codepipeline-trigger

Is global customizations trigger missing? 

**To Reproduce**
1. Provision an account
2. Push to **aft-global-customizations**
3. Observe that XXXX-customizations-pipeline is not triggered

**Expected behavior**
**XXXX-customizations-pipeline** rerun with new global customizations

**Comment by snebhu3** [comment]
@vaspoz thank you for reaching out to us.
The re-invocation of the customization pipeline is not triggered automatically when you update a customization in the  customization repos. To re-invoke customization you would need to invoke the AWS SF `aft-invoke-customizations` in the AFT management account with appropriate input payload according to your roll-out strategy. 
Please refer to `Re-invoke customizations` section in the [Account customization document.](https://docs.aws.amazon.com/controltower/latest/userguide/aft-account-customization-options.html)

**Comment by vaspoz** [comment]
hi @snebhu3 , yes, I'm aware of ```aft-invoke-customizations``` SF
But what was the reason behind that? Wouldn't it be more useful to automatically update existing accounts whenever new global customization is added, or you've seen some drawbacks of that automation?

**Comment by vaspoz** [comment]
closing since seems it's "works as expected" issue

**Comment by perlboy** [comment]
@vaspoz I know this is closed but the general thinking here is that reapplying global customizations beyond the initial deployment might be a bad idea if for instance the account is now being managed by another terraform repository. It ultimately depends what you are doing in the global customization but at least for us we have it prep an initial VPC and delegate an IPAM pool, the management is then handed over to the per account terraform cloud workspace which _may_ modify the VPC state in some way.

**Comment by vaspoz** [comment]
@perlboy , actually after thinking about that for some time I also came to the same conclusion.
However, looking at it from that perspective opens an opposite problem - if we don't want to reapply global customizations, then that account customization pipeline should not be triggered, right (like from account customization repo)? Because it'll pick up the last changes from the global cust repository anyway
