### ISSUE TITLE
Import aft-managment and audit and log archive

### ISSUE THREAD

**Issue by pmmalinov01** [aws-ia/terraform-aws-control_tower_account_factory#266]
**Describe the outcome you'd like**
Import aft-managment and Audit and Log Archive accounts into aft-managment.

From reading [220](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/issues/220) and [20](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/issues/20) I am not 100% sure if this is good idea or is there something that leads me not to import those 3 accounts in aft. The Audit and Log Arcive are created from control and are a particular case. Has anyone imported the accounts in v1.6.4 and have you seen any issue with the process.
Is the same process as importing other accounts provision via CT

**Comment by hanafya** [comment]
Hey @pmmalinov01!
We started supporting this with version 1.4.0. Please refer to the [account provisioning documentation](https://docs.aws.amazon.com/controltower/latest/userguide/taf-account-provisioning.html#aft-provision-account).

To apply changes to the account you could leverage [account customization](https://docs.aws.amazon.com/controltower/latest/userguide/aft-account-customization-options.html).

**Comment by pmmalinov01** [comment]
Account was imported without any issues

**Comment by jarrettj** [comment]
Hi,

Good day.

We've tried to import the Audit account to enable guard duty. But it does not work. Is there anything special that should be done? We have another existing account that was created outside of the AFT accounts and it works fine. 

We can see the entry for the Audit account in the DynamoDB table in the AFT Management account, but none of the pipeline related resources were setup. Any pointers in where and how to debug? Thanks.

Regards,
Jarrett

**Comment by wellsiau-aws** [comment]
@jarrettj , it occurred to me once that the import silently failed due to error state in the service catalog provisioned product. I would try to go to CT management account, check the service catalog provisioned product for your Audit account and make sure it's not in Unhealthy state.

**Comment by wellsiau-aws** [comment]
> @jarrettj , it occurred to me once that the import silently failed due to error state in the service catalog provisioned product. I would try to go to CT management account, check the service catalog provisioned product for your Audit account and make sure it's not in Unhealthy state.

actually, ignore this, you mentioned the Audit account, which are not shown in the service catalog as provisioned product. I apologize.

I would come back and check if the import parameters are correct, i.e. account name, OU, email address. Next, I would check for any error logs on Lambda function `aft-account-request-action-trigger ` and `aft-account-request-processor `

**Comment by jarrettj** [comment]
You legend you @wellsiau-aws . I thought only the email address had to match. And the other values are set :). Updated the account name, OU, email address to match what is in AWS and the Audit account is being setup. Thanks again, Regards Jarrett.
