### ISSUE TITLE
PutParameter API throttled when applying several custom_fields in account_request.

### ISSUE THREAD

**Issue by dansor-AZ** [aws-ia/terraform-aws-control_tower_account_factory#271]
Per the documentation [1], the custom_fields provided in the [account request repo](https://github.com/hashicorp/learn-terraform-aft-account-request) are stored as ssm parameters in the target account as:

/aft/account-request/custom-fields/CUSTOM_FIELD_NAME

However, if you input multiple custom_fields, the AWS lambda function "aft-account-provisioning-framework-account-metadata-ssm" that creates this parameter in the parameter store gets throttled such that it throws the error:

Error:
====================================
"An error occurred (ThrottlingException) when calling the PutParameter operation (reached max retries: 4): Rate exceeded"
====================================

Based on the error above, the PutParameter API call is being throttled. Based on the service quotas for Systems Manager [2], the limit for PutParameter API call is not currently disclosed. Additionally, enabling "Parameter Store throughput" only covers certain API calls and not "PutParameter".

It looks like that this is a current limitation in the lambda function that handles this request as looking at the function there is no exponential backoff implemented to mitigate the issue being experienced above. 

It would be great to have this implemented as this will definitely help especially when you have multiple custom_fields that are applied in the account_request phase.

References:
[1] https://learn.hashicorp.com/tutorials/terraform/aws-control-tower-aft
[2] AWS Systems Manager endpoints and quotas - Service quotas - https://docs.aws.amazon.com/general/latest/gr/ssm.html#limits_ssm

**Comment by balltrev** [comment]
Thanks for reaching out about this @dansor-AZ. The `boto3` client does have built-in exponential back-off as part of it's retry logic on throttling exceptions and is enabled by default. I'll make a backlog to consider how to improve this approach with the team.

**Comment by stumins** [comment]
Hi @dansor-AZ,

We just released [AFT 1.10.4](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/releases/tag/1.10.4) with improved retry behavior to address this type of throttling issue. Please upgrade to 1.10.4 and let us know if you continue to experience any throttling.

**Comment by stumins** [comment]
We haven't received any reports of continued throttling, so I'm going to go close this issue as completed. Please feel free to open a new ticket if you continue to experience throttling issues on versions >= 1.10.4
