### ISSUE TITLE
Enable elective Guardrails with AFT?

### ISSUE THREAD

**Issue by zhatzbreezy** [aws-ia/terraform-aws-control_tower_account_factory#272]
Hello, 

I am looking at whether this project would fit our needs for deploying Control Tower in our environment. I have 3 questions: 

1) Is it possible to enable Control Tower elective guardrails to a given OU? I.e. can I use this terraform module to deploy the elective control guardrail `Control: Detect whether any Amazon EC2 instance has an associated public IPv4 address` to an OU? or do I have to manually extract the AWS Config Rules/SCP's and apply them in the `aft-customizations` repo? 

2) If you are using AFT, is it best practice to completely move away from using terraform to organize & manage your AWS Org w/ `aws_organizations_account` `aws_organizations_organizational_unit` and `aws_organizations_policy` terraform resources ? Basically are you just supposed to forget about AWS Organizations and just use AFT moving forward? 

3) If a new landing zone version is released by AWS and we want to upgrade to the new landing zone version, what are the implications of using this AFT module?

**Comment by balltrev** [comment]
Hey @zhatzbreezy thanks for the questions.

>Is it possible to enable Control Tower elective guardrails to a given OU? I.e. can I use this terraform module to deploy the elective control guardrail Control: Detect whether any Amazon EC2 instance has an associated public IPv4 address to an OU? or do I have to manually extract the AWS Config Rules/SCP's and apply them in the aft-customizations repo?

You would have to extract them and apply during account customization, specifically as an account customization targeting your Control Tower Management account

>If you are using AFT, is it best practice to completely move away from using terraform to organize & manage your AWS Org w/ aws_organizations_account aws_organizations_organizational_unit and aws_organizations_policy terraform resources ? Basically are you just supposed to forget about AWS Organizations and just use AFT moving forward?

I would recommend reaching out to AWS Premium Support to get in touch with someone better able to recommend best practices for your environment

>If a new landing zone version is released by AWS and we want to upgrade to the new landing zone version, what are the implications of using this AFT module?

AFT is not unique from any other deployed infrastructure within your Control Tower environment. Landing zone upgrades should not pose any issue, however it is recommended to test landing zone upgrades in a test environment.
