### ISSUE TITLE
When invoke-customizations, why run_create_pipeline is always true

### ISSUE THREAD

**Issue by vaspoz** [aws-ia/terraform-aws-control_tower_account_factory#273]
In order to apply changes in, say, global customizations, we have to run **aft-invoke-customizations** state machine.
As a first step, it get's all AFT provisioned accounts from **aft-request-metadata** table.
Then it starts to iterate over it with first action - create a customization pipeline for each of the accounts. But we already have all of them.
Creation of a pipeline defined by condition **run_create_pipeline**.
Apparently, it's **always true**.

In aft_common layer, I found this line:
```
invoke_event["account_provisioning"]["run_create_pipeline"] = "true"
```

why it's always true? It has to be false (since we're reinvoking existing pipelines to apply customizations), or at least customizable

**Comment by vaspoz** [comment]
It's actually not a bug it seems, it's more of a feature request. Could you please update the labels?

**Comment by balltrev** [comment]
Hey @vaspoz, thanks for the request! I'll go ahead and create a backlog with the team to discuss optionally executing the customization pipeline creation process.

**Comment by stumins** [comment]
Hi @vaspoz,

This action is always set to true to ensure that an account's customization pipeline is in a healthy state (not deleted out of band, or an older version of AFT that uses the legacy roles, etc.). If the pipeline already exists, this stage is a quick no-op.
