### ISSUE TITLE
"input_aft_feature_delete_default_vpcs_enabled" control only delete AFT Management Account's default VPCs

### ISSUE THREAD

**Issue by oceannic** [aws-ia/terraform-aws-control_tower_account_factory#274]
Hi there,

Is this logic intended to only delete the Default VPC in AFT management account only? 
https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/f8a3a30627f1dfe228dda7db6d64e72957cecece/src/aft_lambda/aft_feature_options/aft_delete_default_vpc.py#L61-L81

It's a bit confusing from [AWS documentation (Delete the AWS default VPC)](https://docs.aws.amazon.com/controltower/latest/userguide/aft-feature-options.html#delete-default-vpc-option) descriptions, and the module [README](https://github.com/aws-ia/terraform-aws-control_tower_account_factory#input_aft_feature_delete_default_vpcs_enabled) as well .

I have the impression of by turning on this feature the AFT pipeline will helps to delete all regions default VPCs for the new account created by AFT/CTLZ. However from the code logic it's only delete AFT Management Account's default VPCs.

Besides, the code looks strange as well, if this option is only intended deleted AFT management account default VPCs only, may I know why it extract the list of regions by target account's session ?
https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/f8a3a30627f1dfe228dda7db6d64e72957cecece/src/aft_lambda/aft_feature_options/aft_delete_default_vpc.py#L51-L60

**Comment by stumins** [comment]
Hi @oceannic,

Thanks for reaching out. The somewhat confusing behavior of this option can be considered a known issue that will not be fixed in AFT v1 due to the risk of breaking changes for customers. Please see our comment in https://github.com/aws-ia/terraform-aws-control_tower_account_factory/issues/200#issuecomment-1178227617 for more detailed information.

Reading the documentation - I agree that is a bit confusing regarding the current behavior. It might be more clear to read it as:

```
Delete the AWS default VPC

When this option is enabled, the AFT pipeline deletes the associated AWS default VPCs for the AFT management account in all AWS Regions, even if you don’t have AWS Control Tower resources deployed in those Regions.

The AFT pipeline does not delete the AWS default VPCs automatically for any AWS Control Tower accounts that AFT provisions, or for existing AWS accounts that you enroll in AWS Control Tower by means of AFT.

To enable this option, set the following feature flag to True in your AFT deployment input configuration.
```

I've created a backlog item for our team to clarify the documentation.

**Comment by oceannic** [comment]
Noted, and thanks for feedbacks @stumins.

**Comment by brakf** [comment]
Dear @stumins ,
It has been almost 2 years and it seems like this behaviour has not changed yet. 
Can you provide an update on this? Is it still in the backlog? When can we expect AFT v2 with this change?

BR
Fabian
