### ISSUE TITLE
Billing account import.

### ISSUE THREAD

**Issue by jarrettj** [aws-ia/terraform-aws-control_tower_account_factory#279]
**Terraform Version & Prov:**
v1.2.8
**AFT Version:**
(Can be found in the AFT Management Account in the SSM Parameter /aft/config/aft/version)
1.6.2

**Bug Description**
Can't import the Billing account. Successfully vended new and existing accounts before. Need to import the Billing account though.

Things I have tried:
- Change the OU name to something simpler.
- Register the OU in Control Tower manually.
- Went through all the Cloudwatch logs in the Management account. No errors.

**Expected behavior**
Billing account should import as all other accounts do.

Regards,
Jarrett

**Comment by adam-daily** [comment]
Hey Jarrett, sorry you're having trouble here. To get assistance, please reach out to AWS Premium Support so they can dive into the details of this account with you and dig into why it isn't successfully getting imported.

**Comment by jarrettj** [comment]
Thanks @adam-daily . Logged a support ticket. But it is possible correct? Thanks.
