### ISSUE TITLE
Unable to deploy AFT module, terraform plan/apply results in below error. I'm using terraform version 1.0.7 &

### ISSUE THREAD

**Issue by ArshikDhar** [aws-ia/terraform-aws-control_tower_account_factory#28]
terraform plan
╷
│ Error: error archiving directory: error encountered during file walk: CreateFile .terraform\modules\aft\modules\aft-account-provisioning-framework\lambda\aft-account-provisioning-framework-validate-request\aft_account_provisioning_framework_validate_request.py: The system cannot find the path specified.
│
│   with module.aft.module.aft_account_provisioning_framework.data.archive_file.validate_request,
│   on .terraform\modules\aft\modules\aft-account-provisioning-framework\lambda.tf line 4, in data "archive_file" "validate_request":  
│    4: data "archive_file" "validate_request" {
│
╵
╷
│ Error: error archiving directory: error encountered during file walk: CreateFile .terraform\modules\aft\modules\aft-account-provisioning-framework\lambda\aft-account-provisioning-framework-get-account-info\aft_account_provisioning_framework_get_account_info.py: The system cannot find the path specified.
│
│   with module.aft.module.aft_account_provisioning_framework.data.archive_file.get_account_info,
│   on .terraform\modules\aft\modules\aft-account-provisioning-framework\lambda.tf line 34, in data "archive_file" "get_account_info": 
│   34: data "archive_file" "get_account_info" {
│
╵
╷
│ Error: error archiving directory: error encountered during file walk: CreateFile .terraform\modules\aft\modules\aft-account-provisioning-framework\lambda\aft-account-provisioning-framework-persist-metadata\aft_account_provisioning_framework_persist_metadata.py: The system cannot find the path specified.
│
│   with module.aft.module.aft_account_provisioning_framework.data.archive_file.persist_metadata,
│   on .terraform\modules\aft\modules\aft-account-provisioning-framework\lambda.tf line 125, in data "archive_file" "persist_metadata":│  125: data "archive_file" "persist_metadata" {

**Comment by balltrev** [comment]
This looks potentially to be the same as https://github.com/aws-ia/terraform-aws-control_tower_account_factory/issues/16

Do you mind sharing how you're sourcing the AFT module?

**Comment by balltrev** [comment]
Feel free to open this issue back up, going to close for now due to inactivity
