### ISSUE TITLE
Cross-account Event Bridge

### ISSUE THREAD

**Issue by andrewkruse** [aws-ia/terraform-aws-control_tower_account_factory#284]
**Terraform Version & Prov:**

**AFT Version:**
(Can be found in the AFT Management Account in the SSM Parameter `/aft/config/aft/version`)

1.7.0

**Terraform Version & Provider Versions**
Please provide the outputs of `terraform version` and `terraform providers` from within your AFT environment

`terraform version`
```
{Replace me}
```

`terraform providers`
```
{Replace me}
```

**Bug Description**
Pre-emptive bug, so pardon the label. Come February next year, cross account set up of account facotry will begin to have some issues. 

> We would like to notify you about an upcoming change for EventBridge cross account event bus targets. At AWS, security is our top priority. We are constantly working on improving our security posture and introducing controls, where necessary, to help our customers secure their applications on AWS. Today, Amazon EventBridge does not require you to create an IAM role when sending events to a cross account event bus target. IAM roles allow you to grant users access to resources in another account and set organization boundaries using Service Control Policies (SCPs) to determine who can send and receive events from accounts in your organization.
> 
> Beginning February 16, 2023, Amazon EventBridge will start requiring IAM roles for all new cross account event bus targets. We are providing you a 90-day notice to give you time to update your Infrastructure-as-Code templates for any new event bus targets. EventBridge already requires IAM roles for all other event bus to event bus delivery use cases, such as cross-region or within the same account. This change will ensure consistency between all routing use cases.

**To Reproduce**

Have account factory deployed into an account that is not your management account.

**Expected behavior**

**Related Logs**
Provide any related logs or error messages to help explain your problem.

**Additional context**

This resource 
https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/main/modules/aft-account-request-framework/eventbridge.tf#L18 needs to specify a role_arn property https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_event_rule#role_arn

**Comment by hanafya** [comment]
Hello @andrewkruse!
We have created an item in our backlog to address this concern.

**Comment by stumins** [comment]
After review, we do not believe AFT will be impacted by the upcoming AWS EventBridge change. AFT implements only one cross-account event bus and the target resource already [specifies a role.](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/main/modules/aft-account-request-framework/eventbridge.tf#L35)

Thanks for raising this issue @andrewkruse!
