### ISSUE TITLE
Error when AFT-account-processor lambda runs

### ISSUE THREAD

**Issue by beegmon** [aws-ia/terraform-aws-control_tower_account_factory#285]
**Terraform Version & Prov:**

**AFT Version:**
1.7.0 (this occured with 1.3.5) as well

**Terraform Version & Provider Versions**
1.3.5 using Terraform cloud and AWS provider version 4.46.0

**Bug Description**
When attempting to provision a new account an error occures in the aft-account-processor lambda runs. The new account is never provisioned.

`[ERROR] ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the DescribeProductAsAdmin operation: Product with name AWS Control Tower Account Factory not found
Traceback (most recent call last):
  File "/var/task/aft_account_request_processor.py", line 37, in lambda_handler
    account_request = AccountRequest(auth=auth)
  File "/opt/python/lib/python3.8/site-packages/aft_common/account_request_framework.py", line 439, in __init__
    self.account_factory_product_id = utils.get_ct_product_id(
  File "/opt/python/lib/python3.8/site-packages/aft_common/aft_utils.py", line 138, in get_ct_product_id
    response = client.describe_product_as_admin(Name=sc_product_name)
  File "/opt/python/lib/python3.8/site-packages/botocore/client.py", line 508, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/python/lib/python3.8/site-packages/botocore/client.py", line 915, in _make_api_call
    raise error_class(parsed_response, operation_name)`

**Expected behavior**
No errors occure and the account is provisioned as expected

**Related Logs**
Provide any related logs or error messages to help explain your problem.

**Additional context**
I have tripple checked to ensure the TF credentials use has admin access in the management account where Service Catalog resides. I have also confirmed that the Product AWS Control Tower Account Factory exists in the service catalog of products in the Control Tower management account.

**Comment by hanafya** [comment]
Hey @beegmon!

Can you see if the AFT role has access to this the service catalog product?

**Comment by beegmon** [comment]
It has admin assigned to the roll

**Comment by balltrev** [comment]
@beegmon, I would recommend you reach out to AWS Premium Support, they should be better able to diagnose the issue in your environment.

**Comment by balltrev** [comment]
@beegmon, I was able to reproduce an error similar to this in a test environment, It occurs when the `AWS Control Tower Account Factory Portfolio` has not granted access to the `AWSAFTService` role. 

Can you try adding the `AWSAFTService` role to the portfolio? From your Control Tower Management Account, navigating in the console to Service Catalog > Portfolios > AWS Control Tower Account Factory Portfolio, and then selecting the Access tab should allow you to grant access to the `AWSAFTService` IAM Role.

**Comment by shigueojp** [comment]
Hi team, I am having the same issue, is there any solution? Thanks :D

**Comment by stumins** [comment]
Hi @shigueojp, can you confirm that the `AWSAFTService` role has access to the Account Factory portfolio?

Follow these steps:

```
From your Control Tower Management Account, navigating in the console to Service Catalog > Portfolios > AWS Control Tower Account Factory Portfolio, and then selecting the Access tab should allow you to grant access to the AWSAFTService IAM Role.
```

**Comment by shigueojp** [comment]
I found the solution the CT was installed in us-east-1, I setted for sa-east-1 and this problem appeared. I setted ct_home_region = "us-east-1" and now it is working as intended.

Hope help is the same problem for @beegmon.


Thank you!

**Comment by shigueojp** [comment]
Hi @shigueojp, can you confirm that the AWSAFTService role has access to the Account Factory portfolio?

Yes, it has. But I found the solution, I created the ct at us-east-1, and instead, I setted to sa-east-1. I did again with us-east-1 and it is working as intended.

I hope is the same problem for @beegmon

Thank you!

**Comment by stumins** [comment]
I'm going to close this issue due to inactivity - please feel free to open a new issue if you are experiencing additional problems.
