### ISSUE TITLE
No expiration set on any CloudWatch LogGroup

### ISSUE THREAD

**Issue by drAlberT** [aws-ia/terraform-aws-control_tower_account_factory#290]
**Terraform Version & Prov:**

**AFT Version:**
1.7.0

**Terraform Version & Provider Versions**

`terraform version`
```
Terraform v1.3.7
```

`terraform providers`
```
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v4.44.0
+ provider registry.terraform.io/hashicorp/local v2.2.3
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/time v0.9.1
```

**Bug Description**
All CloudWatch Logs **LogGroups** created by the AFT system have **no expiration** set (lambda, codebuild, etc.
I know that those log groups are automatically created by the resources, but this could be avoided creating them before (as usual for lambdas for example).

**To Reproduce**
Just look at the CloudWatch Logs console.
![Screenshot from 2023-01-08 17-56-36](https://user-images.githubusercontent.com/1442700/211210084-2e038626-ca04-4e5d-a520-3c0b3fc3d2f6.png)

**Expected behavior**
A reasonable expiration period should be set.

**Comment by adam-daily** [comment]
Hey Emiliano, thanks for reaching out. I'll create a backlog item for the team to have a look at this.

**Comment by stumins** [comment]
Hi @drAlberT,

The CloudWatch log retention period can be defined by configuring the [cloudwatch_log_group_retention parameter](https://github.com/aws-ia/terraform-aws-control_tower_account_factory#input_cloudwatch_log_group_retention) when deploying AFT.

Please let us know if the existing parameter doesn't meet your use case.

**Comment by drAlberT** [comment]
I have to admit that I have missed this, sorry.

Anyway, the description states it controls only the lambda related groups
and, if I'm not wrong again, there should be a few other log groups in use.

I will check asap and let you know. Thanks for your help!

**Comment by drAlberT** [comment]
Hi @stumins,
  I can confirm that the parameter fixes my issue and acts both on lambda and codecommit log groups.

Anyway, it looks like there are still 2 log groups not being affected. See the screenshot.

Thanks
![Screenshot from 2023-01-25 09-44-07](https://user-images.githubusercontent.com/1442700/214518193-1c2ac41a-bc6a-46d9-87bc-d09fffb53a4f.png)

**Comment by stumins** [comment]
Thanks for letting us know @drAlberT - I've created a backlog item to control the retention period of those log groups with the same parameter.

**Comment by drAlberT** [comment]
Perfect, thank you!

**Comment by roynesholen** [comment]
Hi
Today i upgrade our sandbox env to AFT  release 1.12.0 from 1.11.1
variable "aft_cloudwatch_log_group_retention" {
  type        = string
  description = "Amount of days to keep CloudWatch Log Groups for Lambda functions created by AFT"
  default     = "90"
}
cloudwatch_log_group_retention = var.aft_cloudwatch_log_group_retention

Before the upgrade we had 2 weeks retension for CW loggroup except /aws/lambda and python-layer-b*
See the picture that still has nexer expire and one aws lambda with the old 2 weeks
![screencloudwatch](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/assets/126559066/fbf9befc-f550-4cd9-8493-02dfb99322fa)

**Comment by roynesholen** [comment]
About my comments above. We have checked and all this log groups never expire is not used anymore, and one of this was our internal log group also.
So the AFT release 1.12.0 with retension works nice :)

**Comment by meraj-kashi** [comment]
More details about the last comment: 
`python-layer-builder-aft-common-xxx` and `python-layer-builder-aft-common-yyyy` are log groups assigned to AWS CodeBuild project called` python-layer-builder-aft-common-xxx `which come from [AFT project](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/main/modules/aft-lambda-layer/codebuild.tf). Based on the changes in the new release 1.12.0, Terraform creates new Log group called: `/aws/codebuild/python-layer-builder-aft-common-xxx` with the correct retention policy: [Release: 1.12.0 · aws-ia/terraform-aws-control_tower_account_factory@ac0facd](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/commit/ac0facd5911e865cfe9d855c1851aff464cbd8b5#diff-a823e4a680a5d81e698eed506aea2334075242abed56fe4ff6a4f7d2517e4815). So, these two log groups are old one and no new log will be stored there. 

`/aws/lambda/aft-lambda-layer-codebuild-invoker`: This CW log group belonged to Lambda function called `aft-lambda-layer-codebuild-invoker`, ref to code: https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/main/modules/aft-lambda-layer/lambda.tf#L6 . In the new AFT release 1.12.0, to support CW log creation for the Lambda function, the Lambda function was renamed to `aft-lambda-layer-codebuild-trigger` to avoid the Terraform resource creation problem. So, the old `/aws/lambda/aft-lambda-layer-codebuild-invoker `log group is not used anymore and can be deleted.
