### ISSUE TITLE
StartPipelineExecution API throttled when executing large number of customization pipelines concurrently

### ISSUE THREAD

**Issue by addefisher** [aws-ia/terraform-aws-control_tower_account_factory#297]
**Terraform Version & Prov:**

**AFT Version:**
1.6.2

**Bug Description**
When running the `aft-invoke-customizations` step function with AFT's `maximum_concurrent_customizations` setting at `25`, the `aft-customizations-execute-pipeline` lambda function fails with the following error: 

`An error occurred (ThrottlingException) when calling the StartPipelineExecution operation (reached max retries: 4): Rate exceeded`

Based on the error above, the `codepipeline:StartPipelineExecution` API call is being throttled. It looks like this is a current limitation in the `aft-customizations-execute-pipeline` lambda function `aft-invoke-customizations` step function since the step function does not implement any retry logic in https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/dc3eb7ce8ceb6e71d935431b164805b9facf270d/modules/aft-customizations/states/invoke_customizations.asl.json#L75, the lambda function uses a CodePipeline client object configured with the default number of retries (4), and the lambda function does not sleep between calls to `start_pipeline_execution()`.

**Expected behavior**
The lambda function executes successfully.

**Related Logs**
`{
  "Error": "ClientError",
  "Cause": "{\"errorMessage\": \"An error occurred (ThrottlingException) when calling the StartPipelineExecution operation (reached max retries: 4): Rate exceeded\", \"errorType\": \"ClientError\", \"stackTrace\": [\"  File \\\"/var/task/aft_customizations_execute_pipeline.py\\\", line 34, in lambda_handler\\n    execute_pipeline(session, str(p))\\n\", \"  File \\\"/opt/python/lib/python3.8/site-packages/aft_common/customizations.py\\\", line 82, in execute_pipeline\\n    response = client.start_pipeline_execution(name=name)\\n\", \"  File \\\"/opt/python/lib/python3.8/site-packages/botocore/client.py\\\", line 415, in _api_call\\n    return self._make_api_call(operation_name, kwargs)\\n\", \"  File \\\"/opt/python/lib/python3.8/site-packages/botocore/client.py\\\", line 745, in _make_api_call\\n    raise error_class(parsed_response, operation_name)\\n\"]}"
}`

**Additional context**

**Comment by hanafya** [comment]
Hey @addefisher!

Can you upgrade to AFT release 1.7.0?  We added a change to help address network throttling errors that occurred during concurrent executions using the aft-invoke-customizations step function interface. 

Please see, https://github.com/aws-ia/terraform-aws-control_tower_account_factory/releases/tag/1.7.0

**Comment by stumins** [comment]
Recent releases of AFT include refactors that reduce the chance of throttling errors occurring.

I'm closing this ticket due to inactivity - however, please feel free to open a new issue if you continue to experience issues after upgrading to the most recent version of AFT.
