### ISSUE TITLE
plan after initial deployment detects drift

### ISSUE THREAD

**Issue by danno-rose** [aws-ia/terraform-aws-control_tower_account_factory#3]
Just deployed from main... initial deployment fine.. a new plan shows the a drift detection, despite doing nothing at all... The strange thing is that actually the drift is "non-existent" 
These are the 3 resources with drift detected
-  module.aft.module.aft_lambda_layer.aws_iam_role.codebuild
-  resource "aws_kms_key" "aft_log_key"
- resource "aws_s3_bucket_policy" "aft_logging_bucket" 

all the "drifts" are policy objects where one of the principals has been replaced by another (of the same name) e.g. 
```
~ Principal = {
                      ~ Service = [
                            - "cloudtrail.amazonaws.com",
                               "delivery.logs.amazonaws.com",
                             + "cloudtrail.amazonaws.com",
                               "vpc-flow-logs.amazonaws.com",
                            ]
                        }
```
running : ```terraform apply -refresh-only```

doesn't fix the issue.. we see that one or more of the policies remains in "drift" state..

**Comment by lorengordon** [comment]
Fairly certain this is an issue in the aws provider. They have a new tracking issue, summarizing all the reported issues...

* https://github.com/hashicorp/terraform-provider-aws/issues/21968

**Comment by danno-rose** [comment]
agreed.. will close this as an issue for this project

**Comment by YakDriver** [comment]
Just a note that we have a handle on the part of the problem that you mention here: nonexistent drift detections (i.e., perpetual diffs). Once we roll out the fixes that are in progress, that part should be good. However, the other part is valid out-of-band changes causing much larger diffs than they should. The extra layer of JSON wrapping seems to be causing problems there as well.
