### ISSUE TITLE
lambda aft-enable-cloudtrail fails

### ISSUE THREAD

**Issue by androidwiltron** [aws-ia/terraform-aws-control_tower_account_factory#30]
aft version: 1.0.11
feature flag: `aft_feature_cloudtrail_data_events = true`

after the first new account is provisioned and enrolled in controltower the step function `aft-feature-options` fails at `Enable Cloudtrail`.
the lambda it invokes (`aft-enable-cloudtrail`) throws an error:

```
[ERROR] TrailNotFoundException: An error occurred (TrailNotFoundException) when calling the GetTrail operation: Unknown trail: aws-aft-CustomizationsCloudTrail for the user: xxxxxxxxxxx
Traceback (most recent call last):
  File "/var/task/aft_enable_cloudtrail.py", line 130, in lambda_handler
    if not trail_exists(ct_session):
  File "/var/task/aft_enable_cloudtrail.py", line 16, in trail_exists
    response = client.get_trail(Name=CLOUDTRAIL_TRAIL_NAME)
  File "/opt/python/lib/python3.8/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/python/lib/python3.8/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
```

i believe this should throw an exception that is gracefully caught in the lambda python code. you can see in the code a conditional for this cloudtail being created. as it stands in version 1.0.11 if the cloudtrail trail doesnt exist the boto3 request error isnt caught and it just fails:
https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/d347c43d90a048b68184b9f29e2e448ff6c8561e/modules/aft-feature-options/lambda/aft-enable-cloudtrail/aft_enable_cloudtrail.py#L16

you can see in an earlier version of AFT this was actually being handled correctly:
https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/ae35712fdef0ca38cfe9dca34d708f5e9040fcf0/modules/aft-feature-options/lambda/aft-enable-cloudtrail/lambda_function.py#L13-L20

So currently i dont think this functionality for enabling cloudtrail data events will work, correct me if im wrong?

**Comment by androidwiltron** [comment]
to mitigate this you need to disable cloudtrail data events feature flag in the AFT terraform
```
# Feature Flags
aft_feature_cloudtrail_data_events = false
```

**Comment by balltrev** [comment]
Hey @androidwiltron, I'm taking a quick look into this, but in the mean time, do you know if within your Control Tower management account, under Organizations, that you have Access Enabled for the CloudTrail service?

**Comment by androidwiltron** [comment]
CloudTrail - Access Disabled

@balltrev is this somthing that needs enabling - not sure i spotted this in the docs?

**Comment by balltrev** [comment]
I believe it is a prerequisite for the feature option, I'll see if I can't find a documentation link for you.

We did confirm that regression you pointed out and are working on deploying the fix now, thanks for the catch!

**Comment by balltrev** [comment]
https://docs.aws.amazon.com/controltower/latest/userguide/aft-feature-options.html

```
Prerequisite

Before you enable this feature option, be sure that trusted access for AWS CloudTrail is enabled in your organization.

To check the status of trusted access for CloudTrail :

    Navigate to the AWS Organizations console.

    Choose Services > CloudTrail.

    Then select Enable trusted access in the upper right, if needed.

```

**Comment by androidwiltron** [comment]
Thanks for the docs.
Creeping out of scope for this issue a little but I feel that is somthing that could be done in the AFT module itself:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/config_organization_managed_rule

Just a suggestion.

**Comment by balltrev** [comment]
That's a pretty good call out, though I agree it's a little out of scope here so I went ahead and made a backlog for that enhancement.

**Comment by hanafya** [comment]
Hey! We just pushed a fix for this issue - https://github.com/aws-ia/terraform-aws-control_tower_account_factory/releases/tag/1.0.12
