### ISSUE TITLE
Support for new behavior for IAM role trust policy behavior

### ISSUE THREAD

**Issue by cornelllawrence** [aws-ia/terraform-aws-control_tower_account_factory#309]
**Describe the outcome you'd like**

The IAM roles created by this project should comply with the new [IAM role trust policy behavior](https://aws.amazon.com/blogs/security/announcing-an-update-to-iam-role-trust-policy-behavior/).

**Is your feature request related to a problem you are currently experiencing? If so, please describe.**

Currently, we have an event notification in our AFT-Management account that states the `AFTAWSExecution` role didn't comply with the new behavior

**Additional context**

**Comment by stumins** [comment]
Hi @cornelllawrence, 

Thanks for opening this issue. We don't have any notifications related to this change in our internal accounts, and I don't believe that AFT will be impacted by the trust policy changes as the AFT roles do not attempt to assume themselves as part of standard operation.

Can you provide additional details about the notice you received?

**Comment by cornelllawrence** [comment]
@stumins we received this notice regarding the AWSAFTExecution role in our management account:

> AWS IAM is changing an aspect of how role trust policy evaluation behaves when a role assumes itself.
Beginning September 21, 2022, a role trust policy must explicitly grant permission to the principals, including the role itself, that need to assume it under the specified conditions. This change improves consistency with how other AWS resource policies behave and increases visibility into role assumption behavior.
You should have seen no immediate impact due to the change, because these roles have been allow-listed to continue to behave as before. You may continue to use your existing configuration for the roles listed previously until February 15, 2023. We are allowing time for you to make any necessary changes to existing processes, code, or configuration in preparation for enforcement of an explicit permission grant in the role trust policy. If maintaining the existing behavior of your code is important for your use case, a role can continue to assume itself after February 15, 2023, by updating its role trust policy to explicitly trust the role itself.
We are contacting you because our data suggests that your AWS account may have one or more IAM Roles that assumes itself based on the permissions and conditions in its identity-based policy without explicitly granted permission in its role trust policy. [...]
After February 15, 2023, all roles that attempt to assume themselves will fail with an access denied error, unless the role trust policy explicitly grants the permission and the conditions and actions are satisfied.
Additional guidance and details: https://aws.amazon.com/blogs/security/announcing-an-update-to-iam-role-trust-policy-behavior/.

**Comment by cornelllawrence** [comment]
@stumins I manually fixed the role it was complaining about so I don't have the notification any longer.  Also, this only occurred in our development AFT setup and not the production setup.  Seems as if the behavior isn't consistent.

**Comment by stumins** [comment]
@cornelllawrence Thanks for the prompt response. As we don't expect any impact from this IAM change, I'm going to close this issue. However, if you do experience issues in your development setup after the June 30th cutoff date, please open a new issue and we will investigate further.
