### ISSUE TITLE
Provision existing AWS account

### ISSUE THREAD

**Issue by stefanolczak** [aws-ia/terraform-aws-control_tower_account_factory#31]
I'm considering using AFT to apply customizations to existing AWS accounts that are not even registered in Control Tower. I know that I can enroll existing account to Control Tower but it looks like provisioning existing AWS account to AFT is not officially supported.

I made a research and few tests and it appears that it can be done quite easy:

1. Create account request file and put email address of existing account into AccountEmail parameter.
2. Wait until lambda function `aft-account-request-processor` fails with an error that email is not valid ( because it is used by existing account ). By analyzing code of the mentioned lambda function it appears that the check is done just before the creation of new account which is basically ProvisionProduct API call to Service Catalog. Also creation request is not removed from DynamoDB tables in case of mentioned failure. That gave me an idea to try to enroll the AWS account in Control Tower manually in AWS console because I knew it works for emails of existing AWS accounts also. I was also aware of a fact that enrolling AWS account that way uses the mentioned API.
3. Enroll AWS account in Control Tower. After successful registration it will generate lifecycle event `CreateManagedAccount` which is the event that AFT is waiting for to continue.
4. Process of provisioning AWS account in AFT is resumed and finally the AWS account is marked as AFT provisioned. During the provisioning process the customizations are applied to existing AWS account. It's also possible to re-invoke the customizations as documented here: https://docs.aws.amazon.com/controltower/latest/userguide/aft-account-customization-options.html#aft-re-invoke-customizations.  This is what I wanted to achieve.

Please review this approach and comment is it safe to do it that way. Also it would be nice to know if there are any plans to officially support provisioning of existing AWS account anytime soon.

**Comment by balltrev** [comment]
Hey @stefanolczak I think https://github.com/aws-ia/terraform-aws-control_tower_account_factory/releases/tag/1.2.0 addresses part of your request, as long as you enroll the accounts in question in your Control Tower environment first.

**Comment by stefanolczak** [comment]
Hey @balltrev I tested the release by updating AFT to 1.2.1 but unfortunately adding existing accounts still doesn't work. The process is stopped here again:

https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/29061714a0aa1c9cebaf14d6a57dc9d8cba8d7e8/modules/aft-account-request-framework/lambda/aft-account-request-processor/aft_account_request_processor.py#L46-L49

I think the above code should be somehow changed to support adding existing accounts fully.

**Comment by balltrev** [comment]
Hey @stefanolczak, can you verify this account is listed in your AWS Organizations? Reading through the logic there, it seems the processor determined the email for the account you're trying to ingest wasn't part of Orgs at the time it ran.

**Comment by stefanolczak** [comment]
Yes the account is part of my organization and that's the problem because the code proceed with accounts that aren't part of the organization only. You can see it here:

https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/29061714a0aa1c9cebaf14d6a57dc9d8cba8d7e8/modules/aft-account-request-framework/lambda/aft-account-request-processor/aft_account_request_processor.py#L27-L34

As you can see the "if statement" in line 33 marks the account as valid only when it's not in the **org_account_emails** list which is basically a list of all accounts in the organization.

**Comment by balltrev** [comment]
Ah, my misunderstanding! I believe this is actually a bug we're actively working on and fixed in our next release. 

It shouldn't be going down this code path, as it's a modify/update behavior, as opposed to a new account request.

**Comment by lukas-hetzenecker** [comment]
Thanks for the update @balltrev

We have upgraded our environment to AFT 1.3.1 and tested the enrolment of existing accounts into AFT, but unfortunately are also not successful using this release.

You mentioned that pre-existing Control Tower accounts (what we were trying to import) should trigger the modify/update codepath.

After enrolling the OU to CT, provisioned products got added to the Service catalog with the name `Enroll-Account-<AccountID>`. 
Here seems to be the issue - AFT expects [the name of the product to be the same as the account name](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/1.3.1/sources/aft-lambda-layer/aft_common/account.py#L35), which is not the case for imported Control Tower accounts. 

As this check fails, it still follows the _new_ account request code path, following with the "_Requested AccountEmail is NOT valid_" error message again.

**Comment by balltrev** [comment]
Ah, that's exactly right. We'll need to expand the logic to include enrolled accounts. Once we get this knocked out we'll drop an update with the new release including the fix here

**Comment by balltrev** [comment]
@PeterBengtson , I went ahead and moved your issue into it's own thread to better dig into your issue there.

**Comment by fjromerom** [comment]
+1 on this. I'm having issues to incorporate accounts that were not provisioned by AFT and the name was changed.

**Comment by PeterBengtson** [comment]
AFT does not assist you with changing the email or the account name, so maybe this isn't too surprising. It's unclear to me at this point whether it's possible to specify other values for the three SSO data fields, or if these fields _have_ to have exactly the same value they did when creating the account.

But email and account name must, as far as I know, be consistent with the values they had at account creation time.

**Comment by fjromerom** [comment]
I probably didn't explain all the context.

It's right Account Settings can't be changed in AFT. Prior to include the accounts in AFT, I changed the account name and email within Account Settings within each account. Then, I added the account in AFT and it failed creating the CodePipeline pipeline.

**Comment by PeterBengtson** [comment]
The same thing seems to happen with the CT-specific accounts such as Log Archive and Audit. These two when imported to AFT never get any pipelines.

**Comment by balltrev** [comment]
We're actively working on a better implementation that makes less assumptions about the account that's being ingested and the provisioned product that exists for that account. It should make this process less delicate going forward

**Comment by stefanolczak** [comment]
I tested the 1.3.3 release with provisioning existing AWS account and it works well.

**Comment by balltrev** [comment]
Great to hear @stefanolczak, I'll go ahead and close this issue then.

**Comment by stefanolczak** [comment]
@balltrev today I tried to provision existing AWS account on AFT 1.3.5 and unfortunately it didn't work.
The `aft-account-request-processor` triggered and failed with errors like this:
```
Invalid Request - AccountEmail already exists in Organization: 
CT Request is not valid
```
Is it possible that changes in versions 1.3.4-1.3.5 broke the support in any way ? I wanted to return to 1.3.3 to make another test but I can see 1.3.5 is required now because of hotfix.

**Comment by stefanolczak** [comment]
I downgraded to 1.3.3 ( with 1.3.5 backported ) and I encountered the same issue again. Then I realized that I can provision only existing accounts that exist in "provisioned products" in Service Catalog. That means I can't provision audit, log-archive and management account into AFT and that was the case I wanted to achieve today. So the question is: can we have support for provisioning those accounts too?

**Comment by balltrev** [comment]
Hey @stefanolczak, we're actually [still investigating](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/issues/119) how to best support management of "core" accounts within Control Tower, but it's a high priority for the team.

**Comment by paulpog-checkit** [comment]
I'm running AFT 1.3.5 and get the same
`Invalid Request - AccountEmail already exists in Organization: 
CT Request is not valid`
error as @stefanolczak. However, I don't understand his comment than the only way to avoid this error is to have the account(s) defined as a "provisioned product" in the Service Catalog?
This is not a requirement to manually enrol an existing account with the Account Factory in the UI, so why is it a requirement for AFT, and how is this achieved?

**Comment by stumins** [comment]
Removing bug label - this is the primary tracking ticket for the enhancement request for shared account support.

**Comment by balltrev** [comment]
We've just released [1.4.0](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/releases/tag/1.4.0), you can now specify your shared/management accounts in your account request repository allowing you to manage your shared/management accounts with AFT

**Comment by jodgey** [comment]
Does this mean that we can also manage our AFT-Management account with AFT? I would like AFT to add customizations for our AFT-Management account.

**Comment by balltrev** [comment]
@jodgey it does. AFT Management is treated as a member account in your Control Tower environment. As long as you provide the proper values for the account request, you should be able to customize the AFT Management account as well

**Comment by balltrev** [comment]
Going to go ahead and close this issue in favor of the 1.4.0 release

**Comment by joshua-perakis-scf** [comment]
To my knowledge, AFT uses the control_tower_parameters to import accounts into AFT management. I wanted to import the log archive/audit accounts into management but am unsure what values to use for the SSOUSER* control_tower_parameters. What values should I use or where can I locate those values?

**Comment by nronnei** [comment]
@joshua-perakis-scf did you ever figure that out? I'm looking to do the same.

**Comment by nronnei** [comment]
For anyone else who lands here, I succeeded in this by leaving `SSOUser*` params equal to `""`. Note: even though the `Security` OU (or whatever yours may be called) is nested under Root, it's NOT considered a Nested OU by AFT. So don't include it's ID when specifying it.

```
  control_tower_parameters = {
    AccountEmail = "<ACCOUNT_EMAIL>"
    AccountName  = "<ACCOUNT_NAME>"
    # Don't specify OU ID unless it's a nested OU
    ManagedOrganizationalUnit = "Security"
    SSOUserEmail     = ""
    SSOUserFirstName = ""
    SSOUserLastName  = ""
  }
```
