### ISSUE TITLE
aft-account-request CodeBuild failure - incorrect ARN

### ISSUE THREAD

**Issue by naamancampbell** [aws-ia/terraform-aws-control_tower_account_factory#311]
**Terraform Version & Prov:**

**AFT Version:**
1.8.0

**Terraform Version & Provider Versions**
Please provide the outputs of `terraform version` and `terraform providers` from within your AFT environment

`terraform version`
```
Terraform v0.15.5
```

`terraform providers`
```
hashicorp/aws v4.54.0
```

**Bug Description**
In `aft-account-request` CodeBuild buildspec, the `AFT_ADMIN_ROLE_ARN` variable expands to an incorrect ARN:
`arn:aws:iam::602979550473ole/AWSAFTAdmin`

The incorrect ARN causes the build to fail with an exit code 1 (at the `terraform init -no-color` line).

**To Reproduce**
1. Push to the aft-account-request repo
2. Monitor CodeBuild for failure

**Expected behavior**
Successful CodeBuild build.

**Suggested Fix**
Add quotes and braces around variables for the role variables:
```bash
      - AFT_EXEC_ROLE_ARN="arn:${AWS_PARTITION}:iam::${AFT_MGMT_ACCOUNT}:role/AWSAFTExecution"
      - AFT_ADMIN_ROLE_ARN="arn:${AWS_PARTITION}:iam::${AFT_MGMT_ACCOUNT}:role/${AFT_ADMIN_ROLE_NAME}"
```

**Additional context**
```hcl
terraform_distribution = "oss"
vcs_provider           = "codecommit"
```

**Comment by stumins** [comment]
Hi @naamancampbell,

I'm not able to reproduce this issue and all internal tests are passing. Can you provide any additional details around how to reproduce this problem?

If this is causing active impact I recommend reaching out to AWS Premium Support for additional assistance.
