### ISSUE TITLE
AFT raises an error on unsupported but expected control tower events

### ISSUE THREAD

**Issue by CalvinRodo** [aws-ia/terraform-aws-control_tower_account_factory#312]
**AFT Version:** 1.7.0

This method throws an error when a non-supported issue is passed to the handler: 
https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/main/src/aft_lambda/aft_account_request_framework/aft_invoke_aft_account_provisioning_framework.py#L46-L86

This posts an event to the aft-failure-notifications sns topic, which I subscribe to and post to slack cuz I want to know when an AFT customization fails. 

However due to the above code control tower events when you do something like update guardrails, or upgrade control tower also get posted to that topic so then I get an alert per AFT managed account. 

I'm not sure these events should be errors since they are expected just not handled by AFT. 

Would be nice if you just wrote to the log instead of raising an error as it makes the aft-failure-notifications topic pretty unusable for alerting.

Related to # https://github.com/aws-ia/terraform-aws-control_tower_account_factory/issues/308

**Comment by balltrev** [comment]
Hey @CalvinRodo AFT version 1.9.0 has just been released and now only listens to the "CreateManagedAccount" and "UpdateManagedAccount" events to reduce the noise you've mentioned.

**Comment by CalvinRodo** [comment]
@balltrev That's awesome, since I'm on 1.7.0 is it worth it to upgrade to 1.8.0 first or can I got straight to 1.9.0?

**Comment by balltrev** [comment]
@CalvinRodo, We've no requirement that you update to each minor version in succession, you should be good to go straight to 1.9.0!
