### ISSUE TITLE
Fails to create a customization pipeline for Org management AWS account 

### ISSUE THREAD

**Issue by kyrylo-hulak** [aws-ia/terraform-aws-control_tower_account_factory#314]
**Terraform Version & Prov:**
1.0.11
**AFT Version:**
1.8.0

**Bug Description**
After adding Core AWS Accounts along with Org management account to AFT solution. There were observed created corresponding DynamoDB records in `account-request table`. Though, not all customization pipelines was created. All except for Org management AWS account.

**Expected behavior**
After being CT Core Accounts along with Org management accounts registered with AFT There should be corresponding customization pipelines created.

**Related Logs**
There was made an attempt to manually trigger creation a customization pipeline for Org management account with a step function `aft-invoke-customizations` without success. It threw out an error below
``` json
"Cause": "An error occurred while executing the state 'run_create_pipeline?' (entered at the event id #34). Invalid path '$.Input.account_provisioning.run_create_pipeline': The choice state's condition path references an invalid value.",
  "Error": "States.Runtime"
```

**Additional context**
I have tried to search through docs and existing issues registered but didn't find anything that would help me to resolve the issue.
I would appreciate any advice on that?
thank you!

**Comment by stumins** [comment]
Hi @kyrylo-hulak,

You may find more information about why the Organization management account request failed in the `aft-request-action-trigger` and `aft-request-processor` CloudWatch log groups. If you find any errors in the logs, please post them here for additional troubleshooting.

If you don't see any obvious errors in those logs, I recommend reaching out to AWS Premium Support for more in-depth support.

**Comment by kyrylo-hulak** [comment]
Hello @stumins, thank you for your response!
I have made additional investigation of states functions and logs provided there at certain steps. So, I have an extended configuration of account provisioning framework repo to update an alternate contacts in AWS accounts. It's done as it provided in one of the AWS workshop for Control Tower. There exists a state function called `aft_alternate_contacts`.
It inspects `custom_fileds` on the subject if there is `alternate_contacts` provided. If so, it triggers lambda functions to validate contacts and finally applyiing a change to the target/vended AWS account. It's done with help of boto3. And, what I have found out is it will work fine with member Org accounts but not with management Org account. Due to 
`
Note

The management account can't specify its own AccountId ; it must call the operation in standalone context by not including the AccountId parameter.
`
which is not met and failed to pass that state function and fails other in the chain. Therefore, it's not getting a stage to create a pipeline for Management Org Aws account.

**Comment by kyrylo-hulak** [comment]
The error that I found in the `aft-alternate-contacts` is provided below
```
"errorMessage": "An error occurred (AccessDeniedException) when calling the PutAlternateContact operation: User: arn:aws:sts::**aft-account-id**:assumed-role/aft-alternate-contacts-add-lambda-role/aft-alternate-contacts-add is not authorized to perform: account:PutAlternateContact",
  "errorType": "AccessDeniedException",
  "requestId": "23da6855-472c-4f79-af1a-c220c1f82db1",
  "stackTrace": [
    "  File \"/var/task/add-alternate-contacts.py\", line 90, in lambda_handler\n    update_status = update_alternate_contact(account_id, payload[\"alternate_contact\"])\n",
    "  File \"/var/task/add-alternate-contacts.py\", line 64, in update_alternate_contact\n    account_response = account_client.put_alternate_contact(\n",
    "  File \"/var/runtime/botocore/client.py\", line 391, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n",
    "  File \"/var/runtime/botocore/client.py\", line 719, in _make_api_call\n    raise error_class(parsed_response, operation_name)\n"
  ]
}
```
So, it made me first to sort the `AccessDeniedException` but when I went to IAM role used by lambda it seems to have needed permissions. You may see them below:

```
{
            "Action": [
                "account:PutAlternateContact"
            ],
            "Resource": [
                "arn:aws:account::**management-account-id**:account/o-xzldbjhss5/*"
            ],
            "Effect": "Allow",
            "Sid": "AccountOperations"
        }
```
But it keeps failing. Then I turn to py errored lines in the scripts mentioned in the error log above. I believe, this is where it should be adjusted to make it work.

**Comment by kyrylo-hulak** [comment]
there was logged an additional request with AWS Premium support

**Comment by stumins** [comment]
Hi @kyrylo-hulak,

Unfortunately, we can't provide support for code outside the standard AFT code base - please continue to work with AWS Premium Support or reach out to the team who facilitated the workshop for further assistance.

It doesn't seem like there is an issue with core AFT, so I'm going to go ahead and close this issue now.

**Comment by wellsiau-aws** [comment]
tagged this issue on the AFT workshop repo: https://github.com/aws-samples/aft-workshop-sample/issues/5
