### ISSUE TITLE
Enroll support Throttled on DescribeCases operation

### ISSUE THREAD

**Issue by sl-ediquas** [aws-ia/terraform-aws-control_tower_account_factory#317]
Still present in version 1.9.0

Error when running customizations on approximatively 145 accounts, located on aft_enroll_support.py.
Causong the following issue:
*{"errorMessage": "An error occurred (ThrottlingException) when calling the DescribeCases operation (reached max retries: 4): Throttle limit exceeded.", "errorType": "ClientError", "stackTrace": ["  File \"/var/task/aft_enroll_support.py\", line 36, in lambda_handler\n    if not account_enrollment_requested(ct_mgmt_session, target_account_id):\n"*

I've managed to make it work with the following:

#### aft_enroll_support.py

line 36

Original code

```
if not account_enrollment_requested(ct_mgmt_session, target_account_id):
    generate_case(ct_mgmt_session, target_account_id)
```

Proposal for workaround:

```
requested = None
while requested is None:
    try:
        requested =  account_enrollment_requested(ct_mgmt_session, target_account_id)
    except:
        pass
if not requested:
    generate_case(ct_mgmt_session, target_account_id)
```

**Comment by stumins** [comment]
Hi @sl-ediquas,

Thank you for the report. We're aware of the issue and have a backlog ticket to address it.

**Comment by iwt-pjost** [comment]
Any news on this? With this bug we can't really roll out anything on our accounts because it fails the moment we target more than 15 accounts. Which, to be honest, is quite the small number.

**Comment by shashanklmurthy** [comment]
+1 . Any updates here -  we're hitting this issue as well and we have a large pool of accounts to roll changes out to.

**Comment by cianscolard-gp** [comment]
Hi @stumins, any chance this has progressed at all? This is a painful one for us.

**Comment by stumins** [comment]
Hi all - 

[AFT 1.10.4](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/releases/tag/1.10.4) was released last month with improved retry behavior to address these types of throttling issue, including for the Support API referenced in this issue.

Please upgrade to 1.10.4 and let us know if you continue to experience any throttling exceptions.
