### ISSUE TITLE
AFT 1.9.0 fails to ingest existing CT-managed accounts

### ISSUE THREAD

**Issue by stumins** [aws-ia/terraform-aws-control_tower_account_factory#319]
The workflow documented [here](https://docs.aws.amazon.com/controltower/latest/userguide/aft-update-account.html) seems to have been broken in 1.9.0.

When importing an account not provisioned by AFT, the [account request trigger lambda](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/1.9.0/src/aft_lambda/aft_account_request_framework/aft_account_request_action_trigger.py) now fails with "Unsupported account request" because the imported account does not match any of the if branches.

_Originally posted by @lawliet89 in https://github.com/aws-ia/terraform-aws-control_tower_account_factory/issues/207#issuecomment-1450107483_

**Comment by stumins** [comment]
[AFT 1.9.1](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/releases/tag/1.9.1) has been released with a fix for this issue.

**Comment by lawliet89** [comment]
Thank you for the quick turnaround!

**Comment by awsml-axiamed** [comment]
Thanks Stuart!!
