### ISSUE TITLE
Do not detect drift in changes.

### ISSUE THREAD

**Issue by Anorlondo448** [aws-ia/terraform-aws-control_tower_account_factory#32]
Manually changed the OU from the AWS console for the AWS account created using the aft-account-request module.
The pipeline was rerun, and no change was detected, resulting in no change.

resources.instances.attributes.item

 "control_tower_parameters.ManagedOrganizationalUnit” (In “resources.instances.attributes.item”) is drifting with the value of the AWS resource.

**Comment by balltrev** [comment]
Feel free to reopen this issue if you're still working through this, but I'm going to go ahead and close it as I think @adam-daily summed up why the behavior here is expected for the time being.
