### ISSUE TITLE
Terraform modules private repositories

### ISSUE THREAD

**Issue by ahmedfourti** [aws-ia/terraform-aws-control_tower_account_factory#327]
**Describe the outcome you'd like**

On my terraform code I need to fetch modules from private repo (Gitlab and CodeCommit)

**Is your feature request related to a problem you are currently experiencing? If so, please describe.**

I can't find any documentation or example on how to make this working with CodeCommit or Gitlab

**Additional context**

I found some discussion here #42 but still the documentation doesn't exist...

**Comment by snebhu3** [comment]
@ahmedfourti thank you for reaching out.
Please track this request in [Issue 215](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/issues/215)
