### ISSUE TITLE
Lambda aft-account-request-processor fails to create a new account

### ISSUE THREAD

**Issue by anunezlo** [aws-ia/terraform-aws-control_tower_account_factory#33]
Hi!

When trying to create a new account using aft, the lambda _aft-account-request-processor_ fails to create the new account with the error:

```
{
    "time_stamp": "2022-01-18 16:11:23,200",
    "log_level": "ERROR",
    "log_message": {
        "FILE": "aft_account_request_processor.py",
        "METHOD": "lambda_handler",
        "EXCEPTION": "An error occurred (ResourceNotFoundException) when calling the ProvisionProduct operation: No launch paths found for resource: prod-emcidcalm2e2s"
    }
}
Traceback (most recent call last):
  File "/var/task/aft_account_request_processor.py", line 209, in lambda_handler
    response = create_new_account(
  File "/var/task/aft_account_request_processor.py", line 87, in create_new_account
    response = client.provision_product(
  File "/opt/python/lib/python3.8/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/python/lib/python3.8/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the ProvisionProduct operation: No launch paths found for resource: prod-emcidcalm2e2s
```

After spending some time I solved the problem by adding the role arn:aws:iam::xxxx:role/AWSAFTExecution to the AWS Control Tower Account Factory Portfolio in my Control Tower Management Account. If this is the right solution, then it would be nice to add it to the documentation.

By the way, thank you for this powerful tool!

**Comment by adam-daily** [comment]
Hi Angel, thanks for the reach out and glad you're finding AFT useful! You can find the post-deployment prerequisite you mentioned in the [post-deployment steps here in the docs](https://docs.aws.amazon.com/controltower/latest/userguide/aft-post-deployment.html). I'm going to go ahead and close this issue for the time being, but if I've missed a detail here about the behavior you've brought up, feel free to reopen and I can investigate further.
