### ISSUE TITLE
Update Terraform Version

### ISSUE THREAD

**Issue by raben0** [aws-ia/terraform-aws-control_tower_account_factory#335]
**Terraform Version & Prov:**

**AFT Version:**
1.7.0

**Terraform Version & Provider Versions**
Please provide the outputs of `terraform version` and `terraform providers` from within your AFT environment

`terraform version`
```
v0.15.5
```

`terraform providers`
```
+ create
```

**Bug Description**
I would like to update the terraform version being used by CodeBuild to the newest version. The version it is using now is the version v0.15.5. How do I do it? Do I need to change anything directly to AWS, update the value of the variable /aft/config/terraform/version do the trick, or there is a way to do it via .tf?

**Comment by v-rosa** [comment]
You have a variable in the aft module which allow to change it.

**Comment by raben0** [comment]
If I change it there it will start to use this version instead? No need for more settings?

**Comment by v-rosa** [comment]
Yep but better to take a look by yourself, https://github.com/search?q=repo%3Aaws-ia%2Fterraform-aws-control_tower_account_factory+terraform_version&type=code

**Comment by snebhu3** [comment]
@raben0 thank you for reaching out. 
You can specify the Terraform version you want to use in your environment by setting the variable `terraform_version` during AFT deployment / AFT update.
