### ISSUE TITLE
Lambda's TooManyRequestsException when run "aft-invoke-customizations"

### ISSUE THREAD

**Issue by vaspoz** [aws-ia/terraform-aws-control_tower_account_factory#337]
**AFT Version:**
1.9.2

**Terraform Version & Provider Versions**
```
Terraform v1.4.2
on windows_386
+ provider registry.terraform.io/hashicorp/aws v4.61.0
```

**Bug Description**
The State machine throws **TooManyRequestsException** when starting with more than 10 accounts (maybe even less, didn't check what's the threashold, now I'm running in chunks of 5)

**To Reproduce**
1. Run the state machine with input:
```
{
  "include": [
    {
      "type": "all"
    }
  ]
}
```
2. Make sure that you have > 10 accounts.
3. The state machine fails in that stage:
![image](https://user-images.githubusercontent.com/4658186/230603646-6a1640f4-959c-411d-a72b-63aa5a69fb43.png)

If you open invoked **aft-account-provisioning-framework** state machine, you'll see this error:
![image](https://user-images.githubusercontent.com/4658186/230603818-73790900-2fe7-4512-a6ba-8f21794298b0.png)

**Expected behavior**
It's either should be documented somewhere or concurrency limit for the lambdas should be increased.

**Comment by hanafya** [comment]
Hey @vaspoz thanks for reaching out! I would recommend that you reach out to AWS Premium Support to help further deep dive the issue in your environment.
