### ISSUE TITLE
NEW: pass aft account request "custom_fields" metadata to customization pipeline

### ISSUE THREAD

**Issue by wellsiau-aws** [aws-ia/terraform-aws-control_tower_account_factory#34]
### Background:
* In the customization pipeline, I could use pre and post API helper to perform action such as populating the tfvars.
* Account request can contain additional metadata stored in custom_fields, this information propagate through the step function but is not available inside the CodeBuild environment

### Expected outcome:
I want to access these metadata, probably in format of environment variables when running the API helpers.
one way to achieve this is by adding this metadata as part of the CodeBuild environment variables and keep it up to date as I modify the account request.

**Comment by mathewmoon** [comment]
I achieve this by accessing $VENDED_ACCOUNT env var in a customizations pre api helper script then do a Dynamodb lookup into the account_request_metadata Dynamodb table. This gives me all of the data from the account request, including custom_fields. The script then dumps that to a JSON file and I have a locals.tf that reads that file into a local. Seems a little like going around the world, but it works.

**Comment by wellsiau-aws** [comment]
I agree that this approach and it was one of the first come to my mind. That said, it requires user to build this custom script. I was hoping for alternative mechanism that could deliver this custom_fields to the execution environment automatically.

**Comment by balltrev** [comment]
We're actually actively working on an implementation to get custom fields into vended accounts in a more consumable way from within the vended account itself to avoid some of this account/dynamo navigation required as it exists today.

**Comment by balltrev** [comment]
https://github.com/aws-ia/terraform-aws-control_tower_account_factory/releases/tag/1.1.0

This should allow for custom fields to be consumed in a simpler way within the vended account. Going to close out this issue for the time being, but feel free to reopen it if this doesn't quite accomplish what you were looking for, thanks!
