### ISSUE TITLE
Grouping aft-account-customization Resources in AFT: Tagging for Environment-based Configuration

### ISSUE THREAD

**Issue by emil2709** [aws-ia/terraform-aws-control_tower_account_factory#352]
**Describe the outcome you'd like**

I would like to request a new feature for the AFT (Account Fabricator Tool) that allows for environment-based grouping of resources within the `aft-account-customizations` folder. Currently, we can only group individual resources, but it would be immensely helpful to have the ability to organize resources based on different environments. Should there be a way to for example pass a list of strings, which can trigger the `aft-account-customizations` part of AFT? 
For exmaple:
`account_customizations_name = ["Networking", "Prod", "High-Sensitivity"]`
Maybe to even trigger the pipeline based on the OU that they are in - kinda like you do with controls in control tower.

**Is your feature request related to a problem you are currently experiencing? If so, please describe.**

Not a problem, but for customer that operate a large scale of accounts, this might make their life more stress free, and scaleable for customer with 50+ accounts.

**Additional context**

**Comment by balltrev** [comment]
Hey @emil2709 I believe [this example](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/tree/main/examples/multiple-account-customizations) should help you achieve what you're asking here. Feel free to let us know if it doesn't quite cover what you're looking for.

**Comment by emil2709** [comment]
Exactly what i was looking for! Thanks!
