### ISSUE TITLE
Buildspec not working with TFC

### ISSUE THREAD

**Issue by mrl045** [aws-ia/terraform-aws-control_tower_account_factory#356]
Terraform Cloud with 0.15.5

**AFT Version:**
1.10.3 with CodeDeploy VCS

tar: terraform: Cannot open: No such file or directory
--
tar: Error is not recoverable: exiting now

in file modules/aft-code-repositories/buildspecs/cf-aft-account-requests.yml

Should add the following build steps to make it work:

on line 68
          mkdir -p $DEFAULT_PATH/terraform
          mv *.tf *.jinja modules $DEFAULT_PATH/terraform

**Comment by balltrev** [comment]
Hey @mrl045, we're unable to reproduce this issue in our testing environments.

Can you confirm you've followed the [post-deployment steps](https://docs.aws.amazon.com/controltower/latest/userguide/aft-post-deployment.html)? If you have and are still experiencing issues, I recommend reaching out to AWS Premium Support to better deep dive your deployment to understand what may be causing the issue for you.

**Comment by mrl045** [comment]
Hi @balltrev, I've followed the post-deployment steps. The four repositories are created by the Terraform module. 

module "control_tower_account_factory" {
  source  = "aws-ia/control_tower_account_factory/aws"
  version = "1.10.3"
  # Account Setup
  aft_management_account_id   = "x"
  audit_account_id            = "x"
  log_archive_account_id      = "x"
  ct_management_account_id    = "x"
  ct_home_region              = "eu-central-1"
  tf_backend_secondary_region = "eu-west-1"

  # Optional Parameters
  terraform_distribution = "tfc"
  vcs_provider           = "codecommit"
  terraform_org_name     = "x"
  terraform_token        = "x"

  # Optional Feature Flags
  aft_feature_delete_default_vpcs_enabled = true
  aft_feature_cloudtrail_data_events      = true
  aft_feature_enterprise_support          = false
}

After the trigger on the account-request repository it triggers a build. This build always fails with this setup, unless if I add the two build command in the buildpsec I've mentioned.
