### ISSUE TITLE
Do we can disable VPC endpoints creation?

### ISSUE THREAD

**Issue by devopscaxsol** [aws-ia/terraform-aws-control_tower_account_factory#367]
Hello Team,

Do we have options to pass arguments and VPC endpoints will not created?

**Comment by v-rosa** [comment]
Yes, check here:

- https://github.com/search?q=repo%3Aaws-ia%2Fterraform-aws-control_tower_account_factory%20aft_vpc_endpoints%20&type=code

- https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/main/README.md#input_aft_vpc_endpoints

**Comment by devopscaxsol** [comment]
Thanks @v-rosa . 

I will definitely look into this.

Thanks for info.

**Comment by devopscaxsol** [comment]
@v-rosa 

If we set false in variable.tf , vpc endpoints for all resource will not created RIGHT?

after set false, is there any files need to modify?

**Comment by v-rosa** [comment]
You need to set false in the module invocation.

I.e.

```hcl
module "aft" {
  source = "github.com/aws-ia/terraform-aws-control_tower_account_factory"
  .....
  input_aft_vpc_endpoints = false
  ....

```

**Comment by devopscaxsol** [comment]
like as below RIGHT?

module "aft" {
  source = "github.com/aws-ia/terraform-aws-control_tower_account_factory"
  # Required Vars
  ct_management_account_id    = ""
  log_archive_account_id      = ""
  audit_account_id            = ""
  aft_management_account_id   = ""
  ct_home_region              = ""
  tf_backend_secondary_region = ""

  terraform_version = "1.2.3"
  input_aft_vpc_endpoints = false

}

Thank You

**Comment by v-rosa** [comment]
yes, something like that. Give it a try with a `terraform plan` and check what is changing.

**Comment by Veevaete** [comment]
@devopscaxsol That depends on what you put in your VPC.
