### ISSUE TITLE
create separate account for management?

### ISSUE THREAD

**Issue by hardikpatel29** [aws-ia/terraform-aws-control_tower_account_factory#368]
Hello Team,

I have control tower setup with 3 accounts. Now do i have to create a one more account for aft management?

if yes than do i have to call aft module from aft management account or control tower management account?

Please guide me.

gathering info on this so.

Thank You.

**Comment by josukuttyulahannan** [comment]
@hardikpatel29 You should create a new account for AFT. But you have to run the aft module from the Control Tower Management Account.

**Comment by snebhu3** [comment]
@hardikpatel29 please reach out if you have additional questions.
