### ISSUE TITLE
How to call/ trigger account request pipeline from Lambda?

### ISSUE THREAD

**Issue by devopscaxsol** [aws-ia/terraform-aws-control_tower_account_factory#373]
Hello Team,

Is there any way or possibility to trigger pipeline from aws lambda?

**Comment by snebhu3** [comment]
@devopscaxsol thank you for reaching out.
Please may you provide more information about your specific use case and the goal you are trying to achieve?

**Comment by snebhu3** [comment]
@devopscaxsol please feel free to reach out in case of additional questions.
