### ISSUE TITLE
AFT Account Customisation Pipeline not able to read .tfvars and .auto.tfvars files 

### ISSUE THREAD

**Issue by awsomeinfra** [aws-ia/terraform-aws-control_tower_account_factory#379]
**Terraform Version & Prov:**

**AFT Version:**
1.10.3

**Terraform Version & Provider Versions**
Please provide the outputs of `terraform version` and `terraform providers` from within your AFT environment

`terraform version`
```
1.5.3
```

`terraform providers`
```
>= 3.68.0
```

**Bug Description**
In aft-account-customisation-repo, we have Terraform configuration that includes _tfvars_ or _.auto.tfvars_ files for variable declaration. But AFT account customisation pipeline is running into error "Error: No value for required variable". If default values are assigned along with variable definition then  it runs fine, but if we use _.tfvars_ or ._auto.tfvars_ then it does not work.

**To Reproduce**
1. Deploy AFT
2. In aft-account-customisation-repo, create a Terafom configuration with _.tfvars_ or ._auto.tfvars_ file fot variable declaration.
3. Run the account customisation pipeline.

**Expected behavior**
AFT pipeline should pick variable declaration form tfvars or .auto.tfavrs

**Related Logs**
NA

**Additional context**
NA

**Comment by snebhu3** [comment]
@awsomeinfra thank you for reaching out.
Please may you confirm the path for the .`tfvars` or `.auto.tfvars` within the `aft-account-customizations` repository?

**Comment by awsomeinfra** [comment]
@snebhu3 .tfvars or .auto.tfvars is in the same module as main.tf
<img width="312" alt="Screenshot 2023-08-05 at 9 26 22 AM" src="https://github.com/aws-ia/terraform-aws-control_tower_account_factory/assets/125473684/38389edf-b5ca-4900-a2ab-571ea3b77616">

**Comment by snebhu3** [comment]
@awsomeinfra can you confirm that your` terraform.auto.tfvars` file is not ignored by git and that its present in the respective remote github repository?

**Comment by awsomeinfra** [comment]
@snebhu3 Thanks for pointing this out, .tfvars was not present in github as its was ignored by gitignore. I have made this correction and not its working fine.
