### ISSUE TITLE
disable nat gateway in vpc which aft setup

### ISSUE THREAD

**Issue by devopscaxsol** [aws-ia/terraform-aws-control_tower_account_factory#386]
Hello

can we disable nat gateway creation while launching AFT module first time?

**Comment by stumins** [comment]
Hi @devopscaxsol,

Unfortunately disabling NAT Gateway creation is not possible at this time. We are tracking the optional provisioning of AFT networking components under https://github.com/aws-ia/terraform-aws-control_tower_account_factory/issues/150.

To reduce networking related costs, you may be interested in disabling VPC Endpoints by setting the AFT deployment parameter `aft_vpc_endpoints = false`.

I'm going to close this issue as a duplicate - please track https://github.com/aws-ia/terraform-aws-control_tower_account_factory/issues/150. for status updates regarding this request.
