### ISSUE TITLE
STACK already exists

### ISSUE THREAD

**Issue by devopscaxsol** [aws-ia/terraform-aws-control_tower_account_factory#388]
Hello Team,

Getting error while 

Lambda : aft-account-request-processor

execution...

ERROR : A stack named xxxxx already exists.

So how to remove existing stack?

where we can remove ?

Thank you

**Comment by snebhu3** [comment]
@devopscaxsol , I would recommend reaching out to AWS premium support with all the details of your AFT environment, the goal you are trying to achieve, and the error with stack trace for the failure.
