### ISSUE TITLE
how we can remove entry from DB and terraform files which account not provisioned

### ISSUE THREAD

**Issue by devopscaxsol** [aws-ia/terraform-aws-control_tower_account_factory#390]
Hello Team,

I have one situation.

when AFT pipeline failed mostly in duplication of email and other details, how we can clean up that TF files and item entry from dynamodb and also in SQS queue.

is manual option only way to do?

any process that we can clean up TF files which account not provisioned?  

My case aft pipeline failed in duplicate email entry and rest payload info.

any suggestion...

thank you

**Comment by adam-daily** [comment]
Hey, thanks for reaching out. In broad terms, yes, manual cleanup is the route to take when removing accounts. Not sure if this exactly what you need in your case, but you can find more info here: https://docs.aws.amazon.com/controltower/latest/userguide/aft-remove-account.html

However, I think reaching out to AWS Premium Support for help is the best route in this case. They can see the details in your actual account that we're unable to see and are better equipped to help through this.
