### ISSUE TITLE
aft-customizations ignores the maximum_concurrent_customization parameter

### ISSUE THREAD

**Issue by wellsiau-aws** [aws-ia/terraform-aws-control_tower_account_factory#395]
**Terraform Version & Prov:** 
n/a

**AFT Version:** 
1.10.4

**Terraform Version & Provider Versions** 
n/a

**Bug Description**
AFT introduce parameter `maximum_concurrent_customization` to set the maximum number of pipeline that runs in parallel. This parameter however was not honored in the `aft-customizations` module, where the state machine has [a hard-coded concurrency of 25](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/6c0b356895478bb5c6578417640819aa0c8d774b/modules/aft-customizations/states/invoke_customizations.asl.json#L16-L19)

**To Reproduce**
The hard-coded value can be found [here](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/6c0b356895478bb5c6578417640819aa0c8d774b/modules/aft-customizations/states/invoke_customizations.asl.json#L16-L19)

Lambda that controls the pipeline execution can be found [here](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/6c0b356895478bb5c6578417640819aa0c8d774b/src/aft_lambda/aft_customizations/aft_customizations_execute_pipeline.py#L27-L29)

Based of this understanding, it's possible for user to execute the state machine `aft-invoke-customizations` with larger parallelization than value defined in `maximum_concurrent_customization`. This will impact the downstream `aft-account-provisioning-framework` as well.

As additional note, the `maximum_concurrent_customization` was [passed to the module](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/6c0b356895478bb5c6578417640819aa0c8d774b/modules/aft-customizations/states.tf#L12) but never used in the [template file](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/6c0b356895478bb5c6578417640819aa0c8d774b/modules/aft-customizations/states.tf#L21), this might be just an overlook.

**Expected behavior**
I proposed two possible solution:
1. Honor `maximum_concurrent_customization` in the `aft-customizations` module by removing the [hard-coded concurrency of 25](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/6c0b356895478bb5c6578417640819aa0c8d774b/modules/aft-customizations/states/invoke_customizations.asl.json#L16-L19)
2. If the hard-coded concurrency of 25 was by design, introduce separate variable to surface this value on the root module.

**Related Logs**
n/a

**Additional context**
n/a

**Comment by stumins** [comment]
Hi @wellsiau-aws,

Thanks for reporting this bug. I've created a backlog item for the team to fix this issue.

**Comment by stumins** [comment]
Hi @wellsiau-aws,

[AFT 1.11.0](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/releases/tag/1.11.0) was just released and includes a fix for this issue. 

As of 1.11.0, the concurrency of the Account Provisioning step function (when invoked via `aft-invoke-customizations`) will change from 25 to the current value of `maximum_concurrent_customizations`. If left unspecified, the default value is 5.
