### ISSUE TITLE
SQS DLQ SNS notification

### ISSUE THREAD

**Issue by devopscaxsol** [aws-ia/terraform-aws-control_tower_account_factory#399]
Hello Team,

I have one query that is that any SNS topic is configured with SQS DLQ (aft-account-request-dlq.fifo) if we get any message in this.

As suddenly faced have requested account and our lambda ( aft-account-request-action-trigger )  is pushed data in SQS queue.

after some time data is pushed in DLQ ( aft-account-request-dlq.fifo ). 

We didnt notified why account not provisioned. 

So is there any notification there or need to configured manually.

Thank you

**Comment by adam-daily** [comment]
Hi there, thanks for reaching out. My suggestion is to reach out to AWS Premium Support to work together with you on this request. They have more insight into the state of your account than we do and can give you more targeted help as to what's going on in your specific case.
