### ISSUE TITLE
Feature: Put full account request in vended account's SSM parameters

### ISSUE THREAD

**Issue by mathewmoon** [aws-ia/terraform-aws-control_tower_account_factory#40]
1.1.0 Feature to add custom_fields to parameter store is great, but it would be good to take it one step further and add the full request to SSM. This would allow doing things like adding the tags, which can't be accessed using the role assumed during the account customization process (The role in the vended account). Having a path of `/aft/account-request` that contains all of the attributes in the aft-account-request module solves this.

**Comment by balltrev** [comment]
I went ahead and created a backlog to track this feature request within the team. I could see expansion here of the data in a vended account making sense from an ease of use perspective, but we'll discuss it as a team and go from there. Thanks for the info here!

**Comment by mathewmoon** [comment]
For anyone else who comes across this:

For now the solution is to set all parameters for the account-request module in locals and add all of those parameters into the custom_fields
