### ISSUE TITLE
Upgrade AWS Provider Version

### ISSUE THREAD

**Issue by jlosito** [aws-ia/terraform-aws-control_tower_account_factory#402]
**AFT Version:**
(Can be found in the AFT Management Account in the SSM Parameter `/aft/config/aft/version`)
1.10.0

**Bug Description**

As of writing, 5.22.0 is the latest version of the AWS provider.

https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.22.0

https://registry.terraform.io/providers/hashicorp/aws/latest/docs

AFT seems to be restricting me to >= 4.27.0, < 5.0.0. 
https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/main/versions.tf#L10C32-L10C51

I would like to use a more recent version of the AWS provider >= 5.0.0 in order to be in support and ensure that any security issues are resolved.

**To Reproduce**

Deploy AFT using v1.10.0, which is the latest as of the time of writing. Then check which version of the AWS provider is used. The version should be >= 4.27.0, < 5.0.0, but I would like to be >= 5.0.0 since that is the latest.

**Expected behavior**
The latest version of the provider is used and supported.

**Related Logs**
Provide any related logs or error messages to help explain your problem.

**Additional context**
I have a use case where I would always like to be on the latest version as much as possible in order to be supported as well as ensure any security issues are resolved.

**Comment by stumins** [comment]
Hi @jlosito,

Thanks for opening this enhancement request. I've created a backlog item to update the version of the AWS Provider used to deploy AFT's resources.

**Comment by stumins** [comment]
Hi @jlosito,

[AFT 1.11.0](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/releases/tag/1.11.0) was just released, and raises the AFT deployment provider constraints to `">= 5.11.0, < 6.0.0"`.

Thanks for opening this issue!
