### ISSUE TITLE
move local.log_archive_bucket_object_expiration_days to a variable var.log_archive_bucket_object_expiration_days

### ISSUE THREAD

**Issue by silvaalbert** [aws-ia/terraform-aws-control_tower_account_factory#405]
**Describe the outcome you'd like**

Moving local.log_archive_bucket_object_expiration_days to a variable var.log_archive_bucket_object_expiration_days would allow customers to increase/decrease that value if desired. The value of 365 can be set as a default so that the current retention remains the same.

**Comment by stumins** [comment]
Hi @silvaalbert,

Thank you for opening this feature request. I've created a backlog item for the team to investigate exposing the archive bucket object expiration days as a deployment parameter.
