### ISSUE TITLE
Getting error (operation error S3: HeadBucket, https response error StatusCode: 301) while running terraform apply to configure aft management account

### ISSUE THREAD

**Issue by siprap-ics** [aws-ia/terraform-aws-control_tower_account_factory#411]
**Terraform Version & Prov:**

**AFT Version:**
1.11.1

**Bug Description**
I am trying to create new aft management account and added all details as explained in [https://aws.amazon.com/blogs/aws/new-aws-control-tower-account-factory-for-terraform/](url) but when I am trying to run terraform apply I am getting the following error:

 Error: reading Amazon S3 (Simple Storage) Bucket (aft-backend-675853664026-secondary-region): operation error S3: HeadBucket, https response error StatusCode: 301, RequestID: YTJ7M84V5DRBQX2K, HostID: 87oyYH8qviiKZFevchUr4xnGuEeylTe0QZ1lCRqw/4ha/PPtm7qHtH+r2Btp7fALy/y9EFud1kQsFmxwmXzqdA==, api error MovedPermanently: Moved Permanently
│
│   with module.aft.module.aft_backend.aws_s3_bucket.secondary-backend-bucket[0],
│   on .terraform\modules\aft\modules\aft-backend\main.tf line 21, in resource "aws_s3_bucket" "secondary-backend-bucket":
│   21: resource "aws_s3_bucket" "secondary-backend-bucket" {

The error is pointing to [aws-repo](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/main/modules/aft-backend/main.tf#L21)

Please let me know if any other details you want. 

Thanks in advance!!

**Comment by hanafya** [comment]
Hey @siprap-ics!
Are you trying to create a second management account or is this for a completely new environment?

**Comment by siprap-ics** [comment]
Het @hanafya , Thanks for your reply...the issue got resolved. Hence, closing this issue.
