### ISSUE TITLE
Is AFT getting deprecated, or very unimportant to AWS?

### ISSUE THREAD

**Issue by be-aws-architect** [aws-ia/terraform-aws-control_tower_account_factory#413]
**Describe the outcome you'd like**

I used AFT for a year at my previous job and really liked it. However following the Github it has become **very** worrying the lack of needed changes and improvements that are promised but never implemented. It's always added to the backlog, but seemingly never implemented.

In 2023 we went from 1.7.0 to 1.11.4 with very little worthwhile changes, mostly bugfixes.

**Is your feature request related to a problem you are currently experiencing? If so, please describe.**

My problem is that from a customer POV it looks like the backlog is never really picked up, which is of course not the fault of the engineer's that work(ed?) on AFT, but from management above allocating their time differently. 

Should we expect AFT to be discontinued in the (near) future? Or is there an explanation for the very little amount of updates/upgrades we receive?

**Comment by vivesan1** [comment]
@be-aws-architect Thank you for reaching out. Our team is continuing full support for AFT and there are no plans to change that. AFT is not a standalone service and falls under the Control Tower umbrella. Feature requests for AFT are prioritized across all other feature requests for capabilities supported by Control Tower, such as recent launches in API support for controls and landing zone operations. 

Please continue logging bugs and feature requests and submitting product feature requests through Premium Support.

**Comment by be-aws-architect** [comment]
Okay, thank you for the response. Then we hope the CT team finds some breathing room in 2024 to pick up on the AFT backlog.

Kind regards
