### ISSUE TITLE
DynamoDB error: aft-request EnabledPROBLEM: Function call failed

### ISSUE THREAD

**Issue by jekushak** [aws-ia/terraform-aws-control_tower_account_factory#421]
Hello Community,

I have a problem with DynamoDB where the following error occurs: **"EnabledPROBLEM: Function call failed".** This seems to be related to a failed function call related to the DynamoDB table **"aft-request"**.

**Error details:**
Error message: aft-request: EnabledPROBLEM: Function call failed"

**What I checked:**
Checked AWS CloudWatch logs for more details.
Checked IAM permissions for the role calling the function.
Ensured correct configuration of DynamoDB table.
Checked the code of the Lambda function that interacts with DynamoDB.
Checked the DynamoDB triggers and indexes.

We would be very grateful for any advice and support in solving this DynamoDB problem!

**Comment by snebhu3** [comment]
@jekushak Thank you for reaching out.
I would recommend reaching out to AWS premium support as they would be able to help deep dive into your AFT environment and troubleshoot.
