### ISSUE TITLE
Terraform Cloud Requires a Team or User Token

### ISSUE THREAD

**Issue by mikeantonelli** [aws-ia/terraform-aws-control_tower_account_factory#45]
Opening this issue to cross-link documentation updates related to this project via https://github.com/awsdocs/aws-control-tower-guide/pull/31.

HashiCorp's specification for [Configuration Versions API](https://www.terraform.io/cloud-docs/api-docs/configuration-versions):

> Note: This endpoint cannot be accessed with organization tokens. You must access it with a user token or team token.

If you use an organization token, you will get a HTTP 404 not found error when running `ct-aft-account-provisioning-customizations` CodePipeline.

**Comment by stumins** [comment]
Hi, thanks for letting us know. We'll take a backlog item to clarify the documentation around token types.
