### ISSUE TITLE
[Question] about account id in input

### ISSUE THREAD

**Issue by vietwow** [aws-ia/terraform-aws-control_tower_account_factory#46]
Hi all,

As an official document, we only need to create OU (step 1) and account for AFT management (step 2). After that, this tf module (step 3) will create the remaining accounts like log, audit, ... But in the example (https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/main/examples/github%2Btf_oss/main.tf), I see that we need to input account id of these accounts. So where could I take these account id? This makes me really confused. Hope anyone could explain. Thanks.

Best regards,

**Comment by stumins** [comment]
Hi, the audit and log archive accounts are created automatically when you provision a Control Tower landing zone. You can find their account IDs in the Control Tower console from within your Control Tower management account (not the AFT management account).

https://docs.aws.amazon.com/controltower/latest/userguide/accounts.html#special-accounts
