### ISSUE TITLE
Issue when running `aft-account-provisioning-framework` step function

### ISSUE THREAD

**Issue by nc-rajeshnair** [aws-ia/terraform-aws-control_tower_account_factory#483]
**Terraform Version & Prov:**

**AFT Version:**
(Can be found in the AFT Management Account in the SSM Parameter `/aft/config/aft/version`)

**Terraform Version & Provider Versions**
Please provide the outputs of `terraform version` and `terraform providers` from within your AFT environment

`terraform version`
```
1.9.3
```

`terraform providers`
```
5.62.0
```

**Bug Description**
I am getting an error in my step function `aft-account-provisioning-framework` which creates the pipeline. I can only see 3 step functions after my deployment. 

1. `aft-invoke-customizations`
2.  `aft-account-provisioning-framework`
3.  `aft-feature-options`

Below error in step function `aft-account-provisioning-framework`

```
An error occurred while executing the state 'run_create_pipeline?' (entered at the event id #33). Invalid path '$.Input.account_provisioning.run_create_pipeline': The choice state's condition path references an invalid value.
```

```
{
  "Error": "StepFunctions.StateMachineDoesNotExistException",
  "Cause": "State Machine Does Not Exist: 'arn:aws:states:eu-west-1:009160062499:stateMachine:aft-account-provisioning-customizations' (Service: AWSStepFunctions; Status Code: 400; Error Code: StateMachineDoesNotExist; Request ID: a3989ac3-1dae-408f-863d-7730662277d3; Proxy: null)"
}
```

**Comment by ravipratap-wpp** [comment]
Hi there :- I'm getting same error while importing the AWS accounts I could see ***aft-account-provisioning-framework*** execution is failing stating

` "cause": "An error occurred while executing the state 'run_create_pipeline?' (entered at the event id #33). Invalid path '$```
.Input.account_provisioning.run_create_pipeline': The choice state's condition path references an invalid value.",
  "error": "States.Runtime"```


can someone please let me know how was this fixed ?

**Comment by raju7258** [comment]
Hi @ravipratap-wpp 

Have you deployed [this](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/tree/main/sources/aft-customizations-repos/aft-account-provisioning-customizations) before deploying an account?

**Comment by ravipratap-wpp** [comment]
No I haven't deployed it, shall I merge the code and deploy it and then give it a try ?

**Comment by raju7258** [comment]
Please deploy it and then try to vend an account

**Comment by ravipratap-wpp** [comment]
Sure, Shall update you progress . Thank you somuch
