### ISSUE TITLE
Fail to deploy latest version 1.1.2

### ISSUE THREAD

**Issue by fjromerom** [aws-ia/terraform-aws-control_tower_account_factory#49]
Hi,

the latest version 1.1.2 that was released 2 days ago fails to deploy from scratch. I've tested the previous version 1.1.1 and it works fine.

Here is the output:

```
$ terraform plan                          
╷
│ Error: Unsupported block type
│ 
│   on .terraform/modules/aft/modules/aft-account-request-framework/backup.tf line 26, in resource "aws_backup_selection" "aft_controltower_backup_selection":
│   26:   condition {}
│ 
│ Blocks of type "condition" are not expected here.
╵
╷
│ Error: Unsupported argument
│ 
│   on .terraform/modules/aft/modules/aft-account-request-framework/backup.tf line 27, in resource "aws_backup_selection" "aft_controltower_backup_selection":
│   27:   not_resources = []
│ 
│ An argument named "not_resources" is not expected here.
```

According to the comment on the line 25 it seems to be caused by https://github.com/hashicorp/terraform-provider-aws/issues/22595.

Francisco.

**Comment by stumins** [comment]
Hello, we're actively investigating this issue.

Could you paste your output of running `terraform -v`?

**Comment by fjromerom** [comment]
Sure!

```
$ terraform -v
Terraform v1.1.4
on linux_amd64
```

**Comment by stumins** [comment]
Thank you for the details. Can you please also post the output of `terraform providers`?

**Comment by balltrev** [comment]
Hey @fjromerom, thanks for helping catch this. We were able to reproduce this, and discovered it was an out of date minimum version for the `hashicorp/aws` provider.

 We've updated the minimum `hashicorp/aws` provider version in [1.2.1](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/releases/tag/1.2.1) which should fix this issue. Can you retry with [1.2.1](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/releases/tag/1.2.1)?

**Comment by fjromerom** [comment]
Hi @balltrev! I can confirm the new version 1.2.1 works fine and there are no issues.

Thanks for the prompt response :)
