### ISSUE TITLE
Allow terraform workspace to be variable.

### ISSUE THREAD

**Issue by jopperman-stg** [aws-ia/terraform-aws-control_tower_account_factory#50]
I'm curious as to why the [TF_WORKSPACE_NAME](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/0a53b53c10f8e012de35de711dd55594e29c9178/modules/aft-code-repositories/buildspecs/ct-aft-account-provisioning-customizations.yml#L64) is a hardcoded value when the rest of the terraform values when using tfc are variables. It would be nice to control the workspace name in my organization.

Thoughts?

**Comment by stumins** [comment]
Hey there,

Thank you for the feedback. I've created a backlog item for the team to explore allowing the workspace name to be defined as a variable.
