### ISSUE TITLE
Pipelines not running automatically after committing on any of the repositoris 

### ISSUE THREAD

**Issue by alfredocambera-bitso** [aws-ia/terraform-aws-control_tower_account_factory#51]
I'm using github as vcs with public repositories for testing. Whenever I push commits to the main branch of any of the following repositories:

- Account requests
- AFT account provisioning customizations
- Global customizations
- Account customizations

I need to go to Developer Tools > CodePipeline > Pipelines, select on the pipeline (for example: ct-aft-account-request) and then click on `Release change` to trigger the pipeline with the most resent change.

AFAIK, a commit on the main branch should trigger a deployment but that's not working.

The codestar connection is active and the user who created it has write/read permissions on the repository (is not the owner).

How can I troubleshoot this?

**Comment by alfredocambera-bitso** [comment]
I already checked the following on CodePipeline:
- The name of the repository.
- The `Start the pipeline on source code change` (it is on).
- The branch name (`main`).

**Comment by stumins** [comment]
Hi,

Thank you for providing those details. Can you check that the commit pushed to the GitHub repos on the branch that matches the pipeline configuration (`main`) and not another branch like `master` or similar?

**Comment by snebhu3** [comment]
Thank you for checking that. As we are unable to reproduce your exact problem, you might need to reach out to premium support to dive deeper and get help troubleshooting your CodeStar connection.

**Comment by alfredocambera-bitso** [comment]
Sure, I'll contact them. Thanks.
