### ISSUE TITLE
AFT module v1.13.2 breaks

### ISSUE THREAD

**Issue by mikkoc** [aws-ia/terraform-aws-control_tower_account_factory#516]
**Terraform Version & Prov:**
`terraform_version = "1.6.6"`

**AFT Version:**
`v1.13.2`

**Terraform Version & Provider Versions**
Please provide the outputs of `terraform version` and `terraform providers` from within your AFT environment

`terraform version`
```
Terraform v1.7.5
on darwin_arm64
+ provider registry.terraform.io/hashicorp/archive v2.7.0
+ provider registry.terraform.io/hashicorp/aws v5.81.0
+ provider registry.terraform.io/hashicorp/local v2.5.2
+ provider registry.terraform.io/hashicorp/random v3.6.3
+ provider registry.terraform.io/hashicorp/time v0.12.1
```

**Bug Description**
We upgraded the AFT module from v1.13.1 to v1.13.2

Our AFT customization pipeline broke, see AWS ticket 173332875500005 for details

Downgrading back to 1.13.1 fixes the issue.

**To Reproduce**
Change from:
```
module "aft" {
  source  = "aws-ia/control_tower_account_factory/aws"
  version = "1.13.1"
[...]
}
```
to:

```
module "aft" {
  source  = "aws-ia/control_tower_account_factory/aws"
  version = "1.13.2"
[...]
}
```

**Expected behavior**
AFT module upgrade should not break our AFT customizations.

**Related Logs**
see AWS ticket 173332875500005

**Comment by JamesActually** [comment]
Thank you for reporting this issue.  AWS Support is best suited to helping you resolve this issue.  I see that you already opened a case, so I will resolve this issue while AWS Support helps you get your customization pipeline running properly again.
