### ISSUE TITLE
"Cannot have more than 1 builds in queue for the account" with newly deployed AFT account.

### ISSUE THREAD

**Issue by maclema** [aws-ia/terraform-aws-control_tower_account_factory#54]
With a newly deployed AFT account, when you attempt to execute the customizations pipeline via step functions, if there is more than one account pipeline only one pipeline will start executing, and the others will fail with "Cannot have more than 1 builds in queue for the account".

I needed to run an EC2 instance for ~20 minutes and receive the "Your Request For Accessing AWS Resources Has Been Validated" email before more than one pipeline could be started concurrently without exception.

This should be called out in the documentation, or as part of the AFT account deployment an instance should be run to cause the account validation to occur.

**Comment by snebhu3** [comment]
Thank you for the call out. We will create an internal backlog to address this in our documentation.
