### ISSUE TITLE
aft-customizations-pipeline bucket should use S3 block public access

### ISSUE THREAD

**Issue by maclema** [aws-ia/terraform-aws-control_tower_account_factory#56]
As with the aft-backend buckets, the aft-customizations-pipeline bucket should also enable S3 block all public access to be inline with the AWS Foundational Security Best Practices controls: https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#fsbp-s3-8

**Comment by snebhu3** [comment]
Thank you for the call out. We have created an internal backlog to track this feature request.
I will go ahead and close this issue for now.
