### ISSUE TITLE
S3 buckets should have bucket policies enforcing HTTPS endpoints.

### ISSUE THREAD

**Issue by maclema** [aws-ia/terraform-aws-control_tower_account_factory#57]
The S3 buckets (aft-backend, and aft-customizations-pipeline) should implement bucket policies to enforce secure endpoints to be inline with AWS Foundational Security Best Practices controls: https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#fsbp-s3-5

**Comment by snebhu3** [comment]
Thank you for the good call out. We have created an internal backlog for the feature request.
I am going to move forward and close this issue for now.

**Comment by thijruiz** [comment]
@balltrev , @snebhu3 do you have an estimative for this fix?
