### ISSUE TITLE
Customizations multiple regions

### ISSUE THREAD

**Issue by fjromerom** [aws-ia/terraform-aws-control_tower_account_factory#59]
Hi team,

sometimes it's needed to deploy resources in multiple regions, however the provider is a jinja template file that is used during the build phase.

What's the best way to deploy customizations on multiple regions?

Thanks,
Francisco

**Comment by snebhu3** [comment]
Thank you for reaching out.
Although there could be multiple ways of implementing this, you could expand the provider jinja template to include [alternate provider configurations ](https://www.terraform.io/language/providers/configuration#referring-to-alternate-provider-configurations) with required regions. You could then use these alternate providers in your resources.

**Comment by fjromerom** [comment]
That makes sense to me! Thanks for the confirmation.

Francisco
