### ISSUE TITLE
[Feature Request] Multiple Customizations in Account Request

### ISSUE THREAD

**Issue by danno-rose** [aws-ia/terraform-aws-control_tower_account_factory#6]
When deploying a new account, or updating an existing account, I would like to prove a LIST of customizations to the request.

This would
1. Reduce the amount of copy and paste between customizations, where i want the same code deployed different account types
2. Allow customers to produce specific customizations, that can be applied in a more distinct way to different accounts
3. Allow customers to apply specific modules to specific accounts in a clear format

example

```
module "prod_01" {
  source = "./modules/aft-account-request"

  control_tower_parameters = {
    AccountEmail = "prod@amazon.com"
    AccountName  = "dev-aft-test-01"
    # Syntax for top-level OU
    ManagedOrganizationalUnit = "prod"
    # Syntax for nested OU
    ....
    ....

  account_customizations_list = [
      "production_generic",
      "module_just_for_this_account1",
      "module_just_for_this_account2"
     ]
}
```

**Comment by adam-daily** [comment]
Hey, thanks for the feature request. I'll go ahead and add this to our backlog.
