### ISSUE TITLE
Clean-up resources when an account is removed

### ISSUE THREAD

**Issue by fjromerom** [aws-ia/terraform-aws-control_tower_account_factory#62]
Hi team,

AFT manages the creation of the account as well as the creation of the baseline resources, however it does not manage the deprovisioning when an account will be suspended. If an account is removed from the account-request repository, this is removed from the DynamoDB table aft-request however not from aft-request-metadata. The CodePipeline pipeline created is not removed either. 

My expectation of AFT is to perform the following actions:

- Remove any resource related with the account such as the CodePipeline pipeline.
- Unregister the account from AWS Control Tower.

What's the plan to support deprovision of an account?

Thanks,
Francisco

**Comment by balltrev** [comment]
We do call out this process in our [public docs](https://docs.aws.amazon.com/controltower/latest/userguide/aft-remove-account.html), but I do see an opportunity here to automate some of the steps that you're calling out (eg: CodePipelines).

I'll make a backlog to track these improvements to the account removal process.

**Comment by pursachi** [comment]
AFT still doesn't destroy resources created by the customization pipeline, it however deletes the pipeline itself. Any plans to include this feature?
