### ISSUE TITLE
Add `*tfplan*` to .gitignore for customization repos

### ISSUE THREAD

**Issue by jeremyciak** [aws-ia/terraform-aws-control_tower_account_factory#66]
Can we add `*tfplan*` to the `.gitignore` files for each of the customization repositories defined here:
https://github.com/aws-ia/terraform-aws-control_tower_account_factory/tree/main/sources/aft-customizations-repos

I see no reason to track Terraform plan outputs in source control and inadvertently committed one (from my customization testing cycles) since this was not part of the `.gitignore` as I would have expected.

**Comment by snebhu3** [comment]
Thank you for the good call out. I have created an internal backlog to add *tfplan* to the .gitignore files for each of the customization repositories.
I will go ahead and close this issue for now.
