### ISSUE TITLE
Enhancement Request:  Convert account_customizations_name from type 'string' to type 'map(any)'

### ISSUE THREAD

**Issue by cdhesse** [aws-ia/terraform-aws-control_tower_account_factory#68]
# Issue
In the `aft-account-request` terraform the variable `account_customizations_name` is a string.

```
variable "account_customizations_name" {
  type        = string
  default     = ""
  description = "The name of the account customizations to apply"
}
```

To illustrate the issue, assume we have three unique customizations which have nothing to do with one another.  With the current design, we are forced to combine all three customizations into one folder and one terraform.  At scale, this becomes hard to maintain.

What if some accounts need `customization_one`, some need `customization_one` and `customization_two`, and others need `customization_one`, `customization_two` , and `customization_three`?  We have to do a lot of copy/paste of code and remember to update all of them when a change is made.

# Proposal
Change this attribute to be a map(any) which could be json where the top level key is a customization name corresponding to the folder in `aft-account-customizations` repo.  In addition to allowing for a particular account to get more modular customizations, it could also allow for automatic propagation of attributes to control the behavior of the customization.  This concept is included in the example that follows.

```
variable "account_customizations" {
  type        = map(any)
  description = "A map of customizations (corresponding to a folder in the aft-account-customizations repo), and any custom key/value pairs to pass to the customization."
}
```
An example could be something like this:

```
account_customizations = {
    customization_one = {
        custom_field1 = "this is great",
        custom_field2 = "this is also great"
    },
    customization_two = {
         custom_number = 8
    },
    customization_three = {}
}
```

In this above example, perhaps we have some `custom_fields` or other hard coded or other values that change the behavior of the customization.

If the project will accept pull requests, we would consider providing this enhancement if it is agreed to.

**Comment by snebhu3** [comment]
Thank you for the feature request and also for explaining the use case. 
We are not accepting contributions at this time, but I have created an internal backlog to address this request.

I will go ahead and close this issue for now.
