### ISSUE TITLE
Create new account executes but no action takes place in the Master Account

### ISSUE THREAD

**Issue by vlad-QuaDex** [aws-ia/terraform-aws-control_tower_account_factory#72]
Hi, I have the following issue. 
When I try to create an account using a `aft-account-request` push it successfully executes the pipeline.
It finishes successfully and the logs appear to call for a creation of a new account. However, after that nothing happens.

The entries exist in DynamoDB table but the Lambda that is triggered results in errors and there is nothing going into the SQS.

CloudWatch Logs show the following Lambda Error:
`
[ERROR] Runtime.ImportModuleError: Unable to import module 'aft_account_request_processor': cannot import name 'modify_existing_account' from 'aft_common.account_request_framework' (/opt/python/lib/python3.8/site-packages/aft_common/account_request_framework.py)Traceback (most recent call last): | [ERROR] Runtime.ImportModuleError: Unable to import module 'aft_account_request_processor': cannot import name 'modify_existing_account' from 'aft_common.account_request_framework' (/opt/python/lib/python3.8/site-packages/aft_common/account_request_framework.py) Traceback (most recent call last):
`
![Screen Shot 2022-02-11 at 15 21 58](https://user-images.githubusercontent.com/41385350/153664784-816625c8-626c-4c9e-967b-ffe62ad23827.png)
![Screen Shot 2022-02-11 at 15 22 46](https://user-images.githubusercontent.com/41385350/153664829-5454b3ce-a2b9-4333-a012-93507d4806c4.png)

**Comment by vlad-QuaDex** [comment]
![Screen Shot 2022-02-11 at 15 24 32](https://user-images.githubusercontent.com/41385350/153665083-247b38c5-e57e-43be-ab09-4dc452883f45.png)

**Comment by balltrev** [comment]
Hi @vlad-QuaDex, the error you've noted seems to imply your lambda layer is out of date with the code in the lambda handler.

We just released an update that involves fixing a bug with how we handle the Lambda Layer build, if you could update to 1.3.2 and give the process another shot, this should hopefully resolve the issue you're facing.

**Comment by balltrev** [comment]
Glad to hear it!
