### ISSUE TITLE
Step function aft-account-provisioning-framework to fast

### ISSUE THREAD

**Issue by pglagerweij** [aws-ia/terraform-aws-control_tower_account_factory#73]
In the first execution of the aft-account-provisioning-framework step function. My step function failed in the aft_account_provisioning_framework_account_metadata_ssm step. It cannot assume the AWSAFTExecution role in the target account.

Triggering a rerun of the same step function (with the same step function payload) yields the proper results and no errors (with no change in between). Perhaps good to add some exponential back-off or wait time so that we are certain global IAM changes have gone through. 

![image](https://user-images.githubusercontent.com/16048131/153707352-d4b7305c-1b25-4d2a-bb87-30f191d97da4.png)

**Comment by PeterBengtson** [comment]
I've experienced this as well.

**Comment by balltrev** [comment]
Thanks for the call out here, we'll add a backlog to increase retries in our service calls
