### ISSUE TITLE
Unable to upgrade or check version of AFT

### ISSUE THREAD

**Issue by ChrisMusgrove** [aws-ia/terraform-aws-control_tower_account_factory#76]
Hi,

Is there any documentation on checking the current version of AFT running in the environment and how to upgrade the version?

**Comment by balltrev** [comment]
Hey @ChrisMusgrove , you can check your deployed AFT version by querying the SSM Parameter Store key `/aft/config/aft/version`

As far as upgrading, depending on how you deployed, the following should pull in the latest version from our main branch

```
terraform get -update
```

Once this is complete, you should be able to re-run terraform plan/apply to update the AFT infrastructure with our newest features/fixes.


We have created a backlog to include documentation about this though, thanks for the question!

**Comment by nitrocode** [comment]
If you use the registry method, you can pin the version

https://registry.terraform.io/modules/aws-ia/control_tower_account_factory/aws/latest

```hcl
module "control_tower_account_factory" {
  source  = "aws-ia/control_tower_account_factory/aws"
  version = "1.3.2"
  # insert the 6 required variables here
}
```

**Comment by balltrev** [comment]
@ChrisMusgrove feel free to reopen this issue if you're still having trouble with this, going to close it for now
