### ISSUE TITLE
Issues with importing pre-existing Accounts to AFT

### ISSUE THREAD

**Issue by ArshikDhar** [aws-ia/terraform-aws-control_tower_account_factory#77]
For AWS accounts that were created with the Control Tower before AFT, importing such accounts to AFT isn't working.
1. Since the accounts are already under the same Organization & created using the same Control Tower, importing such accounts should have been worked with the newly released 1.3.1 AFT version but it didn't worked.
2. I made a separate account.tf file with all the appropriate Control Tower specific details of the existing account & push it to **`aft-account-request`** repo & it did trigger **`ct-aft-account-request`** pipeline but import didn't work. Along with the existing accounts tags, I added an additional tag in the account.tf file but the same didn't reflect on the account.
3. No new account customization pipeline got created to take care of the account & global customization. There are no failures in the `aft-account-provisioning-framework` State Machine execution

**Comment by balltrev** [comment]
By chance does your provisioned product name differ from the account name on the account in question?

There's an implementation detail in regards to the Account Name needing to match the Service Catalog Provisioned Product name. We're actively working to improve this implementation to make this account ingestion process more robust.

**Comment by ArshikDhar** [comment]
SC product name of the already provisioned account & the account-name in the account.tf which is committed to `aft-account-request` repo matches, no difference in there

**Comment by balltrev** [comment]
Can you confirm you're running on the latest release? The AFT version should be located in your AFT Management account under an SSM Parameter `/aft/config/aft/version`. 

If both the Provisioned Product name and the Account name are equal, this should be working.

**Comment by MohamedAnouar** [comment]
I didn't know that I could add existing accounts to AFT via specifying the same name in the account-request? Could-we use this trick to add the Log Audit account ?

**Comment by PeterBengtson** [comment]
@MohamedAnouar: You will find that the core Control Tower accounts are not only not supported by the AFT, but they also are not managed by Service Catalog. (Also, at the moment accounts with spaces in their names cannot be imported to AFT at all, regardless of where they are. The AFT team is giving the import mechanism an overhaul to fix this.)

**Comment by ArshikDhar** [comment]
Thanks @balltrev, the issue is resolved now. I was able to import the accounts to AFT configuration with the latest release. Just a thought, do we still need to keep the account name as the SC product name?

**Comment by balltrev** [comment]
@ArshikDhar, glad to hear it's working! 

It's probably easiest to be consistent between account requests and their names within Service Catalog. We're looking at improving this experience in the near future. Going to go ahead and close out this issue for now.

**Comment by smeda-stockx** [comment]
We have a weird situation, where we changed account email after importing not CT accounts to CT and now AFT couldn't import them(Basically entries in CT now doesn't match the account ). Any workaround for this?
