### ISSUE TITLE
Is there a way to apply SCPs with AFT?

### ISSUE THREAD

**Issue by vlad-QuaDex** [aws-ia/terraform-aws-control_tower_account_factory#78]
I can't see a suitable place to apply an SCP. Even without the ability to apply to an OU, I've tried directly applying to individual accounts as part of the Global Customization. However, in that case I get the following:

![Screen Shot 2022-02-15 at 13 42 19](https://user-images.githubusercontent.com/41385350/154127856-65aeb5a2-1403-4068-b8c8-18cd009d659c.png)

**Comment by balltrev** [comment]
At this time I don't believe this is actually supported. We've got a feature request in our backlog around implementing this functionality though.

**Comment by taliesins** [comment]
@vlad-QuaDex did you try executing this under the context of the ct or aft account? I think it needs to execute with ct account context.

```
provider "aws" {
  alias  = "ct_management"
  region = local.current_region
  assume_role {
    role_arn     = "arn:aws:iam::${local.ct_management_account_id}:role/AWSAFTExecution"
    session_name = local.ct_session_name
  }
  default_tags {
    tags = {
      managed_by = "AFT"
    }
  }
}
```

**Comment by stumins** [comment]
@vlad-QuaDex 

As of [AFT 1.4.0](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/releases/tag/1.4.0), you can ingest the Control Tower Management account with AFT and deploy customizations to it, including SCPs.

See also: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/organizations_policy

**Comment by seansilvestri** [comment]
I'm trying to do the same thing here but its unclear to me now to 'ingest' the MPA account to apply SCPs which is what I want to do, e.g., I'd like to apply SCPs from the aft-global-customization repo...
@stumins 
Many thanks...

**Comment by stumins** [comment]
@seansilvestri 

SCPs can be applied via customization like any other resource, but the target account must be the CT Management account. You should ingest the CT management account (see: https://docs.aws.amazon.com/controltower/latest/userguide/aft-update-account.html#aft-update-account-not-provision), then define the SCPs as part of the "account customizations".

SCPs have their own concept of targeting via attachment that you should use to specify where the SCP will be applied - see https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/organizations_policy_attachment

**Comment by seansilvestri** [comment]
may thanks that clarified it!
