### ISSUE TITLE
Automate the service catalog portfolio assignment at initial setup

### ISSUE THREAD

**Issue by rcuenotag** [aws-ia/terraform-aws-control_tower_account_factory#79]
In the post-deployment steps, it mentions adding the AWSAFTExecution role to the service catalog portfolio within the master account. We overlooked this step-- causing an hour or so of banging our heads against the wall before we looped back to that part in the instructions. Admittedly an RTFM error. However, is there a reason why this step cannot be done programmatically as part of the AFT deployment? 

Looking at the service catalog API documentation I see that only a "ListPortfolioAccess" method is documented, however there must be something used behind the scenes at AWS when we grant this access by clicking in the console. If we could use that, it would eliminate another manual step.

Service Catalog API: https://docs.aws.amazon.com/servicecatalog/latest/dg/service-catalog-api-overview.html

**Comment by balltrev** [comment]
Hey @rcuenotag, we're looking at improving this experience, I've gone ahead and created a backlog for this and I'll review with our team.

**Comment by stumins** [comment]
Hi @rcuenotag, as of [AFT 1.4.0](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/releases/tag/1.4.0) this configuration is set automatically. 

Users are no longer required to manually grant AFT roles permissions to the Service Catalog portfolio.

**Comment by adesso-os** [comment]
The documentation still says the step is mandatory though. The role doesn't even seem to exist though.
