### ISSUE TITLE
Account Request "Custom Fields" should be written to aft-request-metadata table, 

### ISSUE THREAD

**Issue by danno-rose** [aws-ia/terraform-aws-control_tower_account_factory#8]
In the documentation it is stated that:
_The parameter custom_fields captures custom keys and values. You may want to collect additional metadata that can be logged with the account request. This metadata can trigger additional processing, either during provisioning or when updating an account_

However the data is **not** written to the: "aft-request-metadata" table, instead it is written to the "aft-request table".

This is a two fold problem
1. It is inconsistent with the other metadata that is written to the "request-metadata" table
2. It makes it harder to use as intended, as the partition key of the aft-request table is NOT the account ID, and therefore cannot easily be used in the account customization's pipelines. Giving the customer a second class experience compared to the expectations used by the proved built-in pipeline.

The codebuild pipelines are given the ACCOUNT ID as an environment variable, and this is already used by the buildspec to get data from the corresponding item from the metadata data table. 

e.g. ```CUSTOMIZATION=$(aws dynamodb get-item --table-name aft-request-metadata --key "{\"id\": {\"S\": \"$VENDED_ACCOUNT_ID\"}}" --attributes-to-get "account_customizations_name" | jq --raw-output ".Item.account_customizations_name.S")```

However, if **I** want to run a script, or terraform local-exec to grab some useful metadata, as part of my account/global customizations (as per the documentation).  I first have to query the account metadata table, extract the email address, then pass that into another dynamodb call to the other table to get the custom fields.

Please can we add the custom data to the metadata dynamodB and then I can just make use of the $VENDED_ACCOUNT_ID to get ALL the metadata I need for my customizations

**Comment by danno-rose** [comment]
#11 Linked

**Comment by balltrev** [comment]
We've opened a backlog item to track this feature request, thanks for the details here!
