### ISSUE TITLE
AWS Provider Version

### ISSUE THREAD

**Issue by mathewmoon** [aws-ia/terraform-aws-control_tower_account_factory#80]
There are several submodules that still rely on 3.x.x AWS Provider. These should be upgraded to keep current IMO.

```
 > grep -r '4.0.0' .terraform/modules 2>&1|egrep -v Binary                                                                                 ⚠️ 🆕 
1:.terraform/modules/aft/versions.tf:10:      version               = ">= 3.72, < 4.0.0"
2:.terraform/modules/aft/sources/aft-customizations-common/templates/customizations_pipeline/versions.tf:10:      version = ">= 3.72, < 4.0.0"
4:.terraform/modules/aft/.git/packed-refs:10:6c0754b0907778b36a6fe7a4427dd5a6fd8456da refs/tags/1.0.4
5:.terraform/modules/aft/modules/aft-backend/versions.tf:10:      version               = ">= 3.72, < 4.0.0"
6:.terraform/modules/aft/modules/aft-code-repositories/versions.tf:10:      version = ">= 3.72, < 4.0.0"
7:.terraform/modules/aft/modules/aft-iam-roles/versions.tf:10:      version               = ">= 3.72, < 4.0.0"
8:.terraform/modules/aft/modules/aft-account-provisioning-framework/versions.tf:10:      version = ">= 3.72, < 4.0.0"
9:.terraform/modules/aft/modules/aft-customizations/versions.tf:10:      version = ">= 3.72, < 4.0.0"
10:.terraform/modules/aft/modules/aft-ssm-parameters/versions.tf:10:      version = ">= 3.72, < 4.0.0"
11:.terraform/modules/aft/modules/aft-feature-options/versions.tf:10:      version               = ">= 3.72, < 4.0.0"
12:.terraform/modules/aft/modules/aft-lambda-layer/versions.tf:10:      version = ">= 3.72, < 4.0.0"
13:.terraform/modules/aft/modules/aft-account-request-framework/versions.tf:10:      version               = ">= 3.72, < 4.0.0"
```

**Comment by balltrev** [comment]
Thanks @mathewmoon. We've actually got a back log to support the latest major version update to the `hashicorp/aws` provider version update.

**Comment by mathewmoon** [comment]
TY. As a side note, there are some bugs that were fixed in 3.18 that have resurfaced in later 3.x versions. This particular case for us makes this a bit more important than it may be for other users because we manage some other IaC in the same TF that deploys the AFT module.

**Comment by mathewmoon** [comment]
@balltrev Do you have an idea of what release or the timeline on this?

**Comment by mathewmoon** [comment]
@balltrev Bump the question above. We are a full major version and several minor versions behind.

**Comment by balltrev** [comment]
Hey @mathewmoon, we've explored updating the hashicorp/aws provider to 4.* and we have an upgrade path but we're concerned it would introduce breaking changes for customers here.

We don't have a timeline right now to share

**Comment by mathewmoon** [comment]
Releasing a new version doesn't force existing users to implement it. Releasing then documenting the breaking changes suffices.

**Comment by mathewmoon** [comment]
@balltrev Any proposed date on this? Tech debt is piling up due to this.

**Comment by snebhu3** [comment]
@mathewmoon unfortunately, at this time we do not have an estimated date for releasing support for the latest major version of `hashicorp/aws` provider.
