### ISSUE TITLE
Bug: ct-aft-account-request pipeline does not update custom_fields

### ISSUE THREAD

**Issue by mathewmoon** [aws-ia/terraform-aws-control_tower_account_factory#83]
When the ct-aft-account-request pipeline runs it does not see the changes in custom_fields inside of the account request. Considering that these fields are now passed to parameter store to allow being consumed by the customization pipelines it is imperative that they are updated when the request terraform changes. This is not a feature request, but a bug. Please do not mark as a feature request and leave open until remediated. Thanks.

**Comment by balltrev** [comment]
Thanks for bringing this up @mathewmoon, we'll take a look into it

**Comment by stumins** [comment]
Hey @mathewmoon,

We tested making changes to custom fields & we do see both deltas in the Terraform plan after the change as well as changes to the SSM parameters after pipelines run - can you provide any logs + diffs that show what you are experiencing?

E.g. A commit that changes a custom field but does not result in a diff/update for that field in the "Terraform Apply" stage within Codebuild, or a Terraform plan diff indicating that a parameter change should be made, but no change was ever made to the SSM parameter.

**Comment by balltrev** [comment]
Hey @mathewmoon, feel free to reopen this if you've got some more data for us to dive into this issue, I'm going to go ahead and close this for now though, thanks!
