### ISSUE TITLE
Share state backend output between customization

### ISSUE THREAD

**Issue by thebigcosinus** [aws-ia/terraform-aws-control_tower_account_factory#86]
Hi,

I ve created two accounts with aft.
1 Account will be used for shared services. 
x other account will be used for clients.

How can I used terraform outputs from the shared network account into customer terraform accounts ?

Without AFT I would use data "terraform_remote_state" .

Can I use it with AFT and how I can launch account customization in order. Shared services account should be created before customer accounts ?

Thanks

**Comment by androidwiltron** [comment]
@thebigcosinus sorry it doesn't answer your question but there is already some good guidance on alternatives to using `terraform_remote_state` [here](https://www.terraform.io/language/state/remote-state-data).

I would use parameter store or secrets manager for sharing outputs between customisations.

**Comment by thebigcosinus** [comment]
@androidwiltron  thanks for the tips , I could be a good solution in by case.

**Comment by androidwiltron** [comment]
im not sure there is ordering with the account creation. however for account customisations that is manually invoked with step functions so you should be able to run the account customisations for the accounts in the order you wish manually at least

**Comment by balltrev** [comment]
Hey @thebigcosinus, for your first question, I do believe @androidwiltron's suggestions would work for cross-account data sharing. 

As for the second, if I'm understanding correctly, you'd make an initial account request commit containing only the "shared services" account you've mentioned, and then a subsequent account request containing all the "customer" accounts you want.

**Comment by stumins** [comment]
Hey @thebigcosinus, account customization pipelines are inherently independent from each other and do not directly share any state. I believe the suggestion of sharing outputs/values via SSM Parameter Store is an option that might work for your use case.

I'm going to close this issue due to inactivity - please feel free to open new issues as required.
