### ISSUE TITLE
Desactivate codebuild for python Pre-API-Helpers/Post-API-Helpers/

### ISSUE THREAD

**Issue by thebigcosinus** [aws-ia/terraform-aws-control_tower_account_factory#87]
Hi,

I will not used Pre-API-Helpers/Post-API-Helpers/  I would like to desactivate codebuild for this feature since in took a lot of time ?

Is this possible ?

Thanks

**Comment by balltrev** [comment]
I think this is a great call out @thebigcosinus, we've gone ahead and made a backlog to track this enhancement

**Comment by zxaos** [comment]
+1 from me here too, would love if this was configurable per account as all of our accounts currently only use the terraform step but I wouldn't want to permanently an account out of it if we needed the functionality in the future (I'd be happy to wait for a re-deploy of the pipeline via a flag in account-requests in that case though)

**Comment by stumins** [comment]
As of [1.5.0](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/releases/tag/1.5.0), the customizations pipelines now share a single CodeBuild container for all of the pre-api-helpers / apply-terraform / post-api-helpers stages. This significantly reduces the time spent when pre/post helpers are not defined.

I'm going to close this issue as I believe 1.5.0 meets the spirit of the request - please feel free to open new issues as required.
