### ISSUE TITLE
Issue ingesting existing accounts in 1.3.3: Email case sensitivity

### ISSUE THREAD

**Issue by stumins** [aws-ia/terraform-aws-control_tower_account_factory#90]
Hi team, I'm still facing this issue and we are unable to import some existing accounts to AFT.

Here is the CloudWatch logs of the Lambda function aft-account-request-processor:

``` 
{"time_stamp":"2022-02-21 00:18:29,683","log_level":"INFO","log_message":"Requested AccountEmail is valid: <Account_Email>"}

{"time_stamp":"2022-02-21 00:18:29,683","log_level":"INFO","log_message":"Invalid Request - AccountName already exists in Organization: <Account_Name>"}

{"time_stamp": "2022-02-21 00:18:30,083","log_level": "ERROR","log_message": "CT Request is not valid" }NoneType: None

{"time_stamp": "2022-02-21 00:18:30,105","log_level": "ERROR","log_message": {"FILE": "aft_account_request_processor.py","METHOD": "lambda_handler","EXCEPTION": ""} }Traceback (most recent call last): 

File "/var/task/aft_account_request_processor.py", line 65, in lambda_handler assert ct_request_is_validAssertionError

[ERROR] AssertionErrorTraceback (most recent call last):  File "/var/task/aft_account_request_processor.py", line 65, in lambda_handler assert ct_request_is_valid

{"time_stamp": "2022-02-21 00:20:07,123","log_level": "ERROR","log_message": "CT Request is not valid" }NoneType: None

{"time_stamp": "2022-02-21 00:20:07,123","log_level": "ERROR","log_message": {"FILE": "aft_account_request_processor.py","METHOD": "lambda_handler","EXCEPTION": ""} }Traceback (most recent call last):

File "/var/task/aft_account_request_processor.py", line 65, in lambda_handler assert ct_request_is_validAssertionError

[ERROR] AssertionErrorTraceback (most recent call last):  File "/var/task/aft_account_request_processor.py", line 65, in lambda_handler assert ct_request_is_valid
```

Specifically this account was created by AWS Control Tower, later the name and email were renamed and then incorporated to AFT.

For some reason AFT is trying to create a new account instead of on-boarding the account.

Let me know if you need any additional information.

_Originally posted by @fjromerom in https://github.com/aws-ia/terraform-aws-control_tower_account_factory/issues/75#issuecomment-1046752632_

**Comment by fjromerom** [comment]
Hi Stuart,

it turned out AFT does string matching for the email and it was not the case of this account. After setting the exact email the account got onboarded successfully.

Nowadays emails are uniq no matter the casing used and so AFT should not validate string matching.

Francisco.

**Comment by balltrev** [comment]
That makes sense! We'll go ahead and create a backlog to tackle this situation, thanks for helping call this out @fjromerom

**Comment by snebhu3** [comment]
Release [1.3.4](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/releases/tag/1.3.4) removes the Email case sensitivity requirement.
