### ISSUE TITLE
missleading error message when service quota exceeded

### ISSUE THREAD

**Issue by Dvelezs94** [aws-ia/terraform-aws-control_tower_account_factory#92]
On account provisioning, if the Control Tower account reached the quota limit for `maximum number of accounts`, the step function `aft-account-provisioning-framework` throws a missleading error.

```
{
  "Error": "Exception",
  "Cause": "{\"errorMessage\":\"Account not found for email\",\"errorType\":\"Exception\",\"stackTrace\":[\"  File \\\"/var/task/aft_account_provisioning_framework_get_account_info.py\\\", line 27, in lambda_handler\\n    return get_account_info(payload, session, ct_management_session)\\n\",\"  File \\\"/opt/python/lib/python3.8/site-packages/aft_common/account_provisioning_framework.py\\\", line 163, in get_account_info\\n    account_id = utils.get_account_id_from_email(ct_management_session, email)\\n\",\"  File \\\"/opt/python/lib/python3.8/site-packages/aft_common/aft_utils.py\\\", line 176, in get_account_id_from_email\\n    raise Exception(\\\"Account not found for email\\\")\\n\"]}"
}
```

This is because the request was made to Service Catalog and the email for the request is there, however the state is "Error", which is not valid here https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/main/sources/aft-lambda-layer/aft_common/account_request_framework.py#L33-L88

**Comment by stumins** [comment]
Hi @Dvelezs94, can you confirm what version of AFT you are using?

The lines in the posted stack trace don't match v1.3.3: https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/main/sources/aft-lambda-layer/aft_common/account_provisioning_framework.py#L163

**Comment by Dvelezs94** [comment]
I applied the AFT from main branch. Here are some extra details

Lambda throwing this error: `aft-account-provisioning-framework-get-account-info`

Cloudwatch logs error trace

```
{
    "time_stamp": "2022-02-22 02:26:13,847",
    "log_level": "ERROR",
    "log_message": {
        "FILE": "aft_account_provisioning_framework_get_account_info.py",
        "METHOD": "lambda_handler",
        "EXCEPTION": "Account not found for email"
    }
}
Traceback (most recent call last):
  File "/var/task/aft_account_provisioning_framework_get_account_info.py", line 27, in lambda_handler
    return get_account_info(payload, session, ct_management_session)
  File "/opt/python/lib/python3.8/site-packages/aft_common/account_provisioning_framework.py", line 163, in get_account_info
    account_id = utils.get_account_id_from_email(ct_management_session, email)
  File "/opt/python/lib/python3.8/site-packages/aft_common/aft_utils.py", line 176, in get_account_id_from_email
    raise Exception("Account not found for email")
Exception: Account not found for email

[ERROR] Exception: Account not found for email
Traceback (most recent call last):
  File "/var/task/aft_account_provisioning_framework_get_account_info.py", line 27, in lambda_handler
    return get_account_info(payload, session, ct_management_session)
  File "/opt/python/lib/python3.8/site-packages/aft_common/account_provisioning_framework.py", line 163, in get_account_info
    account_id = utils.get_account_id_from_email(ct_management_session, email)
  File "/opt/python/lib/python3.8/site-packages/aft_common/aft_utils.py", line 176, in get_account_id_from_email
    raise Exception("Account not found for email")
```

**Comment by stumins** [comment]
Thanks for providing these details - I've created a backlog item for us to improve the clarity of logging & error messages around account creation.

In the second stack trace you posted, I'm again seeing that:

```
File "/opt/python/lib/python3.8/site-packages/aft_common/account_provisioning_framework.py", line 163, in get_account_info:
    account_id = utils.get_account_id_from_email(ct_management_session, email)
```

Doesn't match line 163 in that [file for v1.3.3](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/main/sources/aft-lambda-layer/aft_common/account_provisioning_framework.py#L163)

```
account_id = payload["control_tower_event"]["detail"]["serviceEventDetails"]
            ["updateManagedAccountStatus"]["account"]["accountId"]
```

Can you let us know what AFT version you are running? In your AFT Management account, there is an parameter in Parameter Store named `/aft/config/aft/version` that should have the version.

**Comment by stumins** [comment]
Great, thank you for getting us that detail. 

Upgrading to v1.3.3 will not allow ingestion of an account in an error state in Service Catalog, but I believe it should improve the error message you see in that case.

We'll continue to work on improving clarity in the errors & logs.

**Comment by oh-diego-velez** [comment]
perfect, thank you very much @stumins!

**Comment by Dvelezs94** [comment]
perfect, thank you @stumins !

**Comment by stumins** [comment]
Release [1.3.6](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/releases/tag/1.3.6) improves the clarity of Lambda error messaging & now includes errors in notifications sent via the `aft-failure-notifications` SNS topic.
