### ISSUE TITLE
Undocumented `/aft/config/aft-ssh-key` and red herring error returned

### ISSUE THREAD

**Issue by nitrocode** [aws-ia/terraform-aws-control_tower_account_factory#93]
I noticed the following error in a couple builds

```
[Container] 2022/02/22 19:00:38 Running command ssh_key_parameter=$(aws ssm get-parameter --name /aft/config/aft-ssh-key --with-decryption || echo "None")
--

An error occurred (ParameterNotFound) when calling the GetParameter operation:
```

This ssm param is undocumented `/aft/config/aft-ssh-key` and the `aws ssm get-parameter` should output its error to stderr to prevent the above error.

This is located in a few places

https://github.com/aws-ia/terraform-aws-control_tower_account_factory/search?q=%2Faft%2Fconfig%2Faft-ssh-key

**Comment by snebhu3** [comment]
Thank you for the great call out. 
The SSM parameter /aft/config/aft-ssh-key was being used during beta release of AFT and is no longer being used. I will go ahead and create a backlog to remove these lines from our code.

**Comment by snebhu3** [comment]
Release [1.3.4](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/releases/tag/1.3.4) suppresses the misleading ParameterNotFound error.
