### ISSUE TITLE
AFT Cost in AWS Account

### ISSUE THREAD

**Issue by thebigcosinus** [aws-ia/terraform-aws-control_tower_account_factory#95]
Hi,

What is the cost of the product in the AWS Account. Infra Cost I mean, Nat Gateway, endpoints etc

Thanks for your help

**Comment by adam-daily** [comment]
Hi there. You can find more info about the cost of AFT in the [pricing section of the AFT documentation](https://docs.aws.amazon.com/controltower/latest/userguide/aft-pricing.html), including links to pricing details for the services you mentioned. That said, much of the cost of AFT is contingent on how AFT is configured and used in your accounts. If you need a more detailed cost analysis, reach out to your AWS account representative or AWS Premium Support.
