### ISSUE TITLE
Please allow configuring of the build timeouts

### ISSUE THREAD

**Issue by nitrocode** [aws-ia/terraform-aws-control_tower_account_factory#96]
The build timeouts are currently set to 60 minutes. We have a few jobs that need to take longer, at times. If this was configurable, we can avoid having to create our own separate code build pipelines/stages and reuse the existing ones in this module.

Thank you.

**Comment by stumins** [comment]
Hey @nitrocode, thanks for the feature request - good call-out here. I've created an item in our backlog to enable customization of build job timeouts.

**Comment by androidwiltron** [comment]
I also ran into this. A resource took greater than 30 minutes to provision and then state was not commited. a nasty one to stumble over. 
considering the terraform codebuild could be used for any number of resources I think 60mins is really quite conservative here and should be configurable for sure 
https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/1010f5ead7960114a4abf96afffb02c7a6e47e70/modules/aft-customizations/codebuild.tf#L64

**Comment by snebhu3** [comment]
Release [1.3.4](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/releases/tag/1.3.4) now has support for custom CodeBuild timeouts.
