### ISSUE TITLE
aft-account-request - Unable to import modules

### ISSUE THREAD

**Issue by kkadiyam** [aws-ia/terraform-aws-control_tower_account_factory#98]
Team, I started using the aft-account-request module, The terraform part on the code pipeline is completed but, Lambda aft-account-request-processor failed with below error .

I am using Github Enterprise+ TF oss

I did tried below solution it still didn't work:
https://aws.amazon.com/premiumsupport/knowledge-center/lambda-import-module-error-python/

{
  "errorMessage": "Unable to import module 'aft_account_request_processor': cannot import name 'modify_existing_account' from 'aft_common.account_request_framework' (/opt/python/lib/python3.8/site-packages/aft_common/account_request_framework.py)",
  "errorType": "Runtime.ImportModuleError",
  "stackTrace": []
}

Please let me know if you have any input.

**Comment by kkadiyam** [comment]
Thank You @balltrev for your quick reply.

I have 1.3.0 aft version, Where is the, Which file is setting up this version ?, So i can update it through control tower automation ?

**Comment by kkadiyam** [comment]
@balltrev  ahh i see that version file is the one it is setting the aft version right ?

**Comment by balltrev** [comment]
I believe it depends on how you've deployed AFT, but you'd need to update your AFT module by doing something like the `terraform get -update` in your CI/CD process for deploying AFT

**Comment by kkadiyam** [comment]
Thanks @balltrev I was able to fix the version, Seeing different error now, I did forked the latest code as of 1 hour back

[ERROR] ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the ProvisionProduct operation: No launch paths found for resource: prod-bgqptygn4vd4c
Traceback (most recent call last):
  File "/var/task/aft_account_request_processor.py", line 50, in lambda_handler
    response = create_new_account(
  File "/opt/python/lib/python3.8/site-packages/aft_common/account_request_framework.py", line 254, in create_new_account
    response = client.provision_product(
  File "/opt/python/lib/python3.8/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/python/lib/python3.8/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)

**Comment by balltrev** [comment]
I would double check that `prod-bgqptygn4vd4c` exists in Service Catalog in your Control Tower management account

**Comment by kkadiyam** [comment]
Yup, prod-bgqptygn4vd4c does exist in the AWS Service catalog. Not sure if i am missing any permissions

**Comment by kkadiyam** [comment]
Hi @balltrev  It went through "Creating new account leveraging parameters:" in aft-common/account_request_framework.py but haven't created the account, Its been more than 30 minutes, Not sure if it takes that long.

**Comment by balltrev** [comment]
You can check the provisioning account status in Service Catalog in your Control Tower management account. In my experience provisioning an account can take a while, so 30 minutes isn't unheard of

**Comment by kkadiyam** [comment]
Hi @balltrev Service catalog doesn't show anything on the new account creation, account-request-processor is running without any errors, but the account still  never getting created.

You have any insights on what might be the issue ?

**Comment by mikeantonelli** [comment]
@kkadiyam I use aft infrequently so I spin up and tear down the resources between uses to save on costs. I noticed this issue:

> No launch paths found for resource: prod-dpqqfywxxxx

Resolution:

You need to manually grant permission for the `AWSAFTExecution` **role**, in the AWS console: Service Catalog > Portfolios > AWS Control Tower Account Factory > Groups, roles, and users. You will also see the old permission, and it can be cleaned up (this one will be a GUID and not a full ARN). There are also possible other causes for this error:

> Common Causes:
>
> * You may be logged in as root. AWS Control Tower does not support creating accounts when you're logged in as root.
>
> * Your SSO user has not been added to the appropriate permission group. You may need to add your SSO user to one of these permission groups: AWSAccountFactory (for end-user access) or AWSServiceCatalogAdmins (for admin access).
>
> * If you are authenticated as an IAM user, you must add it to the AWS Service Catalog portfolio so that it has the correct permissions.

* https://docs.aws.amazon.com/controltower/latest/userguide/troubleshooting.html

**Comment by kkadiyam** [comment]
@snebhu3 @mikeantonelli Thank you very much for your inputs, That resolved the issue along with the below validation issue, We are good to close this. Really appreciate your help.

Variable validation for AccountName and other parameters #103
